/**
 * Pinned artifacts of the on-device alert tagger. GENERATED by
 * scripts/parser-ai/probe/write-manifest.cjs — do not edit by hand.
 *
 * The files are NOT in the repository or the app binary. They are hosted at
 * defaultBaseUrl (a GitHub release of this repository, tag below) and
 * downloaded only when the person asks, then verified by exact size and
 * SHA-256 before use. Encoder: intfloat/multilingual-e5-small (MIT),
 * vocabulary-pruned, fine-tuned on synthetic alerts only, dynamic int8.
 */
export type AiAlertNetworkType = 'wifi' | 'cellular' | 'none' | 'unknown';

export interface AiAlertModelStatus {
  state: 'not-downloaded' | 'downloading' | 'downloaded' | 'ready' | 'failed';
  version: string;
  downloadBytes: number;
  error: string | null;
}

/** Hard ceiling for the whole download, whatever a manifest says. */
export const MAX_TOTAL_BYTES = 45_000_000;

export const AI_ALERT_MODEL_MANIFEST = Object.freeze({
  version: "parser-ai-tagger-v1",
  defaultBaseUrl: "https://github.com/khanjer496-alt/Wafra/releases/download/parser-ai-tagger-v1",
  artifacts: [
    {
      "name": "tagger.int8.onnx",
      "bytes": 31555035,
      "sha256": "80c9eee4405fe51350c25ed8a45d2b5d0234a0263e98e88e3f54c3163225f0b9"
    },
    {
      "name": "tokenizer.json",
      "bytes": 1131342,
      "sha256": "2b7a2eb761fbff7ee2b46a87d4b1d0704c57c70499428e4fec86edf9b20670b1"
    },
    {
      "name": "tokenizer_config.json",
      "bytes": 443,
      "sha256": "a1d6bc8734a6f635dc158508bef000f8e2e5a759c7d92f984b2c86e5ff53425b"
    }
  ] as const,
  temperatures: {"status":0.6748,"family":0.7078,"direction":0.8983,"tags":0.7078,"intent":0.7423,"qtags":0.6134} as Record<'tags' | 'status' | 'family' | 'direction' | 'qtags' | 'intent', number>,
  labels: {"tags":["O","B-AMT","I-AMT","B-CUR","I-CUR","B-MER","I-MER","B-DATE","I-DATE","B-BAL","I-BAL","B-CUE_DEBIT","I-CUE_DEBIT","B-CUE_CREDIT","I-CUE_CREDIT","B-CUE_NONPOST","I-CUE_NONPOST"],"statuses":["completed","pending","declined","otp","promo","informational","future","request","unknown"],"families":["purchase","refund","transfer","salary","fee","withdrawal","card-payment","bill-payment","non-posting"],"directions":["debit","credit","none"],"maxTokens":192,"clsId":0,"sepId":2,"unkId":3} as {
    tags: string[];
    statuses: import('@/lib/ai-alert-extractor').AiAlertStatus[];
    families: import('@/lib/ai-alert-extractor').AiAlertFamily[];
    directions: ('debit' | 'credit' | 'none')[];
    maxTokens: number; clsId: number; sepId: number; unkId: number;
  },
  askLabels: {"qtags":["O","B-Q_ACCT","I-Q_ACCT","B-Q_CAT","I-Q_CAT","B-Q_CMP","I-Q_CMP","B-Q_MER","I-Q_MER","B-Q_PERIOD","I-Q_PERIOD","B-Q_TOPN","I-Q_TOPN"],"intents":["account_inventory","compare_periods","daily_average","income_total","largest_purchases","month_forecast","net_income_spending","possible_duplicates","recurring_changes","spending_total","subscriptions","top_accounts","top_categories","top_merchants","unknown","unusual_charges","upcoming_payments"]},
});
