import type { AlertMarketPack } from '@/lib/alert-market-pack-types';

export const US_EU_ALERT_MARKET_PACKS = {
  US: {
    market: 'US', currencies: ['USD'], currencyAliases: { '$': ['USD'] },
    rails: ['ach', 'wire transfer', 'zelle'],
    transferTerms: ['transfer', 'direct deposit'],
    utilityTerms: ['utility', 'electric', 'water bill', 'gas bill'],
    recurringTerms: ['recurring', 'autopay', 'standing instruction'],
  },
  GB: {
    market: 'GB', currencies: ['GBP'], currencyAliases: {},
    rails: ['faster payments', 'bacs', 'chaps'],
    transferTerms: ['bank transfer', 'faster payment', 'faster payments'],
    utilityTerms: ['council tax', 'energy bill', 'water bill', 'mobile bill'],
    recurringTerms: ['recurring', 'standing order'],
  },
  FR: {
    market: 'FR', currencies: ['EUR'], currencyAliases: {},
    rails: ['sepa'], transferTerms: ['virement'],
    utilityTerms: ['électricité', 'gaz', 'eau', 'téléphone'],
    recurringTerms: ['récurrent', 'abonnement'],
    postedTerms: ['débité', 'crédité', 'effectué', 'payé', 'payée'],
    failedTerms: ['refusé', 'rejeté', 'échoué', 'non payé', 'non payée', 'pas été payé', 'pas été payée'],
    futureTerms: ['sera débité', 'à venir'],
    debitTerms: ['débité', 'payé', 'payée'], creditTerms: ['crédité'],
  },
  DE: {
    market: 'DE', currencies: ['EUR'], currencyAliases: {},
    rails: ['sepa'], transferTerms: ['überweisung'],
    utilityTerms: ['strom', 'gas', 'wasser', 'telefon'],
    recurringTerms: ['dauerauftrag', 'abonnement'],
    failedTerms: ['abgelehnt', 'fehlgeschlagen', 'nicht bezahlt', 'nicht abgebucht'],
    futureTerms: ['wird abgebucht', 'wird morgen abgebucht', 'fällig'],
    debitTerms: ['belastet', 'abgebucht', 'bezahlt'], creditTerms: ['gutgeschrieben'],
  },
  ES: {
    market: 'ES', currencies: ['EUR'], currencyAliases: {},
    rails: ['sepa', 'bizum'], transferTerms: ['transferencia'],
    utilityTerms: ['suministros', 'electricidad', 'agua', 'teléfono'],
    recurringTerms: ['recurrente', 'suscripción'],
    failedTerms: ['rechazado', 'fallido', 'no pagado', 'no cargado'], futureTerms: ['se cargará', 'próximo'],
    debitTerms: ['cargado', 'pagado'], creditTerms: ['abonado'],
  },
  IT: {
    market: 'IT', currencies: ['EUR'], currencyAliases: {},
    rails: ['sepa'], transferTerms: ['bonifico'],
    utilityTerms: ['utenza', 'elettricità', 'acqua', 'telefono'],
    recurringTerms: ['ricorrente', 'abbonamento'],
    postedTerms: ['pagato', 'pagata'],
    failedTerms: ['rifiutato', 'fallito', 'non pagato', 'non addebitato'],
    futureTerms: ['sarà addebitato', 'in scadenza'],
    debitTerms: ['addebitato', 'pagato', 'pagata'], creditTerms: ['accreditato'],
  },
  NL: {
    market: 'NL', currencies: ['EUR'], currencyAliases: {},
    rails: ['sepa', 'ideal'], transferTerms: ['overboeking'],
    utilityTerms: ['energie', 'water', 'telefoon'],
    recurringTerms: ['periodiek', 'abonnement'],
    failedTerms: ['geweigerd', 'mislukt', 'niet betaald', 'niet afgeschreven'],
    futureTerms: ['wordt afgeschreven', 'wordt morgen afgeschreven', 'aankomend'],
    debitTerms: ['afgeschreven', 'betaald'], creditTerms: ['bijgeschreven'],
  },
} as const satisfies Record<string, AlertMarketPack>;
