/** English-first assistant copy; additional language packs can share the same local tools. */
export const assistantCopy = {
  title: 'Ask Wafra',
  back: 'Back',
  heading: 'Understand your transactions',
  privacy: 'Answers are calculated on your device from the transactions you have recorded.',
  placeholder: 'Ask about your transactions',
  send: 'Send question',
  newChat: 'New chat',
  explain: 'Explain this',
  explainCategory: 'Explain this category',
  askMerchant: 'Ask about this merchant',
  askIncome: 'Ask about this income',
  spendingChangedQuestion: 'Why did my spending change?',
  categoryChangedQuestion: (category: string) => `Why did my ${category} spending change?`,
  merchantChangedQuestion: (merchant: string) => `Why did spending at ${JSON.stringify(merchant)} change?`,
  incomeQuestion: (source: string) => `How much income did I receive from ${JSON.stringify(source)}?`,
  recentQuestions: (count: number) => `Showing your last ${count} questions.`,
  includedPortion: (amount: string) => `Included portion of a ${amount} transaction`,
  originalCashRecord: (record: string) => `Cash funding shown above. Original record: ${record}.`,
  reviewFinding: 'Review transactions',
  exploreFinding: 'Explore this',
  dataUsed: 'Data used',
  coverageCount: (records: number, accounts: number, totalAccounts: number) =>
    `${records} recorded transaction${records === 1 ? '' : 's'} · ${accounts} of ${totalAccounts} selected account${totalAccounts === 1 ? '' : 's'}`,
  observedDates: (first: string, last: string) => `Recorded activity: ${first} to ${last}.`,
  period: 'Change reporting period',
  local: 'Calculated on this device',
  viewTransactions: 'View transactions',
  viewPayments: 'Review payments',
  evidenceTitle: 'Transactions behind this answer',
  recorded: 'Based on recorded transactions. Missing imports can affect totals and comparisons.',
  stale: 'Your ledger has changed since this answer.',
  refresh: 'Refresh answer',
  failed: 'This answer could not be calculated. Try a shorter question or review your transactions.',
  loading: 'Loading your transactions…',
  emptyTitle: 'Start with your transactions',
  emptyBody: 'Import your history or add a transaction, then ask about spending, income and changes.',
  import: 'Import transactions',
  add: 'Add a transaction',
  noRecords: 'No recorded transactions matched this answer.',
  previous: 'Previous page',
  next: 'Next page',
} as const;
