import type { CategoryId } from '@/lib/types';

/**
 * Curated consumer-brand table: merchant descriptor -> category.
 *
 * A LAST-RESORT fallback for markets outside the launch-tested AE/SA
 * vocabulary. universal-categorization.ts consults it only after the user's
 * own merchant rules, activity words and the existing merchant vocabulary have
 * all failed to resolve a category, and never for AE/SA.
 *
 * Written from public knowledge of what each chain sells. It was NOT fitted to
 * the phase-1 evaluation descriptors (scripts/parser-ai/category/merchants.cjs).
 *
 * Data format, one block per country (GLOBAL applies everywhere):
 *   `<alias>: PATTERN; PATTERN; ...`
 * - A PATTERN is an uppercase regex fragment matched against a normalised
 *   descriptor (accents stripped, apostrophes removed, `* _ # | ~` -> space).
 *   A space inside a pattern means "zero or more separators" (space . / & + , -),
 *   so `TIM HORTONS` also matches `TIMHORTONS` and `TIM-HORTONS`.
 * - Every pattern is anchored on alphanumeric boundaries. A trailing store
 *   number is allowed (`KROGER0412`) unless the pattern itself ends in a digit.
 * - A leading `!` GATES the pattern to that block's country: it applies only
 *   when the caller's market is that country. Use it for short or ambiguous
 *   tokens (DIA, BIM, D1, ACTION, COOP, TIM, JUMBO, ORANGE, CLARO...).
 * - When several patterns match, the longest wins (UBER EATS over UBER). If a
 *   different-category match lies outside the winner's span, nothing is
 *   returned: `MTA NYCT SUBWAY` is neither a sandwich nor provably a train.
 */

const ALIAS: Record<string, CategoryId> = {
  g: 'groceries', d: 'dining', t: 'transport', u: 'utilities', c: 'telecom', s: 'shopping', h: 'health',
  p: 'personal-care', hs: 'home-services', e: 'education', tr: 'travel', en: 'entertainment',
  sw: 'software', i: 'investing', ch: 'charity', gv: 'government',
};

const TABLE: Readonly<Record<string, string>> = {
  GLOBAL: `
sw: APPLE COM BILL; ITUNES COM; ITUNES; ICLOUD; GOOGLE (?:STORAGE|ONE|WORKSPACE|GSUITE|CLOUD|PLAY|DOMAINS); GSUITE; MICROSOFT; MSFT; ADOBE; DROPBOX; GITHUB; OPENAI; CHATGPT; ANTHROPIC; CLAUDE AI; NOTION (?:LABS|SO); CANVA; ZOOM (?:US|COM|VIDEO); SLACK; FIGMA; JETBRAINS; ATLASSIAN; 1PASSWORD; LASTPASS; NORDVPN; NORD SEC; EXPRESSVPN; GODADDY; NAMECHEAP; SQUARESPACE; WIX COM; SHOPIFY; AWS (?:EMEA|AMAZON|US); AMAZON WEB SERVICES; DIGITALOCEAN; HEROKU; VERCEL; CLOUDFLARE; MAILCHIMP; GRAMMARLY; EVERNOTE; TODOIST; CURSOR (?:AI|COM); ANYSPHERE; MIDJOURNEY; PERPLEXITY; KASPERSKY; NORTONLIFELOCK; MCAFEE; SURFSHARK; PROTON (?:AG|MAIL|VPN)
en: NETFLIX; SPOTIFY; DISNEY (?:PLUS|\\+); HULU; HBO MAX; HBOMAX; YOUTUBE; YOUTUBE ?(?:PREMIUM|MUSIC|TV); PRIME VIDEO; AMAZON PRIME VIDEO; AMAZON MUSIC; AMZN DIGITAL; AMAZON DIGITAL; KINDLE (?:UNLIMITED|STORE|SVCS|EDITION); APPLE (?:TV|MUSIC|ARCADE); PARAMOUNT (?:PLUS|\\+); PEACOCK; CRUNCHYROLL; DAZN; STEAMGAMES; STEAM (?:GAMES|POWERED|PURCHASE|COM); STEAMPOWERED; PLAYSTATION; SONY PLAYSTATION; XBOX; NINTENDO; EPIC GAMES; RIOT GAMES; BLIZZARD; BATTLE NET; ELECTRONIC ARTS; ROBLOX; TWITCH; AUDIBLE; DEEZER; TIDAL (?:COM|MUSIC); SOUNDCLOUD; PATREON; TICKETMASTER; LIVE NATION; EVENTBRITE; STUBHUB; VIAGOGO; IMAX; SHOWMAX; SHAHID; STARZPLAY; ANGHAMI; OSN (?:PLUS|\\+|STREAMING); APPLE COM TV
s: AMAZON; AMZN; AMZN MKTP; EBAY; ALIEXPRESS; ALIBABA; TEMU; SHEIN; ETSY; WISH COM; IKEA; ZARA; H & M; HM COM; UNIQLO; NIKE; ADIDAS; PUMA (?:STORE|COM|SE); APPLE (?:STORE|ONLINE STORE|RETAIL); SAMSUNG (?:STORE|ELECTRONICS|SHOP|COM); DECATHLON; PRIMARK; MASSIMO DUTTI; PULL (?:&|AND) BEAR; BERSHKA; STRADIVARIUS; OYSHO; LEVIS; LEVI STRAUSS; C & A; LEGO; TOYS R US; MUJI; SWAROVSKI; TK MAXX; TJ MAXX; FOREVER 21; ZALANDO; ASOS; FARFETCH; LOUIS VUITTON; GUCCI; SKECHERS; FOOT LOCKER; SUPERDRY; MINISO; DAISO; FLYING TIGER; LULULEMON; UNDER ARMOUR; NEW BALANCE; CONVERSE (?:COM|STORE); VANS STORE; CRATE (?:&|AND) BARREL; POTTERY BARN; WILLIAMS SONOMA; BIRKENSTOCK; PANDORA JEWEL
g: CARREFOUR; LIDL; ALDI; SPAR; EUROSPAR; INTERSPAR; 7 ELEVEN; SEVEN ELEVEN; COSTCO; WHOLE FOODS; WHOLEFDS; AMAZON FRESH; INSTACART; AUCHAN; SHOPRITE; FAMILYMART; FAMILY MART; LAWSON; GETIR; GORILLAS; FLINK; NETTO; MINISTOP; GRAB MART; GRABMART
d: MCDONALDS; MC DONALDS; BURGER KING; KFC; PIZZA HUT; DOMINOS; DOMINO S PIZZA; PAPA JOHNS; LITTLE CAESARS; STARBUCKS; COSTA COFFEE; TIM HORTONS; DUNKIN; KRISPY KREME; WENDYS; TACO BELL; CHIPOTLE; FIVE GUYS; SHAKE SHACK; POPEYES; CHICK FIL A; DAIRY QUEEN; HARDEES; CARLS JR; JOLLIBEE; NANDOS; PRET A MANGER; WAGAMAMA; PANDA EXPRESS; OUTBACK STEAKHOUSE; TGI FRIDAYS; HARD ROCK CAFE; CHEESECAKE FACTORY; JOHNNY ROCKETS; BASKIN ROBBINS; COLD STONE; HAAGEN DAZS; CINNABON; AUNTIE ANNES; WINGSTOP; DELIVEROO; JUST EAT; UBER EATS; UBEREATS; DOORDASH; GRUBHUB; POSTMATES; FOODPANDA; GLOVO; WOLT; RAPPI; IFOOD; SWIGGY; ZOMATO; TALABAT; MENULOG; SKIPTHEDISHES; SKIP THE DISHES; LIEFERANDO; THUISBEZORGD; YEMEKSEPETI; PEDIDOSYA; PEDIDOS YA; DIDI FOOD; GRAB FOOD; GRABFOOD; GOFOOD; GO FOOD; SHOPEEFOOD; SHOPEE FOOD; BOLT FOOD; CAREEM FOOD; CAREEM NOW; CAFFE NERO; PAUL BAKERY; CHATIME; DIN TAI FUNG; SUBWAY; GRAB (?:AND|N) GO; PEETS COFFEE; BLUE BOTTLE; ARABICA COFFEE; % ARABICA
t: UBER; LYFT; BOLT; BOLT EU; CAREEM; GRAB; GOJEK; GO JEK; GORIDE; GOCAR; DIDI; CABIFY; OLACABS; OLA CABS; INDRIVE; INDRIVER; YANGO; FREE NOW; FREENOW; MYTAXI; HEETCH; BLABLACAR; FLIXBUS; FLIXTRAIN; GREYHOUND; MEGABUS; NATIONAL EXPRESS; LIME (?:RIDE|SCOOTER|BIKE); LIMEBIKE; VOI (?:TECHNOLOGY|SCOOTER); SHELL; BP (?:OIL|CONNECT|EXPRESS|PULSE|SERVICE STATION|STATION|FUEL); BP \\d{3,}; ESSO; EXXON; EXXONMOBIL; MOBIL (?:OIL|\\d{3,}); CHEVRON; TEXACO; CALTEX; TOTALENERGIES; TOTAL ENERGIES; TOTAL ACCESS; Q8; REPSOL; CEPSA; MOEVE; GALP; AGIP; ENILIVE; OMV; CIRCLE K; PETRONAS; PETROBRAS; PERTAMINA; PUMA ENERGY; VIVO ENERGY; RUBIS; ENGEN; SASOL; ADNOC; ENOC; EPPCO; ALDREES; SASCO; PARKMOBILE; PAYBYPHONE; EASYPARK; Q PARK; APCOA; INDIGO PARK; INDIGO PARKING; SPOTHERO; TESLA SUPERCHARGER; CHARGEPOINT; IONITY
h: BUPA; BOOTS (?:PHARMACY|UK|THE CHEMIST|OPTICIANS); SPECSAVERS; VISION EXPRESS; ANYTIME FITNESS; PLANET FITNESS; GOLDS GYM; FITNESS FIRST; BASIC FIT; PUREGYM; PURE GYM; CLASSPASS; F45 TRAINING; ORANGETHEORY; CRUNCH FITNESS; LA FITNESS; 24 HOUR FITNESS; EQUINOX; VIRGIN ACTIVE; SNAP FITNESS; MCFIT; SMART FIT; SMARTFIT; BODYTECH; GUARDIAN PHARMACY; LENSCRAFTERS; WARBY PARKER
p: SEPHORA; ULTA; LUSH; THE BODY SHOP; BODY SHOP; BATH (?:&|AND) BODY WORKS; MAC COSMETICS; KIKO; KIKO MILANO; YVES ROCHER; SALLY BEAUTY; SUPERCUTS; GREAT CLIPS; SPORT CLIPS; TONI (?:&|AND) GUY; RITUALS; L OCCITANE; LOCCITANE; WATSONS; FACES BEAUTY; DOUGLAS (?:PARFUM|COSMETICS|PARFUMERIE); PARFUMERIE DOUGLAS; NOCIBE; MARIONNAUD; DM DROGERIE; DM FIL; ROSSMANN; KRUIDVAT; BENEFIT COSMETICS; CHARLOTTE TILBURY
e: COURSERA; UDEMY; EDX; SKILLSHARE; MASTERCLASS; DUOLINGO; BABBEL; BUSUU; LINKEDIN LEARNING; PLURALSIGHT; CODECADEMY; DATACAMP; CHEGG; QUIZLET; STUDOCU; IELTS; ETS TOEFL; TOEFL; COLLEGE BOARD; BYJUS; UNACADEMY
ch: UNICEF; RED CROSS; CROIX ROUGE; CRUZ ROJA; CROCE ROSSA; RODE KRUIS; ROTES KREUZ; RED CRESCENT; OXFAM; SAVE THE CHILDREN; WWF; MEDECINS SANS FRONTIERES; MSF DONATION; DOCTORS WITHOUT BORDERS; AMNESTY; GREENPEACE; WIKIMEDIA; WIKIPEDIA; UNHCR; WORLD VISION; ISLAMIC RELIEF; GOFUNDME; JUSTGIVING; CANCER RESEARCH; SALVATION ARMY; HABITAT FOR HUMANITY; WORLD FOOD PROGRAMME; WFP DONATION; PLAN INTERNATIONAL; CHARITY WATER; KHAN ACADEMY
i: ROBINHOOD; COINBASE; BINANCE; KRAKEN; ETORO; TRADING 212; TRADING212; DEGIRO; INTERACTIVE BROKERS; IBKR; CHARLES SCHWAB; SCHWAB; VANGUARD; E TRADE; ETRADE; WEBULL; CRYPTO COM; BYBIT; OKX; KUCOIN; BITSTAMP; BITPANDA; LUNO; MOOMOO; FUTU; TIGER BROKERS; STASHAWAY; FREETRADE; SCALABLE CAPITAL; TRADE REPUBLIC; ACORNS; BETTERMENT; WEALTHFRONT; TASTYTRADE; WEALTHSIMPLE; QUESTRADE; SHARESIES; COMMSEC; SELFWEALTH; HARGREAVES LANSDOWN; AJ BELL; NUTMEG; MONEYBOX; ZERODHA; GROWW; UPSTOX; ANGEL ONE; ANGEL BROKING; SMALLCASE; BITSO; INDODAX; COINDCX; WAZIRX; EASYEQUITIES; BITKUB
tr: BOOKING COM; AIRBNB; EXPEDIA; HOTELS COM; AGODA; TRIVAGO; KAYAK; SKYSCANNER; TRIP COM; MARRIOTT; HILTON; HYATT; IHG; HOLIDAY INN; ACCOR; NOVOTEL; IBIS (?:HOTEL|BUDGET|STYLES); SOFITEL; MERCURE; RADISSON; FOUR SEASONS; SHERATON; WESTIN; RITZ CARLTON; BEST WESTERN; WYNDHAM; EMIRATES (?:AIRLINE|AIRLINES|SKYWARDS); QATAR (?:AIRWAYS|AIR); ETIHAD; TURKISH AIRLINES; LUFTHANSA; BRITISH AIRWAYS; AIR FRANCE; KLM; RYANAIR; EASYJET; WIZZ AIR; WIZZAIR; SINGAPORE AIRLINES; CATHAY PACIFIC; QANTAS; DELTA (?:AIR|AIRLINES); UNITED AIRLINES; AMERICAN AIRLINES; AA COM; SOUTHWEST (?:AIR|AIRLINES); JETBLUE; ALASKA AIR; AIR CANADA; WESTJET; IBERIA; VUELING; TAP AIR PORTUGAL; FLYTAP; SWISS INTL AIR; SWISS INTERNATIONAL; AUSTRIAN AIRLINES; FLYSAS; FINNAIR; AEGEAN; FLYPGS; PEGASUS (?:AIRLINES|HAVA); AIR INDIA; INDIGO AIRLINES; SPICEJET; AIRASIA; AIR ASIA; CEBU PACIFIC; PHILIPPINE AIRLINES; GARUDA; LION AIR; MALAYSIA AIRLINES; FLYSCOOT; JETSTAR; VIRGIN (?:AUSTRALIA|ATLANTIC); AIR NEW ZEALAND; LATAM (?:AIRLINES|AIR|AIRWAYS|COM); AVIANCA; AEROMEXICO; VOLARIS; VIVA AEROBUS; VIVAAEROBUS; AEROLINEAS ARGENTINAS; SOUTH AFRICAN AIRWAYS; FLYSAFAIR; KULULA; KENYA AIRWAYS; ETHIOPIAN AIRLINES; EGYPTAIR; ROYAL AIR MAROC; AIR ARABIA; FLYDUBAI; SAUDIA; FLYNAS; GULF AIR; OMAN AIR; HERTZ; AVIS (?:RENT|BUDGET|CAR|UK|RAC); EUROPCAR; SIXT; ENTERPRISE RENT A CAR; BUDGET RENT; ALAMO RENT; GETYOURGUIDE; VIATOR; KLOOK; HOSTELWORLD; VRBO; MAKEMYTRIP; GOIBIBO; CLEARTRIP; TRAVELOKA; TIKET COM; DESPEGAR; DECOLAR; EDREAMS; LASTMINUTE; OPODO; EUROSTAR; OYO ROOMS; OYO HOTELS
c: VODAFONE; AIRTEL; MTN (?:AIRTIME|DATA|MOBILE|GROUP|NIGERIA|SA|UGANDA|GHANA); T MOBILE; LEBARA; LYCAMOBILE
`,
  US: `
g: KROGER; SAFEWAY; PUBLIX; TRADER JOES?; ALBERTSONS; H-E-B; !HEB; MEIJER; WEGMANS; HY VEE; FOOD LION; STOP (?:&|AND) SHOP; GIANT EAGLE; GIANT FOOD; HARRIS TEETER; SPROUTS; FRED MEYER; RALPHS; VONS; JEWEL OSCO; WINCO; RALEYS; SAVE A LOT; PIGGLY WIGGLY; WINN DIXIE; !INGLES; KING SOOPERS; FOOD 4 LESS; STATER BROS; SAMS CLUB; SAMSCLUB; BJS WHOLESALE; WALMART; WAL MART; WM SUPERCENTER; WALMART SUPERCENTER; WAWA; FOOD CITY; SHOPRITE; ACME MARKETS; PRICE CHOPPER; SMART (?:&|AND) FINAL; GROCERY OUTLET; LUCKY SUPERMARKET; MARKET BASKET; HANNAFORD; DILLONS; TOM THUMB; RANDALLS
s: WALMART COM; WALMART MARKETPLACE; !TARGET; TARGET COM; HOME DEPOT; THE HOME DEPOT; LOWES; BEST BUY; BESTBUY; MACYS; NORDSTROM; KOHLS; JCPENNEY; JC PENNEY; MARSHALLS; ROSS STORES; ROSS DRESS; BURLINGTON (?:STORES|COAT); OLD NAVY; BANANA REPUBLIC; WAYFAIR; CHEWY; PETSMART; PETCO; STAPLES; OFFICE DEPOT; OFFICEMAX; BED BATH; VICTORIAS SECRET; AMERICAN EAGLE; ABERCROMBIE; HOLLISTER; DICKS SPORTING; ACADEMY SPORTS; REI COOP; REI COM; !REI; JOANN; HOBBY LOBBY; GAMESTOP; MICRO CENTER; B (?:&|AND) H PHOTO; NEWEGG; SAKS; BLOOMINGDALES; NEIMAN MARCUS; DOLLAR TREE; DOLLAR GENERAL; FAMILY DOLLAR; FIVE BELOW; BIG LOTS; OLLIES; TRACTOR SUPPLY; HARBOR FREIGHT; KMART; ZAPPOS; QVC
d: CHIPOTLE; PANERA; CHICK FIL A; SONIC DRIVE; ARBYS; JACK IN THE BOX; IN N OUT; WHATABURGER; OLIVE GARDEN; APPLEBEES; IHOP; DENNYS; CRACKER BARREL; RED LOBSTER; BUFFALO WILD WINGS; CHILIS; TEXAS ROADHOUSE; !SEAMLESS; SEAMLESSWEB; CARIBOU COFFEE; DUTCH BROS; JERSEY MIKES; JIMMY JOHNS; FIREHOUSE SUBS; RAISING CANES; ZAXBYS; CULVERS; SWEETGREEN; !CAVA; QDOBA; EL POLLO LOCO; DEL TACO; JAMBA; TST; TOAST TAB
t: MTA; MTA NYCT; NYCT PAYGO; OMNY; !BART; CLIPPER CARD; WMATA; SMARTRIP; VENTRA; MBTA; SEPTA; METRA; NJ TRANSIT; !NJT; LIRR; AMTRAK; E ?ZPASS; SUNPASS; FASTRAK; TXTAG; PARKWHIZ; LAZ PARKING; SP PLUS; JIFFY LUBE; VALVOLINE; AUTOZONE; OREILLY AUTO; ADVANCE AUTO; PEP BOYS; NAPA AUTO; ELECTRIFY AMERICA; EVGO; SHEETZ; QUIKTRIP; RACETRAC; !SPEEDWAY; MARATHON PETRO; SUNOCO; VALERO; CITGO; PHILLIPS 66; CONOCO; !ARCO; ARCO AMPM; LOVES TRAVEL; PILOT TRAVEL; FLYING J; CASEYS GENERAL
h: CVS; WALGREENS; RITE AID; DUANE READE; KAISER PERMANENTE; QUEST DIAGNOSTICS; LABCORP; ONE MEDICAL; TELADOC; GOODRX; ZOCDOC; HIMS; MINUTECLINIC; PELOTON; 1 800 CONTACTS
en: !AMC; AMC THEATRES; AMC \\d{3,}; REGAL CINEMAS; !REGAL; CINEMARK; FANDANGO; SIRIUSXM; SIRIUS XM; !PANDORA; DAVE (?:&|AND) BUSTERS; TOPGOLF; SIX FLAGS; DISNEYLAND; WALT DISNEY WORLD; SEATGEEK; DIRECTV; DISH NETWORK; SLING TV
c: VERIZON; VZW; AT & T; AT (?:&|AND) T MOBILITY; !ATT; ATT BILL; !SPRINT; COMCAST; XFINITY; !SPECTRUM; CHARTER SPECTRUM; COX COMM; CRICKET WIRELESS; MINT MOBILE; METROPCS; METRO BY T MOBILE; BOOST MOBILE; GOOGLE FI; US CELLULAR; FRONTIER COMM; CENTURYLINK; !OPTIMUM; VISIBLE WIRELESS; STRAIGHT TALK; TRACFONE
u: CON ED; CONED; CONSOLIDATED EDISON; PG (?:&|AND) E; PGANDE; PACIFIC GAS; DUKE ENERGY; SOUTHERN CALIFORNIA EDISON; SO CAL EDISON; SDG (?:&|AND) E; DOMINION ENERGY; FLORIDA POWER; !FPL; XCEL ENERGY; NATIONAL GRID; EVERSOURCE; PSEG; !COMED; GEORGIA POWER; ENTERGY; AMEREN; DTE ENERGY; CONSUMERS ENERGY; !PECO; !BGE; AMERICAN ELECTRIC POWER; TXU ENERGY; RELIANT ENERGY; !SPIRE; CENTERPOINT; LADWP; AMERICAN WATER; WASTE MANAGEMENT; WM EZPAY; REPUBLIC SERVICES; SOCALGAS; PEOPLES GAS; NICOR GAS
gv: IRS; USATAXPYMT; IRS TREAS; US TREASURY; DMV; TSA PRECHECK; TRAVEL STATE GOV; USCIS
hs: TASKRABBIT; !ANGI; ANGIES LIST; HANDY COM; THUMBTACK; ROTO ROOTER; TERMINIX; ORKIN; MOLLY MAID; MERRY MAIDS; SERVPRO
i: FIDELITY INVESTMENTS; FIDELITY BROKERAGE; STASH INVEST; M1 FINANCE; PUBLIC COM; SOFI INVEST
`,
  CA: `
g: LOBLAWS; SOBEYS; NO FRILLS; NOFRILLS; !METRO; METRO INC; FOOD BASICS; FRESHCO; FARM BOY; SAVE ON FOODS; REAL CANADIAN SUPERSTORE; RCSS; T (?:&|AND) T SUPERMARKET; LONGOS; ZEHRS; FORTINOS; PROVIGO; !MAXI; IGA; FOODLAND; VALU MART; YOUR INDEPENDENT GROCER; INDEPENDENT GROCER; !SAQ; LCBO; BEER STORE; WALMART
d: A & W; HARVEYS; SWISS CHALET; MARY BROWNS; BOSTON PIZZA; THE KEG; EAST SIDE MARIOS; SECOND CUP; PIZZA PIZZA; MONTANAS; KELSEYS; MR SUB; ST HUBERT; TIMS
t: PETRO CANADA; PETROCAN; ULTRAMAR; !HUSKY; !PRESTO; !TTC; !STM; OC TRANSPO; TRANSLINK; COMPASS CARD; GO TRANSIT; VIA RAIL; UP EXPRESS; 407 ETR; !GREEN P; IMPARK; CANADIAN TIRE GAS; CO OP GAS
h: SHOPPERS DRUG MART; SHOPPERS DRUG; !SDM; REXALL; JEAN COUTU; PHARMAPRIX; UNIPRIX; FAMILIPRIX; GOODLIFE FITNESS
s: CANADIAN TIRE; HUDSONS BAY; !WINNERS; HOMESENSE; SPORT CHEK; MARKS WORK; !SIMONS; DOLLARAMA; LONDON DRUGS; !RONA; HOME HARDWARE; !INDIGO; INDIGO BOOKS; CHAPTERS INDIGO; !ROOTS; ARITZIA; CANADA COMPUTERS; !MEC; MOUNTAIN EQUIPMENT; GIANT TIGER; LEONS FURNITURE; !THE BRICK; BEST BUY
c: !ROGERS; BELL CANADA; BELL MOBILITY; !BELL; TELUS; !FIDO; KOODO; VIRGIN PLUS; VIRGIN MOBILE; FREEDOM MOBILE; VIDEOTRON; SHAW (?:CABLE|COMM|DIRECT); PUBLIC MOBILE; CHATR; LUCKY MOBILE; COGECO
u: HYDRO ONE; HYDRO QUEBEC; BC HYDRO; TORONTO HYDRO; ENBRIDGE; FORTISBC; FORTIS ALBERTA; !EPCOR; ENMAX; !ATCO; ALECTRA
en: CINEPLEX; !CRAVE; CRAVE TV
tr: PORTER AIRLINES; FLYPORTER; FLAIR AIRLINES; SUNWING; AIR TRANSAT
gv: SERVICE ?ONTARIO; CANADA REVENUE; !CRA; SERVICE CANADA; SAAQ
`,
  GB: `
g: TESCO; SAINSBURYS?; SAINSBURY S; JS ONLINE; ASDA; MORRISONS; WM MORRISON; WAITROSE; OCADO; !ICELAND; ICELAND FOODS; CO ?OP (?:FOOD|GROUP|RETAIL|STORES?); COOPERATIVE FOOD; CO OPERATIVE FOOD; M ?& ?S SIMPLY FOOD; M ?& ?S FOOD; !NISA; BUDGENS; COSTCUTTER; !ONE STOP; FARMFOODS; HERON FOODS; !BOOTHS; MAJESTIC WINE; GOPUFF; !ZAPP
d: !PRET; CAFFE NERO; GREGGS; ITSU; PIZZA EXPRESS; PIZZAEXPRESS; ZIZZI; ASK ITALIAN; FRANKIE (?:&|AND) BENNYS; TOBY CARVERY; HARVESTER; BEEFEATER; WETHERSPOON; JD WETHERSPOON; GOURMET BURGER; YO SUSHI; !TORTILLA; DISHOOM; HONEST BURGERS; LEON RESTAURANTS; WASABI SUSHI; GAILS BAKERY; BILLS RESTAURANT; PIZZA HUT DELIVERY
t: TFL; TRANSPORT FOR LONDON; TRAINLINE; NATIONAL RAIL; LNER; AVANTI WEST COAST; GWR; GREAT WESTERN RAIL; SOUTHERN RAIL; SOUTHEASTERN; NORTHERN (?:RAIL|TRAINS); SCOTRAIL; THAMESLINK; ARRIVA; STAGECOACH; FIRST BUS; RINGGO; JUSTPARK; NCP; DART CHARGE; ADDISON LEE; KWIK FIT; !HALFORDS; GREATER ANGLIA; C2C RAIL; ELIZABETH LINE; MERSEYRAIL
h: !BOOTS; SUPERDRUG; LLOYDS PHARMACY; LLOYDSPHARMACY; THE GYM GROUP; GYM GROUP; DAVID LLOYD; NUFFIELD HEALTH; BANNATYNE; PHARMACY2U
s: ARGOS; JOHN LEWIS; CURRYS; B (?:&|AND) Q; MARKS (?:&|AND) SPENCER; M & S; NEXT (?:RETAIL|PLC|DIRECTORY); !NEXT; SPORTS DIRECT; JD SPORTS; HOMEBASE; WICKES; SCREWFIX; TOOLSTATION; DUNELM; B & M (?:RETAIL|BARGAINS|STORES); POUNDLAND; WILKO; HOBBYCRAFT; WHSMITH; WH SMITH; WATERSTONES; DEBENHAMS; SELFRIDGES; HARRODS; HARVEY NICHOLS; !FRASERS; HOUSE OF FRASER; RIVER ISLAND; NEW LOOK; BOOHOO; PRETTYLITTLETHING; VERY CO UK; AO COM; AO RETAIL; ROBERT DYAS; MATALAN; PETS AT HOME; THE WORKS; CARD FACTORY; SCHUH
tr: JET2; VIRGIN ATLANTIC; PREMIER INN; TRAVELODGE; LOGANAIR
c: EE (?:LIMITED|LTD|MOBILE|BROADBAND); !EE; !O2; O2 UK; THREE (?:UK|MOBILE|CO UK); BT (?:GROUP|BROADBAND|PLC|MOBILE); BRITISH TELECOM; VIRGIN MEDIA; TALKTALK; GIFFGAFF; TESCO MOBILE; PLUSNET; HYPEROPTIC; COMMUNITY FIBRE; !SMARTY; ID MOBILE; SKY MOBILE; SKY BROADBAND
u: BRITISH GAS; OCTOPUS ENERGY; EDF ENERGY; EON NEXT; E ON (?:ENERGY|NEXT|UK); OVO ENERGY; SCOTTISH POWER; !SSE; THAMES WATER; SEVERN TRENT; ANGLIAN WATER; UNITED UTILITIES; YORKSHIRE WATER; SOUTHERN WATER; WESSEX WATER; SOUTH EAST WATER; AFFINITY WATER; NORTHUMBRIAN WATER; WELSH WATER; DWR CYMRU; SCOTTISH WATER; SHELL ENERGY; UTILITA; SO ENERGY
gv: HMRC; DVLA; COUNCIL TAX; TV LICEN[CS]E; TV LICENSING; HM PASSPORT; GOV UK
en: ODEON; VUE CINEMA; VUE ENTERTAINMENT; CINEWORLD; EVERYMAN CINEMA; PICTUREHOUSE; NOW TV; NOWTV; BRITBOX; SKY (?:DIGITAL|UK|SUBSCRIPTION|TV|STORE); !SKY; SEETICKETS; SEE TICKETS
ch: BRITISH RED CROSS; !MACMILLAN; BRITISH HEART; RNLI; NSPCC; RSPCA; BARNARDOS; MIND CHARITY
`,
  IE: `
g: TESCO; DUNNES; DUNNES STORES; SUPERVALU; !CENTRA; !MACE; LIDL; ALDI; SPAR
t: APPLEGREEN; MAXOL; !TOPAZ; CIRCLE K; LEAP CARD; IRISH RAIL; IARNROD EIREANN; DUBLIN BUS; !LUAS; BUS EIREANN; EFLOW; FREENOW
d: SUPERMACS; BUTLERS CHOCOLATE; INSOMNIA COFFEE; BEWLEYS; ABRAKEBABRA
h: !BOOTS; LLOYDS PHARMACY; HICKEYS PHARMACY; !VHI; LAYA HEALTHCARE; IRISH LIFE HEALTH
s: PENNEYS; BROWN THOMAS; ARNOTTS; HARVEY NORMAN; DID ELECTRICAL; WOODIES; EZ LIVING; DEALZ; MR PRICE
tr: AER LINGUS; RYANAIR; IRISH FERRIES; STENA LINE
c: !EIR; EIR MOBILE; !THREE; VIRGIN MEDIA; !GOMO
u: ELECTRIC IRELAND; BORD GAIS; SSE AIRTRICITY; !ENERGIA; UISCE EIREANN; IRISH WATER; FLOGAS; PANDA POWER
gv: MOTOR TAX; REVENUE COMMISSIONERS
en: IMC CINEMAS; OMNIPLEX; !SKY
`,
  FR: `
g: E LECLERC; LECLERC; INTERMARCHE; MONOPRIX; FRANPRIX; !CASINO; CASINO SUPERMARCHE; GEANT CASINO; !PICARD; SYSTEME U; SUPER U; HYPER U; U EXPRESS; !CORA; GRAND FRAIS; BIOCOOP; NATURALIA; LA VIE CLAIRE; CARREFOUR (?:CITY|MARKET|EXPRESS|CONTACT); NICOLAS VINS
d: MCDO; !QUICK; QUICK RESTAURANT; BUFFALO GRILL; COURTEPAILLE; HIPPOPOTAMUS; BRIOCHE DOREE; COLUMBUS CAFE; PAUL (?:BOULANGERIE|SAS); !PAUL; LA MIE CALINE; MARIE BLACHERE; POMME DE PAIN; FLUNCH; LEON DE BRUXELLES; DEL ARTE; BIG FERNAND; O TACOS; FRICHTI
t: SNCF; OUIGO; TGV INOUI; RATP; NAVIGO; !TOTAL; VINCI AUTOROUTES; SANEF; APRR; AREA AUTOROUTE; ESCOTA; ASF AUTOROUTE; G7 TAXI; !G7; TRANSDEV; KEOLIS; MARCEL CAB; !LE CAB; INDIGO PARK; SAEMES; EFFIA
h: DOCTOLIB; MULTIPHARMA; !KRYS; ALAIN AFFLELOU; OPTIC 2000; L APPART FITNESS; FITNESS PARK; NEONESS
s: FNAC; DARTY; LEROY MERLIN; CASTORAMA; !BOULANGER; KIABI; CDISCOUNT; VINTED; GALERIES LAFAYETTE; !PRINTEMPS; PRINTEMPS HAUSSMANN; CELIO; !ACTION; LA REDOUTE; BRICO DEPOT; BRICORAMA; MR BRICOLAGE; !GIFI; !LA HALLE; !JULES; !CULTURA; BOULANGER COM; MAISONS DU MONDE; BUT (?:SAS|COM); CONFORAMA; GO SPORT; INTERSPORT; JOUE CLUB; KING JOUET; NATURE (?:&|ET) DECOUVERTES; LA GRANDE RECRE; ELECTRO DEPOT; BOULANGER SA
tr: TRANSAVIA; SOFITEL; CLUB MED; PIERRE (?:&|ET) VACANCES; CENTER PARCS; CORSAIR; FRENCH BEE
c: ORANGE (?:SA|FRANCE|MOBILE); !ORANGE; SFR; BOUYGUES TELECOM; BOUYGTEL; FREE (?:MOBILE|TELECOM); FREE SAS; !FREE; SOSH; RED BY SFR
u: EDF; ENGIE; VEOLIA; EAU DE PARIS; SUEZ EAU; TOTALENERGIES ELECTRICITE
en: CANAL ?\\+; CANALPLUS; UGC; PATHE; GAUMONT; MOLOTOV; MK2; CGR CINEMAS; FNAC SPECTACLES
p: YVES ROCHER; NOCIBE; MARIONNAUD; SEPHORA; JEAN LOUIS DAVID; FRANCK PROVOST
gv: DGFIP; IMPOTS GOUV; !ANTS; AMENDES GOUV; TRESOR PUBLIC; URSSAF
e: OPENCLASSROOMS
`,
  DE: `
g: REWE; EDEKA; ALDI (?:NORD|SUED|SUD); KAUFLAND; PENNY (?:MARKT)?; !NORMA; !GLOBUS; TEGUT; DENNS BIOMARKT; ALNATURA; BIO COMPANY; MARKTKAUF; NETTO MARKEN DISCOUNT; !E CENTER; KNUSPR
d: BACKWERK; VAPIANO; NORDSEE; KAMPS; BACKFACTORY; DITSCH; L OSTERIA; BLOCK HOUSE; HANS IM GLUCK; HANS IM GLUECK; DEAN (?:&|AND) DAVID; JIM BLOCK; BACK FACTORY; WIENERWALD
t: DB (?:VERTRIEB|BAHN|FERNVERKEHR|REGIO|NAVIGATOR); DEUTSCHE BAHN; BAHN DE; !BVG; !MVG; !HVV; !RMV; !KVB; !VRR; !VVS; !ARAL; ARAL STATION; JET (?:TANKSTELLE|DANKT); STAR TANKSTELLE; !AVIA; HEM TANKSTELLE; SHARE NOW; MILES MOBILITY; TIER MOBILITY; DEUTSCHLANDTICKET; !ADAC
h: DOCMORRIS; SHOP APOTHEKE; CLEVER FIT; FITX; URBAN SPORTS CLUB; FIELMANN; APOLLO OPTIK; MEDPEX
p: DM (?:DROGERIE|MARKT); MULLER DROGERIE; MUELLER DROGERIE; !MULLER; !MUELLER; BUDNI
s: MEDIA ?MARKT; !SATURN; SATURN ELECTRO; OTTO (?:GMBH|DE|VERSAND); !OBI; OBI BAUMARKT; HORNBACH; !BAUHAUS; TOOM BAUMARKT; HAGEBAU; !GALERIA; GALERIA KAUFHOF; KARSTADT; DEICHMANN; PEEK (?:&|AND) CLOPPENBURG; !ACTION; !TEDI; KIK TEXTIL; !KIK; !WOOLWORTH; THALIA; HUGENDUBEL; CONRAD ELECTRONIC; CYBERPORT; NOTEBOOKSBILLIGER; TCHIBO; DEPOT GMBH; JYSK; !POCO; XXXLUTZ; ROLLER GMBH; SPORTSCHECK; ABOUT YOU; EXPERT TECHNOMARKT
tr: EUROWINGS; !CONDOR; CONDOR FLUGDIENST; !TUI; HOLIDAYCHECK; CHECK24 REISEN
c: O2 (?:GERMANY|DE|TELEFONICA); !O2; 1 ?& ?1 (?:TELECOM|INTERNET|VERSATEL); 1UND1; CONGSTAR; ALDI TALK; FREENET; WINSIM; SIMYO; TELEFONICA GERMANY; VODAFONE KABEL; PYUR
u: STADTWERKE; E ON (?:ENERGIE|SE|VERTRIEB|ENERGY); EON ENERGIE; VATTENFALL; ENBW; RWE; !EWE; YELLO; LICHTBLICK; NATURSTROM; TIBBER; GASAG; MAINOVA; !SWM
gv: RUNDFUNK; ARD ZDF; BEITRAGSSERVICE; FINANZAMT; BUERGERAMT; BURGERAMT; BUNDESKASSE; STADTKASSE
en: CINEMAXX; CINESTAR; UCI KINOWELT; SKY DEUTSCHLAND; RTL ?\\+; JOYN; EVENTIM
i: SCALABLE; FLATEX; SMARTBROKER; JUSTTRADE
`,
  ES: `
g: MERCADONA; !DIA; DIA %; SUPERMERCADOS DIA; EROSKI; ALCAMPO; !CONSUM; HIPERCOR; SUPERCOR; BONAREA; BON PREU; AHORRAMAS; CONDIS; CAPRABO; GADIS; FROIZ; COVIRAN; BM SUPERMERCADOS; LA SIRENA; EL CORTE INGLES SUPERMERCADO; SUPERSOL; MAS Y MAS
d: TELEPIZZA; 100 MONTADITOS; RODILLA; VIPS; GINOS; FOSTERS HOLLYWOOD; THE GOOD BURGER; !TGB; GOIKO; LIZARRAN; LA TAGLIATELLA; !UDON; FAST GOOD; PANS (?:&|AND) COMPANY
t: RENFE; METRO (?:DE )?MADRID; METRO DE BARCELONA; !TMB; !EMT; PETRONOR; BALLENOIL; PLENOIL; !ALSA; !AUTOPISTAS; !VIA T; BICIMAD; !BICING; !FGC
h: SANITAS; ADESLAS; ALTAFIT; VIVAGYM; DREAMFIT; GENERAL OPTICA; MULTIOPTICAS; FARMACIA
s: EL CORTE INGLES; !MANGO; MANGO COM; BRICOMART; BRICO DEPOT; !SPRINGFIELD; CORTEFIEL; LEFTIES; PCCOMPONENTES; WORTEN; MIRAVIA; TIGER STORES; CASA DEL LIBRO; !SFERA; TENDAM; LEROY MERLIN; FNAC
p: PRIMOR; DRUNI; KIKO
tr: AIR EUROPA; VOLOTEA; BINTER; MELIA; NH HOTEL; BARCELO; PARADORES; !RIU; RIU HOTELS; LEVEL AIRLINE
c: MOVISTAR; !ORANGE; YOIGO; MASMOVIL; MASORANGE; !DIGI; DIGI MOBIL; PEPEPHONE; !LOWI; JAZZTEL; FINETWORK
u: IBERDROLA; ENDESA; NATURGY; HOLALUZ; CANAL DE ISABEL II; AGBAR; AGUAS DE BARCELONA; AQUALIA; REPSOL LUZ
gv: AGENCIA TRIBUTARIA; AEAT; !DGT; DGT MULTAS; SEGURIDAD SOCIAL; AYUNTAMIENTO
en: CINESA; YELMO; KINEPOLIS; MOVISTAR ?\\+; MOVISTAR PLUS
i: MYINVESTOR; INDEXA CAPITAL
`,
  IT: `
g: ESSELUNGA; !COOP; COOP ITALIA; IPERCOOP; CONAD; !PAM; PAM PANORAMA; EUROSPIN; MD DISCOUNT; MD SPA; !IPER; !BENNET; TIGROS; DESPAR; !SIGMA; !CRAI; !UNES; TODIS; INS MERCATO; NATURASI; !PENNY; CARREFOUR MARKET; !FAMILA; LIDL ITALIA; ALDI ITALIA; IPERAL; PRIX QUALITY
d: AUTOGRILL; OLD WILD WEST; SPONTINI; !CAMST; CHEF EXPRESS; ROADHOUSE RESTAURANT; RISTORANTE; !GROM; PIADINERIA
t: TRENITALIA; ITALO (?:TRENO|SPA|NTV); !ITALO; ATM MILANO; ATAC ROMA; !ATAC; !ENI; ENI STATION; ENI SPA; IP (?:STATION|STAZIONE); ITALIANA PETROLI; TAMOIL; AUTOSTRADE; TELEPASS; ITABUS; GTT TORINO; !TPER; MYCICERO; FRECCIAROSSA
h: FARMACIA; FARMACIE COMUNALI; GRANDVISION; SALMOIRAGHI
s: UNIEURO; MEDIAWORLD; EURONICS; !OVS; RINASCENTE; BRICOMAN; BRICO IO; CALZEDONIA; INTIMISSIMI; TEZENIS; YAMAMAY; BENETTON; UNITED COLORS; FELTRINELLI; MONDADORI; COIN CASA; COIN SPA; LEROY MERLIN; MEDIA WORLD; !TRONY; EXPERT ITALIA; ZARA HOME; GIOCHI PREZIOSI; PIAZZA ITALIA; TERRANOVA
p: TIGOTA; ACQUA (?:&|E) SAPONE; KIKO; PINALLI; DOUGLAS ITALIA
tr: ITA AIRWAYS; ALITALIA; NEOS AIR
c: !TIM; TIM SPA; TELECOM ITALIA; WINDTRE; WIND TRE; !ILIAD; ILIAD ITALIA; FASTWEB; HO MOBILE; KENA MOBILE; VERY MOBILE; POSTEMOBILE; POSTE MOBILE
u: ENEL; HERA COMM; !HERA; !A2A; !IREN; IREN MERCATO; !ACEA; !EDISON; EDISON ENERGIA; SORGENIA; ENI PLENITUDE; PLENITUDE; SERVIZIO ELETTRICO
gv: AGENZIA (?:DELLE )?ENTRATE; PAGOPA; AGENZIA ENTRATE
en: THE SPACE CINEMA; UCI CINEMAS; SKY ITALIA; TIMVISION; NOW TV ITALIA; INFINITY TV
`,
  NL: `
g: ALBERT HEIJN; AH TO GO; !AH; !JUMBO; JUMBO SUPERMARKT; !PLUS; PLUS SUPERMARKT; DIRK (?:VAN DEN BROEK|VD BROEK); !DIRK; DEKAMARKT; VOMAR; HOOGVLIET; !COOP; COOP SUPERMARKT; !PICNIC; EKOPLAZA; !CRISP APP; GALL (?:&|AND) GALL; JAN LINDERS; POIESZ; BONI SUPERMARKT; NETTO NL
d: FEBO; NEW YORK PIZZA; SMULLERS; !LA PLACE; KWALITARIA; BURGERMEESTER; BAGELS (?:&|AND) BEANS
t: NS (?:GROEP|REIZIGERS|INTERNATIONAL|NL); NS \\d{3,}; GVB; RET ROTTERDAM; !RET; !HTM; OV CHIPKAART; TRANSLINK SYSTEMS; CONNEXXION; QBUZZ; TINQ; !TANGO; YELLOWBRICK; ARRIVA; SWAPFIETS; OV FIETS
h: SPORTCITY; !PEARLE; HANS ANDERS; APOTHEEK
p: KRUIDVAT; !ETOS; ETOS BV; TREKPLEISTER; DA DROGIST
s: HEMA; BOL COM; !BOL; COOLBLUE; !ACTION; ACTION NEDERLAND; GAMMA BOUWMARKT; !GAMMA; !PRAXIS; PRAXIS BOUWMARKT; KARWEI; BLOKKER; WIBRA; ZEEMAN; BIJENKORF; WEHKAMP; INTERTOYS; !XENOS; !BRUNA; MEDIAMARKT; LEEN BAKKER; BEDDENREUS; KWANTUM; PRIMERA; AMAZON NL
tr: TRANSAVIA; CORENDON; SUNWEB
c: KPN; ZIGGO; ODIDO; TELE2; !SIMPEL; YOUFONE; LEBARA; HOLLANDSNIEUWE; DELTA FIBER
u: ENECO; ESSENT; GREENCHOICE; BUDGET ENERGIE; VANDEBRON; WATERNET; VITENS; EVIDES; BRABANT WATER; !PWN; OXXIO; ENERGIEDIRECT; FRANK ENERGIE
gv: BELASTINGDIENST; CJIB; GEMEENTE; RDW; WATERSCHAP
en: PATHE; !VUE; KINEPOLIS; VIDEOLAND; NLZIET
i: !BUX; MEESMAN; BRAND NEW DAY; BITVAVO
`,
  BE: `
g: DELHAIZE; COLRUYT; !OKAY; OKAY COMPACT; BIO PLANET; INTERMARCHE; !CORA; !MATCH; SMATCH; PROXY DELHAIZE; AD DELHAIZE; !JUMBO; ALBERT HEIJN
d: !QUICK; !PANOS; EXKI; LE PAIN QUOTIDIEN; TAKEAWAY COM
t: SNCB; NMBS; STIB; MIVB; DE LIJN; !TEC; LUKOIL; DATS 24; !TOTAL
p: KRUIDVAT; !ETOS
s: HEMA; !ACTION; !BRICO; BRICO PLANIT; !GAMMA; MEDIAMARKT; KREFEL; VANDEN BORRE; FNAC; COOLBLUE; BOL COM; !ZEEMAN; TORFS; STANDAARD BOEKHANDEL
c: PROXIMUS; !ORANGE; ORANGE BELGIUM; TELENET; !SCARLET; BASE MOBILE
u: ENGIE ELECTRABEL; ELECTRABEL; !LUMINUS; ENECO; VIVAQUA; FLUVIUS; DE WATERGROEP; !ENGIE
tr: BRUSSELS AIRLINES; TUI FLY
en: KINEPOLIS; UGC
gv: FOD FINANCIEN; SPF FINANCES; MYMINFIN
`,
  CH: `
g: MIGROS; !COOP; COOP PRONTO; DENNER; ALDI SUISSE; !VOLG; MIGROLINO; AVEC SHOP; !LANDI; GLOBUS DELICATESSA
t: SBB (?:CFF|MOBILE|TICKET); SBB CFF FFS; !SBB; ZVV; !BLS; POSTAUTO; POSTBUS; AGROLA; TAMOIL; !AVIA; SOCAR; MOBILITY CARSHARING
h: AMAVITA; !SUN STORE; SUNSTORE; TOPPHARM
s: !MANOR; GALAXUS; DIGITEC; INTERDISCOUNT; !JUMBO; JUMBO MARKT; !BAUHAUS; !OBI; !FUST; !MICASA; !PFISTER; !JELMOLI; ORELL FUSSLI; !BRACK
c: SWISSCOM; SALT (?:MOBILE|COMMUNICATIONS); !SALT; SUNRISE (?:UPC|COMMUNICATIONS|GMBH|MOBILE); !WINGO; !YALLO
u: !EWZ; !BKW; !IWB; SIG GENEVE; ROMANDE ENERGIE; !AXPO; !CKW
tr: SWISS (?:INTERNATIONAL|INTL)? AIR ?LINES; SWISSAIR; EDELWEISS AIR
en: PATHE; KITAG; BLUE ENTERTAINMENT
gv: STEUERVERWALTUNG; SERAFE
`,
  PT: `
g: !CONTINENTE; PINGO DOCE; MINIPRECO; INTERMARCHE; MERCADONA; !AUCHAN; FROIZ
t: CP COMBOIOS; COMBOIOS DE PORTUGAL; METRO (?:LISBOA|DO PORTO); METROPOLITANO DE LISBOA; !CARRIS; VIA VERDE; !PRIO; PRIO ENERGY; GALP; REPSOL
h: !WELLS; WELLS PT
s: WORTEN; FNAC; RADIO POPULAR; EL CORTE INGLES; SPORT ZONE; LEROY MERLIN; BERTRAND LIVREIROS; !SONAE
c: !MEO; !NOS; NOS COMUNICACOES; !NOWO; DIGI PORTUGAL
u: !EDP; EDP COMERCIAL; !EPAL; GALP GAS; ENDESA
tr: TAP (?:AIR|PORTUGAL)
gv: PORTAL DAS FINANCAS; AUTORIDADE TRIBUTARIA
`,
  TR: `
g: !BIM; BIM BIRLESIK; A101; SOK MARKET; SOK MARKETLER; CARREFOURSA; MACROCENTER; ISTEGELSIN; HAKMAR; FILE MARKET; !METRO; MIGROS JET
d: GETIR YEMEK; TRENDYOL YEMEK; SIMIT SARAYI; KOFTECI YUSUF; !MADO; KAHVE DUNYASI; BURGER KING TURKIYE; TAVUK DUNYASI; USTA DONERCI
t: OPET; PETROL OFISI; !PO; AYTEMIZ; ISTANBULKART; BITAKSI; !MARTI; MARTI SCOOTER; !HGS; TCDD; TCDD TASIMACILIK; OBILET; BELBIM
s: TRENDYOL; HEPSIBURADA; !N11; LC WAIKIKI; !DEFACTO; !KOTON; !MAVI; MAVI GIYIM; TEKNOSA; VATAN BILGISAYAR; KOCTAS; !BOYNER; ENGLISH HOME; MADAME COCO; !FLO; CICEKSEPETI; AMAZON TR
p: !GRATIS; GRATIS MAGAZA; EVEN (?:&|AND) GOOD
tr: !THY; TURK HAVA YOLLARI; !PEGASUS; SUNEXPRESS; !AJET
c: TURKCELL; TURK TELEKOM; TTNET; SUPERONLINE; VODAFONE TR
u: ENERJISA; IGDAS; !ISKI; CK ENERJI; CK BOGAZICI; !ASKI; BASKENTGAZ
gv: GELIR IDARESI; !GIB; E DEVLET
en: CINEMAXIMUM; BLUTV; EXXEN; BIUBIU
i: MIDAS MENKUL
`,
  BR: `
g: PAO DE ACUCAR; !ASSAI; ATACADAO; !EXTRA; EXTRA HIPER; !DIA; ZAFFARI; ST MARCHE; !SONDA; SONDA SUPERMERCADO; !GUANABARA; SAVEGNAGO; CONDOR SUPER; SUPERMERCADO BH; MAMBO SUPERMERCADO; OXXO
d: HABIBS; !BOBS; BOBS LANCHES; GIRAFFAS; !SPOLETO; CHINA IN BOX; COCO BAMBU; !MADERO; !RAGAZZO; AMERICAN BURGER
t: 99 (?:TAXI|APP|POP|TECNOLOGIA); IPIRANGA; POSTO IPIRANGA; BR MANIA; !RAIZEN; SEM PARAR; CONECTCAR; VELOE; METRO SAO PAULO; METRO SP; CPTM; BILHETE UNICO; ESTAPAR; ZONA AZUL
h: DROGASIL; DROGA RAIA; !RAIA; PAGUE MENOS; DROGARIA SAO PAULO; PANVEL; DROGARIAS PACHECO
s: MERCADO ?LIVRE; MAGAZINE LUIZA; MAGALU; AMERICANAS; !RENNER; RIACHUELO; CASAS BAHIA; NETSHOES; !CENTAURO; TOK (?:&|AND) STOK; CAMICADO; KALUNGA; FAST SHOP; PONTO FRIO; SHOPEE BR; LEROY MERLIN
p: BOTICARIO; O BOTICARIO; !NATURA; NATURA COSMETICOS; !EUDORA; QUEM DISSE BERENICE
tr: GOL LINHAS; VOEGOL; !GOL; AZUL LINHAS; VOEAZUL; !AZUL; 123MILHAS; !HURB
c: !VIVO; TELEFONICA BRASIL; !CLARO; !TIM; TIM CELULAR; !OI; OI FIBRA; OI MOVEL
u: SABESP; CEMIG; COPEL; LIGHT (?:SA|SERVICOS); CPFL; ELETROPAULO; COMGAS; SANEPAR; CEDAE; NEOENERGIA; COELBA; CELPE; EQUATORIAL ENERGIA; ENEL
gv: DETRAN; RECEITA FEDERAL; DARF; IPVA
en: GLOBOPLAY; CINEMARK; CINEPOLIS; INGRESSO COM; SYMPLA; TELECINE
i: XP INVESTIMENTOS; RICO INVESTIMENTOS; NUINVEST; CLEAR CORRETORA
`,
  MX: `
g: OXXO; SORIANA; CHEDRAUI; LA COMER; BODEGA AURRERA; SUPERAMA; !SAMS; CITY MARKET; !FRESKO; !HEB; CASA LEY; CIRCULO K; WALMART; SMART (?:&|AND) FINAL
d: VIPS; !TOKS; ITALIANNIS; EL PORTON; SANBORNS CAFE; POTZOLLCALLI; FINCA SANTA VERACRUZ; CAFEBRERIA; LA ESQUINA DE LOS CAFES; EL FAROLITO
t: PEMEX; OXXO GAS; !G500; HIDROSINA; !ORSAN; !IAVE; TELEVIA; PASE URBANO; !ADO; ADO AUTOBUSES; !ETN; METRO CDMX; !METROBUS; ECOBICI; CAPUFE
h: FARMACIAS GUADALAJARA; FARMACIAS DEL AHORRO; FARMACIAS SIMILARES; FARMACIAS SAN PABLO; !BENAVIDES; !SPORT CITY
s: !LIVERPOOL; LIVERPOOL MX; COPPEL; MERCADO ?LIBRE; PALACIO DE HIERRO; !SUBURBIA; !ELEKTRA; !SEARS; SANBORNS; OFFICE DEPOT; CLAROSHOP
c: TELCEL; TELMEX; !CLARO; AT & T MEXICO; MOVISTAR; IZZI; TOTALPLAY; MEGACABLE; !BAIT
u: !CFE; CFE SUMINISTRADOR; NATURGY
gv: !SAT; SAT PAGO; SAT MX; SERVICIO DE ADMINISTRACION TRIBUTARIA
en: CINEPOLIS; CINEMEX
i: !GBM; CETES ?DIRECTO; !HAPI
`,
  CO: `
g: !EXITO; ALMACENES EXITO; CARULLA; !OLIMPICA; !D1; TIENDAS D1; !ARA; TIENDAS ARA; JUSTO (?:&|Y) BUENO; !JUMBO; SURTIMAX; !ISIMO; !METRO
d: CREPES (?:&|AND) WAFFLES; !EL CORRAL; !FRISBY; JUAN VALDEZ; !OMA; !TOSTAO; DOMICILIOS COM; FRESCOS Y CALIENTES
t: TERPEL; !PRIMAX; !BIOMAX; TRANSMILENIO; METRO DE MEDELLIN; !PEAJE
h: CRUZ VERDE; FARMATODO; LOCATEL
s: FALABELLA; ALKOSTO; KTRONIX; HOMECENTER; !PANAMERICANA; ARTURO CALLE; MERCADO ?LIBRE; LINIO
tr: !WINGO; FLY WINGO
c: !CLARO; MOVISTAR; !TIGO; !WOM; !ETB
u: !EPM; CODENSA; ENEL COLOMBIA; !VANTI; ACUEDUCTO; GAS NATURAL
gv: !DIAN; !SIMIT
en: CINE COLOMBIA; PROCINAL; CINEMARK
`,
  AR: `
g: !COTO; !DIA; !JUMBO; !DISCO; !VEA; !CHANGOMAS; !LA ANONIMA; VITAL MAYORISTA
d: !MOSTAZA; HAVANNA; CAFE MARTINEZ; !FREDDO; !GRIDO
t: YPF; !AXION; !SUBE; CARGA SUBE; AUTOPISTAS DEL SOL; !AUSA
h: FARMACITY; !DR AHORRO
s: MERCADO ?LIBRE; FRAVEGA; GARBARINO; MUSIMUNDO; FALABELLA; !EASY; SODIMAC
tr: FLYBONDI; JETSMART
c: !PERSONAL; TELECOM PERSONAL; !CLARO; MOVISTAR; TELECENTRO; FIBERTEL
u: EDENOR; EDESUR; METROGAS; AYSA; NATURGY
gv: !AFIP; !ARCA
en: HOYTS; CINEMARK
i: INVERTIRONLINE; BALANZ
`,
  IN: `
g: BIGBASKET; BIG BASKET; DMART; D MART; AVENUE SUPERMARTS; RELIANCE (?:FRESH|SMART|MART|RETAIL); SMART BAZAAR; BLINKIT; GROFERS; ZEPTO; INSTAMART; SWIGGY INSTAMART; MORE (?:RETAIL|SUPERMARKET); !SPENCERS; NATURES BASKET; STAR BAZAAR; JIOMART; BB DAILY; BBNOW; METRO CASH (?:&|AND) CARRY; LULU HYPER
d: HALDIRAMS; CAFE COFFEE DAY; !CCD; CHAAYOS; BARBEQUE NATION; THIRD WAVE COFFEE; BLUE TOKAI; BEHROUZ; FAASOS; REBEL FOODS; EATSURE; BIKANERVALA; SAGAR RATNA; WOW MOMO
t: !OLA; !RAPIDO; RAPIDO BIKE; IOCL; INDIAN OIL; HPCL; HP PETROL; HINDUSTAN PETROLEUM; BPCL; BHARAT PETROLEUM; NAYARA; FASTAG; NHAI; DELHI METRO; DMRC; BMRCL; NAMMA METRO; MUMBAI METRO; REDBUS; ABHIBUS; !YULU; BLUSMART; PARK ?PLUS
h: APOLLO PHARMACY; !APOLLO; APOLLO HOSPITALS; PHARMEASY; 1MG; TATA 1MG; NETMEDS; !MEDPLUS; PRACTO; !FORTIS; MAX HEALTHCARE; MANIPAL HOSPITAL; CULT FIT; CULTFIT; CURE FIT; CUREFIT; HEALTHIFYME; LENSKART
s: FLIPKART; MYNTRA; AJIO; MEESHO; CROMA; RELIANCE (?:DIGITAL|TRENDS); VIJAY SALES; TATA CLIQ; SHOPPERS STOP; !LIFESTYLE; PANTALOONS; !WESTSIDE; MAX FASHION; FIRSTCRY; PEPPERFRY; URBAN LADDER; TANISHQ
p: NYKAA; PURPLLE; MAMAEARTH
tr: IRCTC; YATRA; !INDIGO; 6E INDIGO; INTERGLOBE AVIATION; AKASA AIR; VISTARA; IXIGO
c: JIO; RELIANCE JIO; VI (?:POSTPAID|PREPAID|RECHARGE); VODAFONE IDEA; BSNL; ACT FIBERNET; HATHWAY
u: BESCOM; TATA POWER; ADANI ELECTRICITY; MSEDCL; MAHADISCOM; BSES; TORRENT POWER; MAHANAGAR GAS; !MGL; INDRAPRASTHA GAS; !IGL; BWSSB; DELHI JAL BOARD; TANGEDCO; TNEB; CESC; KSEB
gv: INCOME ?TAX; PASSPORT SEVA; PARIVAHAN
en: BOOKMYSHOW; HOTSTAR; JIOHOTSTAR; !PVR; !INOX; SONYLIV; ZEE5; JIOCINEMA; GAANA; TATA PLAY
e: VEDANTU; PHYSICS ?WALLAH; UPGRAD; SIMPLILEARN
i: KUVERA; PAYTM MONEY
hs: URBAN COMPANY; URBANCLAP
`,
  PK: `
g: !IMTIAZ; IMTIAZ SUPER; !AL FATAH; !CHASE UP; !NAHEED; NAHEED SUPERMARKET; HASH MART; !GREEN VALLEY
d: CHEEZIOUS; !OPTP; SAVOUR FOODS; BUNDU KHAN; KABABJEES; !HOWDY; JOHNNY (?:&|AND) JUGNU
t: !PSO; PAKISTAN STATE OIL; TOTAL PARCO; ATTOCK PETROLEUM; BYKEA; M ?TAG; HASCOL
h: DAWAAI; SEHAT KAHANI; SHAUKAT KHANUM; !SERVAID; !D WATSON; OLADOC; !MARHAM
s: DARAZ; KHAADI; GUL AHMED; !SAPPHIRE; !OUTFITTERS; !LIMELIGHT; ALKARAM; BONANZA SATRANGI; SANA SAFINAZ; !J DOT; JUNAID JAMSHED
tr: !PIA; PAKISTAN INTERNATIONAL AIRLINES; AIRBLUE; SERENE AIR; AIRSIAL; FLY JINNAH
c: !JAZZ; JAZZ CASH; TELENOR; ZONG; UFONE; PTCL; NAYATEL; STORMFIBER
u: !K ?ELECTRIC; !LESCO; !IESCO; !MEPCO; !FESCO; !PESCO; !GEPCO; !HESCO; SSGC; SUI SOUTHERN; SNGPL; SUI NORTHERN; !KWSC; !WASA
gv: !FBR; NADRA; EXCISE (?:&|AND) TAXATION
en: CINEPAX; NUEPLEX; TAPMAD
`,
  ID: `
g: INDOMARET; ALFAMART; ALFAMIDI; SUPERINDO; HYPERMART; LOTTE MART; !TRANSMART; !GIANT; RANCH MARKET; GRAND LUCKY; SAYURBOX; HERO SUPERMARKET; !FOODHALL
d: KOPI KENANGAN; JANJI JIWA; FORE COFFEE; !SOLARIA; HOKBEN; HOKA HOKA BENTO; !RICHEESE; MIXUE; J ?CO DONUTS; BAKMI GM; ES TEH INDONESIA; KOPI KULO; PADANG SEDERHANA
t: BP AKR; !KAI; KERETA API; !KRL; COMMUTER LINE; KAI COMMUTER; TRANSJAKARTA; MRT JAKARTA; JASA MARGA; !BLUEBIRD; !BLUE BIRD; !MAXIM
h: KIMIA FARMA; APOTEK K ?24; !CENTURY; HALODOC; ALODOKTER; SILOAM; MITRA KELUARGA; BPJS
s: TOKOPEDIA; SHOPEE; LAZADA; BUKALAPAK; BLIBLI; !INFORMA; !MATAHARI; ERAFONE; ZALORA
p: SOCIOLLA
tr: CITILINK; BATIK AIR; TIKET COM; PEGIPEGI
c: TELKOMSEL; INDOSAT; !IM3; XL AXIATA; XL (?:PREPAID|POSTPAID); SMARTFREN; INDIHOME; BIZNET; !FIRST MEDIA; !BY U
u: !PLN; PLN PREPAID; TOKEN PLN; !PDAM; PDAM JAYA; !PGN
en: CGV; CINEMA XXI; !XXI; VIDIO
i: !BIBIT; !AJAIB; PLUANG; BAREKSA
e: RUANG ?GURU; !ZENIUS
`,
  MY: `
g: AEON BIG; AEON MAXVALU; LOTUSS; LOTUS S; !TESCO; !GIANT; !MYDIN; JAYA GROCER; VILLAGE GROCER; !MERCATO; 99 SPEEDMART; KK (?:SUPER )?MART; !ECONSAVE; !NSK TRADE
d: OLDTOWN WHITE COFFEE; !OLDTOWN; SECRET RECIPE; MARRYBROWN; TEALIVE; ZUS COFFEE; PAPPARICH; SUSHI KING; KENNY ROGERS; !RICHIAMO
t: PETRON; BHPETROL; TOUCH N GO TOLL; PLUS MALAYSIA; PLUSMILES; RAPID ?KL; MRT CORP; !KTM; KTM BERHAD; KLIA EKSPRES
h: CARING PHARMACY; BIG PHARMACY; ALPRO PHARMACY; !KPJ; SUNWAY MEDICAL; PANTAI HOSPITAL; !GUARDIAN
s: MR ?DIY; ECO ?SHOP; !PARKSON; SENHENG; HARVEY NORMAN; !PADINI; !COURTS
tr: !FIREFLY; FIREFLY AIRLINES; BATIK AIR
c: MAXIS; CELCOM; CELCOMDIGI; !DIGI; U MOBILE; !UNIFI; TIME DOTCOM; !HOTLINK; TUNETALK; !YES 5G
u: !TNB; TENAGA NASIONAL; AIR SELANGOR; SYABAS; INDAH WATER; !SESB; GAS MALAYSIA
gv: LHDN; !HASIL; !JPJ
en: !GSC; GOLDEN SCREEN; TGV CINEMAS; !ASTRO; ASTRO MALAYSIA
i: RAKUTEN TRADE
`,
  SG: `
g: NTUC FAIRPRICE; FAIRPRICE; COLD STORAGE; SHENG SIONG; !GIANT; PRIME SUPERMARKET; REDMART; DON DON DONKI; !CHEERS
d: KOPITIAM; YA KUN; TOAST BOX; BREADTALK; OLD CHANG KEE; SWENSENS; !KOI; !LIHO; SUBWAY SG; GONG CHA; PASTAMANIA
t: BUS ?/? ?MRT; SIMPLYGO; TRANSITLINK; EZ ?LINK; COMFORTDELGRO; CDG ZIG; COMFORT TAXI; !TADA; !RYDE; SPC SERVICE; !SPC; SINOPEC
h: UNITY PHARMACY; RAFFLES MEDICAL; !PARKWAY; GUARDIAN HEALTH; !GUARDIAN
s: QOO10; !COURTS; BEST DENKI; !CHALLENGER; POPULAR BOOK; TAKASHIMAYA; ISETAN; !TANGS; !MUSTAFA; MUSTAFA CENTRE; HARVEY NORMAN
tr: !CHANGI; !SCOOT
c: SINGTEL; STARHUB; !M1; M1 LIMITED; !SIMBA; CIRCLES LIFE; MYREPUBLIC
u: SP SERVICES; !SP GROUP; !CITY ENERGY; !GENECO
gv: IRAS; !ICA; !HDB; !LTA
en: GOLDEN VILLAGE; !GV; SHAW THEATRES; CATHAY CINEPLEX
i: SYFE; ENDOWUS
`,
  PH: `
g: SM (?:SUPERMARKET|HYPERMARKET|SAVEMORE); !SAVEMORE; PUREGOLD; ROBINSONS SUPERMARKET; WALTERMART; !LANDERS; !S ?& ?R; ALL DAY SUPERMARKET; RUSTANS SUPERMARKET; ALFAMART
d: CHOWKING; !GREENWICH; MANG INASAL; !RED RIBBON; !GOLDILOCKS; SHAKEYS; YELLOW CAB PIZZA
t: PETRON; !SEAOIL; !PHOENIX; !ANGKAS; !JOYRIDE; BEEP CARD; AUTOSWEEP; !EASYTRIP; !LRT
h: MERCURY DRUG; SOUTHSTAR DRUG; THE GENERICS PHARMACY; ROSE PHARMACY
s: SM STORE; SM DEPT; !RUSTANS; ABENSON; !ANSONS; WILCON; NATIONAL BOOK ?STORE
tr: !PAL; CEBU PAC
c: !GLOBE; GLOBE TELECOM; !SMART; SMART (?:COMM|PREPAID); PLDT; !CONVERGE; SKY CABLE; !DITO
u: MERALCO; MANILA WATER; MAYNILAD; !VECO
gv: !BIR; !LTO; !SSS; PHILHEALTH; PAG ?IBIG
en: SM CINEMA
`,
  AU: `
g: !WOOLWORTHS; WOOLWORTHS METRO; !COLES; COLES SUPERMARKETS; IGA; FOODWORKS; HARRIS FARM; !DRAKES; !BWS; DAN MURPHYS; LIQUORLAND; FIRST CHOICE LIQUOR
d: GUZMAN Y GOMEZ; !GYG; HUNGRY JACKS; BOOST JUICE; !OPORTO; RED ROOSTER; GRILLD; ZAMBRERO; SUMO SALAD; !SCHNITZ; MUFFIN BREAK; GLORIA JEANS
t: MYKI; !OPAL; !GO CARD; TRANSLINK QLD; ADELAIDE METRO; SMARTRIDER; TRANSPERTH; AMPOL; UNITED PETROLEUM; COLES EXPRESS; LINKT; EASTLINK; 13CABS; SECURE PARKING; WILSON PARKING; SUPERCHEAP AUTO
h: CHEMIST WAREHOUSE; PRICELINE PHARMACY; TERRY ?WHITE; !AMCAL; BLOOMS THE CHEMIST; MEDIBANK; !NIB; !HCF; !JETTS; !OPSM
s: JB HI ?FI; BUNNINGS; !TARGET; BIG W; !MYER; !DAVID JONES; HARVEY NORMAN; THE GOOD GUYS; OFFICEWORKS; REBEL SPORT; !BCF; !ANACONDA; !SPOTLIGHT; COTTON ON; CATCH COM; THE ICONIC; EB GAMES; !ADAIRS
tr: !REX; WEBJET; WOTIF
c: TELSTRA; OPTUS; !TPG; AUSSIE BROADBAND; IINET; !BELONG; AMAYSIM; !DODO
u: !AGL; ORIGIN ENERGY; ENERGY ?AUSTRALIA; RED ENERGY; ALINTA; SYDNEY WATER; YARRA VALLEY WATER; SA WATER; ACTEWAGL; SIMPLY ENERGY; POWERSHOP
gv: !ATO; AUSTRALIAN TAXATION; SERVICE NSW; VICROADS
en: STAN COM AU; !STAN; FOXTEL; !KAYO; !BINGE; HOYTS; EVENT CINEMAS; VILLAGE CINEMAS; READING CINEMAS
i: !RAIZ; !SPACESHIP; !PEARLER; !STAKE
`,
  NZ: `
g: !COUNTDOWN; !WOOLWORTHS; PAK N SAVE; PAKNSAVE; !NEW WORLD; !FOUR SQUARE; FRESHCHOICE; !SUPERVALUE; LIQUORLAND; SUPER LIQUOR
d: HELL PIZZA; BURGER ?FUEL; DELIVEREASY
t: Z ENERGY; !MOBIL; !GULL; !WAITOMO; AT HOP; AUCKLAND TRANSPORT; !SNAPPER; !METLINK; WAKA KOTAHI; KIWIRAIL; !INTERCITY
h: UNICHEM; !SOUTHERN CROSS; LES MILLS; CHEMIST WAREHOUSE
s: !THE WAREHOUSE; WAREHOUSE STATIONERY; NOEL LEEMING; BRISCOES; !FARMERS; MITRE 10; BUNNINGS; REBEL SPORT; !SPOTLIGHT; !TRADE ?ME; !KATHMANDU; TORPEDO7
tr: AIR NZ
c: !SPARK; ONE NZ; ONE NEW ZEALAND; 2DEGREES; !SKINNY
u: !MERCURY; GENESIS ENERGY; CONTACT ENERGY; MERIDIAN ENERGY; TRUSTPOWER; ELECTRIC KIWI; WATERCARE
gv: !IRD; INLAND REVENUE
en: !SKY; SKY TV; !NEON; EVENT CINEMAS; HOYTS
i: !HATCH; HATCH INVEST
`,
  ZA: `
g: !CHECKERS; PICK N PAY; !PNP; PNP ASAP; WOOLWORTHS FOOD; !USAVE; !BOXER; FOOD LOVERS MARKET; OK FOODS; OK MINIMARK; SIXTY60
d: !MR D; MRD FOOD; !STEERS; !WIMPY; !SPUR; SPUR STEAK; OCEAN BASKET; !DEBONAIRS; ROMANS PIZZA; FISHAWAYS; !KAUAI; VIDA E CAFFE; MUGG (?:&|AND) BEAN; CHICKEN LICKEN; SEATTLE COFFEE
t: GAUTRAIN; !SANRAL; !E ?TOLL; !MYCITI
h: !CLICKS; DIS ?CHEM; MEDIRITE; NETCARE; MEDICLINIC; LIFE HEALTHCARE
s: TAKEALOT; MR PRICE; !WOOLWORTHS; !EDGARS; TRUWORTHS; FOSCHINI; ACKERMANS; !PEP; PEP STORES; CASHBUILD; BUILDERS WAREHOUSE; BUILDERS EXPRESS; INCREDIBLE CONNECTION; HIFI CORP; !GAME; GAME STORES; EXCLUSIVE BOOKS; !CNA; SUPERBALIST
tr: !SAA; !AIRLINK; LIFT AIRLINE
c: VODACOM; MTN; !CELL ?C; TELKOM; !RAIN; AFRIHOST
u: ESKOM; !CITY POWER; CITY OF (?:CAPE TOWN|JOHANNESBURG|TSHWANE|EKURHULENI)
gv: !SARS; SA REVENUE SERVICE
en: DSTV; MULTICHOICE; STER ?KINEKOR; !NU METRO; COMPUTICKET
i: !SATRIX; VALR
`,
  NG: `
g: JUSTRITE; !EBEANO; PRINCE EBEANO; !MARKET SQUARE; !HUBMART
d: CHICKEN REPUBLIC; CHOWDECK; !KILIMANJARO; MR BIGGS; TANTALIZERS; !SWEET SENSATION
t: !RIDA; NNPC; OANDO; CONOIL; ARDOVA; FORTE OIL; MRS OIL
h: MEDPLUS; !HEALTHPLUS
s: JUMIA; KONGA; !SLOT; SLOT SYSTEMS
tr: AIR PEACE; ARIK AIR; IBOM AIR; DANA AIR; UNITED NIGERIA
c: MTN; !GLO; GLOBACOM; 9MOBILE; SPECTRANET
u: IKEDC; IKEJA ELECTRIC; EKEDC; EKO ELECTRIC; AEDC; ABUJA ELECTRIC; !PHED; IBEDC; KEDCO; EEDC
gv: !FIRS; !LIRS
en: DSTV; GOTV; FILMHOUSE
i: !BAMBOO; !CHAKA; !TROVE; RISEVEST
`,
  KE: `
g: NAIVAS; !QUICKMART; CHANDARANA; CLEANSHELF
d: JAVA HOUSE; ARTCAFFE; CHICKEN INN; PIZZA INN; GALITOS
t: LITTLE (?:CAB|RIDE); OLA ENERGY; !KENOL
h: GOODLIFE PHARMACY; !AGA KHAN; NAIROBI HOSPITAL
s: JUMIA; KILIMALL; !HOTPOINT
tr: JAMBOJET; SAFARILINK
c: SAFARICOM; TELKOM KENYA; !ZUKU; !FAIBA
u: KPLC; KENYA POWER; NAIROBI WATER
gv: !KRA; KENYA REVENUE; E ?CITIZEN; NTSA
en: DSTV; GOTV; CENTURY CINEMAX
`,
  EG: `
g: SEOUDI; METRO MARKETS; KHEIR ZAMAN; HYPERONE; BREADFAST; !RABBIT; OSCAR GRAND STORES
d: ELMENUS; !KOSHARY; BUFFALO BURGER; !CILANTRO; COOK DOOR; !MOMEN
t: SWVL; MISR PETROLEUM; !WATANIYA; EMARAT MISR
h: EL ?EZABY; SEIF PHARMACY; !19011; VEZEETA
s: !B ?TECH; JUMIA; !NOON; RAYA SHOP; !2B
tr: AIR CAIRO; NILE AIR
c: WE TELECOM; TELECOM EGYPT; !ORANGE; ORANGE EGYPT; ETISALAT
`,
  MA: `
g: MARJANE; LABEL VIE; !BIM; !ACIMA; ASWAK ASSALAM
t: AFRIQUIA; !WINXO; ONCF; AL BORAQ; !TRAMWAY
s: ELECTROPLANET; JUMIA; KITEA
tr: !RAM; ROYAL AIR MAROC
c: MAROC TELECOM; !IAM; INWI; !ORANGE; ORANGE MAROC
u: LYDEC; !REDAL; AMENDIS; !ONEE
`,
};

export interface BrandMatch {
  /** The table key the pattern came from (GLOBAL or an ISO country). */
  table: string;
  pattern: string;
  category: CategoryId;
}

interface CompiledBrand extends BrandMatch {
  regex: RegExp;
  gate: string | null;
}

const SEPARATOR = "[\\s./&+,-]*";

function compilePattern(body: string): RegExp {
  const source = body.replace(/ /g, SEPARATOR);
  // A trailing store number is fine (TESCO3345) unless the brand itself ends
  // in a digit, where it would turn A101 into a prefix of A1012.
  const tail = /\d$/.test(body) ? '(?![A-Z0-9])' : '(?![A-Z])';
  return new RegExp(`(?<![A-Z0-9])(?:${source})${tail}`, 'u');
}

let compiled: CompiledBrand[] | null = null;
let index: { byKey: Map<string, CompiledBrand[]>; always: CompiledBrand[] } | null = null;

/**
 * The literal characters every match of `pattern` must start with: two when
 * the pattern opens with two plain characters, one when only the first is
 * plain, none (always test) for a leading group, class, escape or top-level
 * alternation. This is only a prefilter; the regex still decides.
 */
function literalKey(pattern: string): string | null {
  let depth = 0;
  for (const ch of pattern) {
    if (ch === '(') depth++;
    else if (ch === ')') depth--;
    else if (ch === '|' && depth === 0) return null;
  }
  const plain = (i: number) => /[A-Z0-9]/.test(pattern[i] ?? '') && !/[?*{]/.test(pattern[i + 1] ?? '');
  if (!plain(0)) return null;
  return plain(1) ? pattern.slice(0, 2) : pattern[0];
}

function brandIndex(): NonNullable<typeof index> {
  if (index) return index;
  const byKey = new Map<string, CompiledBrand[]>();
  const always: CompiledBrand[] = [];
  for (const brand of compileBrandTable()) {
    const key = literalKey(brand.pattern);
    if (!key) { always.push(brand); continue; }
    const list = byKey.get(key);
    if (list) list.push(brand); else byKey.set(key, [brand]);
  }
  index = { byKey, always };
  return index;
}

/** Parse the table. Throws on an unknown category alias so a typo cannot ship silently. */
export function compileBrandTable(): CompiledBrand[] {
  if (compiled) return compiled;
  const out: CompiledBrand[] = [];
  for (const [table, block] of Object.entries(TABLE)) {
    for (const rawLine of block.split('\n')) {
      const line = rawLine.trim();
      if (!line) continue;
      const colon = line.indexOf(':');
      const alias = line.slice(0, colon).trim();
      const category = ALIAS[alias];
      if (colon < 1 || !category) throw new Error(`brand-categories: bad alias "${alias}" in ${table}`);
      for (const rawPattern of line.slice(colon + 1).split(';')) {
        let pattern = rawPattern.trim();
        if (!pattern) continue;
        const gated = pattern.startsWith('!');
        if (gated) pattern = pattern.slice(1).trim();
        if (gated && table === 'GLOBAL') throw new Error(`brand-categories: GLOBAL pattern cannot be gated: ${pattern}`);
        out.push({ table, pattern, category, regex: compilePattern(pattern), gate: gated ? table : null });
      }
    }
  }
  compiled = out;
  return out;
}

/** Upper-case, accent-free, processor-delimiter-free text the patterns read. */
export function normalizeBrandDescriptor(descriptor: string): string {
  return descriptor
    .normalize('NFKD')
    .replace(/[̀-ͯ]/gu, '')
    .toUpperCase()
    .replace(/['’`]/gu, '')
    .replace(/[*_#|~]+/gu, ' ')
    .replace(/\s+/gu, ' ')
    .trim();
}

/**
 * The category a well-known brand in the descriptor implies, or null.
 * `market` is an ISO country; gated (ambiguous) brands need it to match.
 */
export function matchBrandCategory(descriptor: string, market?: string | null): BrandMatch | null {
  if (typeof descriptor !== 'string' || !descriptor.trim() || descriptor.length > 256) return null;
  const text = normalizeBrandDescriptor(descriptor);
  if (!text) return null;
  const country = typeof market === 'string' ? market.trim().toUpperCase() : null;
  const hits: { brand: CompiledBrand; start: number; end: number }[] = [];
  const { byKey, always } = brandIndex();
  const candidates = new Set<CompiledBrand>(always);
  for (let i = 0; i < text.length; i++) {
    if (!/[A-Z0-9]/.test(text[i]) || (i > 0 && /[A-Z0-9]/.test(text[i - 1]))) continue;
    for (const key of [text[i], text.slice(i, i + 2)]) for (const brand of byKey.get(key) ?? []) candidates.add(brand);
  }
  for (const brand of candidates) {
    if (brand.gate && brand.gate !== country) continue;
    const m = brand.regex.exec(text);
    if (m) hits.push({ brand, start: m.index, end: m.index + m[0].length });
  }
  if (!hits.length) return null;
  let best = hits[0];
  for (const hit of hits) if (hit.end - hit.start > best.end - best.start) best = hit;
  // Conflicting evidence outside the winning span means two different brands
  // (or a brand and a transit word) are present: decline rather than guess.
  for (const hit of hits) {
    if (hit.brand.category === best.brand.category) continue;
    const inside = hit.start >= best.start && hit.end <= best.end;
    if (!inside || hit.end - hit.start === best.end - best.start) return null;
  }
  const { table, pattern, category } = best.brand;
  return { table, pattern, category };
}

/** Size of the table, for tests and evaluation reports. */
export function brandTableStats(): { patterns: number; tables: number; countries: string[]; gated: number } {
  const all = compileBrandTable();
  const countries = Object.keys(TABLE).filter((key) => key !== 'GLOBAL');
  return { patterns: all.length, tables: Object.keys(TABLE).length, countries, gated: all.filter((b) => b.gate).length };
}
