/** Setup guidance only; never store Apple's free-form error text or message input. */
// One sentence per screen. The quoted Apple words (Automation, Message, Message
// Contains, Run Immediately, Next, Done) are the English iOS 26 Shortcuts
// labels, verified on the owner's iPhone. The Arabic ones follow Apple's
// Arabic UI and still need checking on an Arabic-language iPhone. "Space" is
// our word for the one character typed, not an Apple label.
// Every error says what happened, then the one thing to do next.
const copy = {
  en: {
    add: 'Add the shortcut', check: 'Test it', automate: 'Turn on the automation',
    bundled: 'Pick Shortcuts in the share sheet, then tap Add Shortcut.',
    bundledChips: ['Shortcuts', 'Add Shortcut'],
    checkBody: 'Tap Run test. If Shortcuts asks, tap Allow.',
    failed: 'Test failed: the shortcut did not reach Wafra.',
    stopped: 'Test stopped. Tap Run test to try again.',
    repair: 'Add the shortcut again',
    repairBody: 'Add the shortcut again, then run the test.',
    retry: 'Run test again',
    addedCheck: 'I added it — test it', editExisting: 'Edit my existing automation',
    existing: 'Already have a Wafra automation? Edit it instead of adding a second one.',
    waitingAutomation: 'Your next bank text confirms the automation.',
    verifiedAutomation: 'Working: a bank text reached Wafra.',
    relinkTitle: 'Point your automation at the new shortcut',
    relinkBody: 'In your Message automation, swap the old Wafra shortcut for {shortcut}, then tap Done.',
    relinkConfirm: 'I updated the automation',
    upgradeTitle: 'Update to Wafra Capture v3',
    upgradeBody: 'Capture still works. Update the shortcut, then point your automation at it.',
    upgradeAction: 'Update shortcut',
    upgradeDetail: 'Working · update available',
    otherWays: 'More ways to capture',
    otherWaysBody: 'Optional. Your Messages setup stays as it is.',
    statusSkipped: 'Skipped',
    // Guided flow.
    liveTitle: 'Catch new transactions',
    stepOf: 'Step {step} of {total}',
    screenOf: 'Screen {screen} of {total}',
    stepAdd: 'Add', stepTest: 'Test', stepAutomate: 'Automate',
    confirmTitle: 'Back from Shortcuts?',
    confirmBody: 'Tap below and Wafra tests the shortcut.',
    testPassed: 'Test passed',
    next: 'Next',
    previous: 'Previous',
    allSteps: 'Show all steps',
    inShortcuts: 'In Shortcuts',
    guide: [
      { title: 'Open Shortcuts', body: 'Tap Automation, then +.', chips: ['Automation', '+'] },
      { title: 'Choose Message', body: 'Scroll the list and tap Message.', chips: ['Message'] },
      { title: 'Type one space', body: 'In Message Contains, type a single space. Leave Sender empty.', chips: ['Message Contains', 'Space'] },
      { title: 'Run Immediately', body: 'Pick Run Immediately, turn off Notify When Run, then tap Next.', chips: ['Run Immediately', 'Next'] },
      { title: 'Pick the shortcut', body: 'Choose {shortcut}, then tap Done.', chips: ['{shortcut}', 'Done'] },
    ],
    doneTitle: 'You’re set',
    doneBody: 'Wafra is ready for your next bank text.',
    doneVerifiedBody: 'A bank text already reached Wafra.',
    oneToggleTitle: 'Add Wafra Capture',
    oneToggleBody: 'Add it, then turn on its automation.',
  },
  ar: {
    add: 'أضف الاختصار', check: 'اختبره', automate: 'فعّل الأتمتة',
    bundled: 'اختر «الاختصارات» من قائمة المشاركة، ثم اضغط «إضافة اختصار».',
    bundledChips: ['الاختصارات', 'إضافة اختصار'],
    checkBody: 'اضغط «تشغيل الاختبار». إذا طلبت الاختصارات إذناً، اضغط «سماح».',
    failed: 'فشل الاختبار: لم يصل الاختصار إلى وفرة.',
    stopped: 'توقف الاختبار. اضغط «تشغيل الاختبار» للمحاولة مجدداً.',
    repair: 'أضف الاختصار مجدداً',
    repairBody: 'أضف الاختصار مجدداً، ثم شغّل الاختبار.',
    retry: 'أعد تشغيل الاختبار',
    addedCheck: 'أضفته — اختبره', editExisting: 'تعديل أتمتتي الحالية',
    existing: 'لديك أتمتة لوفرة؟ عدّلها بدلاً من إضافة أتمتة ثانية.',
    waitingAutomation: 'رسالتك البنكية التالية تؤكد عمل الأتمتة.',
    verifiedAutomation: 'يعمل: وصلت رسالة بنكية إلى وفرة.',
    relinkTitle: 'وجّه الأتمتة إلى الاختصار الجديد',
    relinkBody: 'في أتمتة الرسائل، استبدل اختصار وفرة القديم بـ {shortcut}، ثم اضغط «تم».',
    relinkConfirm: 'حدّثت الأتمتة',
    upgradeTitle: 'التحديث إلى Wafra Capture v3',
    upgradeBody: 'الالتقاط ما زال يعمل. حدّث الاختصار، ثم وجّه الأتمتة إليه.',
    upgradeAction: 'تحديث الاختصار',
    upgradeDetail: 'يعمل · يتوفر تحديث',
    otherWays: 'طرق أخرى للالتقاط',
    otherWaysBody: 'اختياري. يبقى إعداد الرسائل كما هو.',
    statusSkipped: 'تم التخطي',
    liveTitle: 'التقط العمليات الجديدة',
    stepOf: 'الخطوة {step} من {total}',
    screenOf: 'الشاشة {screen} من {total}',
    stepAdd: 'إضافة', stepTest: 'اختبار', stepAutomate: 'أتمتة',
    confirmTitle: 'عدت من الاختصارات؟',
    confirmBody: 'اضغط أدناه وسيختبر وفرة الاختصار.',
    testPassed: 'نجح الاختبار',
    next: 'التالي',
    previous: 'السابق',
    allSteps: 'عرض كل الخطوات',
    inShortcuts: 'في الاختصارات',
    guide: [
      { title: 'افتح الاختصارات', body: 'اضغط «الأتمتة»، ثم +.', chips: ['الأتمتة', '+'] },
      { title: 'اختر «رسالة»', body: 'مرّر القائمة واضغط «رسالة».', chips: ['رسالة'] },
      { title: 'اكتب مسافة واحدة', body: 'في «تحتوي الرسالة على» اكتب مسافة واحدة، واترك «المرسل» فارغاً.', chips: ['تحتوي الرسالة على', 'مسافة'] },
      { title: 'تشغيل فوراً', body: 'اختر «تشغيل فوراً»، وأوقف «الإشعار عند التشغيل»، ثم اضغط «التالي».', chips: ['تشغيل فوراً', 'التالي'] },
      { title: 'اختر الاختصار', body: 'اختر {shortcut}، ثم اضغط «تم».', chips: ['{shortcut}', 'تم'] },
    ],
    doneTitle: 'أنت جاهز',
    doneBody: 'وفرة جاهز لرسالتك البنكية التالية.',
    doneVerifiedBody: 'وصلت رسالة بنكية إلى وفرة بالفعل.',
    oneToggleTitle: 'أضف Wafra Capture',
    oneToggleBody: 'أضفه، ثم فعّل الأتمتة الخاصة به.',
  },
};
export type IosShortcutSetupCopy = (typeof copy)['en'];
export const iosShortcutSetupCopy = (language: string): IosShortcutSetupCopy => copy[language === 'ar' ? 'ar' : 'en'];
