export const iosPagingBetaCopy = (language: string) => language === 'ar' ? {
  screenTitle: 'اختبار استيراد السجل',
  title: 'الرسائل السابقة، على دفعات',
  intro: 'هذا الاختبار الداخلي يفحص سجل الرسائل المتاح بدءاً من الأحدث. أبقِ تطبيق الاختصارات مفتوحاً والآيفون غير مقفل. لا يلزم اختيار بنك أو تسجيل دخول.',
  storage: 'يمكن استئناف الدفعات المحفوظة لمدة تصل إلى 24 ساعة. هذه بيانات مصدر مؤقتة وليست معاملات محفوظة في السجل. تتم المراجعة والتأكيد بعد الاستخراج.',
  unavailable: 'التقدم المحفوظ غير متاح أو انتهت صلاحيته. لم تتم إضافة معاملات بسبب هذا الفحص.',
  shortcutMissing: 'أضف اختصار Wafra History Paging Beta الموقّع قبل البدء.',
  cleanupFailed: 'لم يكتمل التنظيف. حاول مرة أخرى قبل بدء استيراد آخر.',
  staged: (count: string) => `${count} رسالة تم تجهيزها بأمان`,
  readable: (accepted: string, skipped: string) => `${accepted} مقروءة · ${skipped} غير مقروءة أو تم تخطيها`,
  complete: 'اكتمل الاستخراج. راجع قبل الحفظ.',
  continue: 'ما زال هناك سجل. تابع من الموضع المحفوظ.',
  review: 'مراجعة السجل المستخرج',
  resume: 'استئناف استيراد السجل',
  start: 'بدء استيراد السجل',
  refresh: 'تحديث التقدم المحفوظ',
  discard: 'حذف الاستيراد المؤقت',
  discardQuestion: 'حذف السجل المجهّز؟',
  discardBody: 'سيؤدي ذلك إلى حذف هذا الاستيراد المؤقت ومؤشر المتابعة المحفوظ. لن يتغير سجلك الحالي.',
  discardConfirm: 'حذف',
  requirement: 'يتطلب اختصار الاختبار الموقّع المطابق وهذا الإصدار الداخلي. ما زال سلوك استعلام Apple لصناديق الرسائل الكبيرة قيد التحقق على الجهاز.',
  shortcutName: 'Wafra History Paging Beta',
} : {
  screenTitle: 'History import beta',
  title: 'Past messages, in pages',
  intro: 'This internal test checks available message history, newest first. Keep Shortcuts open and the iPhone unlocked. No bank selection or login is needed.',
  storage: 'Saved pages can resume for up to 24 hours. They are temporary source data, not saved ledger transactions. Review and confirmation happen after extraction.',
  unavailable: 'Saved progress is unavailable or has expired. No transactions were added by this check.',
  shortcutMissing: 'Add the signed Wafra History Paging Beta Shortcut before starting.',
  cleanupFailed: 'Cleanup did not finish. Try again before starting another import.',
  staged: (count: string) => `${count} messages securely staged`,
  readable: (accepted: string, skipped: string) => `${accepted} readable · ${skipped} unreadable or skipped`,
  complete: 'Extraction finished. Review before saving.',
  continue: 'History remains. Continue from the saved position.',
  review: 'Review extracted history',
  resume: 'Resume history import',
  start: 'Start history import',
  refresh: 'Refresh saved progress',
  discard: 'Discard temporary import',
  discardQuestion: 'Discard staged history?',
  discardBody: 'This removes this temporary import and its saved cursor. Your existing ledger is not changed.',
  discardConfirm: 'Discard',
  requirement: 'Requires the matching signed beta Shortcut and this internal build. Large-inbox Apple query behavior is still under device validation.',
  shortcutName: 'Wafra History Paging Beta',
};
