/** Setup guidance only; never store Apple's free-form error text or message input. */
// One name for the check everywhere: "setup check" / «فحص الإعداد».
const copy = {
  en: {
    add: 'Add the Shortcut', check: 'Run the setup check', automate: 'Connect new messages',
    bundled: 'Choose Shortcuts in the share sheet, then Add Shortcut. Choose Replace if asked, and keep the name shown here.',
    checkBody: 'Run a quick setup check. Allow Wafra when Shortcuts asks, then return here.',
    checkNote: 'The setup check tests the Shortcut. A real bank alert confirms automatic delivery.',
    failed: 'The Shortcut did not finish the setup check.',
    stopped: 'Check was stopped — run it again when ready.',
    repair: 'Add the correct Shortcut',
    repairBody: 'First add the exact Shortcut shown below. If Apple showed an error, check the highlighted action in Shortcuts before trying again.',
    name: 'Shortcut name', retry: 'Run setup check again',
    permissions: 'Permission help',
    addedCheck: 'I added it — run setup check', editExisting: 'Edit an existing automation',
    existing: 'Already have a Wafra Message automation? Edit it to use this Shortcut instead of creating a second automation.',
    autoCheck: 'When you come back from Shortcuts, Wafra runs the setup check for you.',
    waitingAutomation: 'Setup checked. Wafra will confirm the automation when your next message arrives.',
    verifiedAutomation: 'Automation verified — a new message reached Wafra.',
    relinkTitle: 'Point your automation at the new Shortcut',
    relinkBody: 'Open your existing Message automation, replace the old Wafra Shortcut with {shortcut}, then tap Done.',
    relinkConfirm: 'I updated the automation',
    upgradeTitle: 'Update to Wafra Capture v3',
    upgradeBody: 'Capture is working with your current Shortcut. Update to Wafra Capture v3, then point your existing automation at it. Nothing changes until the new Shortcut passes the setup check.',
    upgradeAction: 'Update Shortcut',
    upgradeDetail: 'Working · update available',
    otherWays: 'Other ways to connect',
    otherWaysBody: 'Optional. Your message setup stays as it is until another source is fully set up.',
    statusSkipped: 'Skipped',
  },
  ar: {
    add: 'أضف الاختصار', check: 'شغّل فحص الإعداد', automate: 'اربط الرسائل الجديدة',
    bundled: 'اختر «الاختصارات» من قائمة المشاركة، ثم أضف الاختصار. اختر «استبدال» إذا ظهر، وأبقِ الاسم الظاهر هنا.',
    checkBody: 'شغّل فحص الإعداد السريع. اسمح بالوصول إلى وفرة عندما تطلب الاختصارات ذلك، ثم عد إلى هنا.',
    checkNote: 'يختبر فحص الإعداد الاختصار. يؤكد تنبيه بنكي حقيقي وصول الرسائل تلقائياً.',
    failed: 'لم يُكمل الاختصار فحص الإعداد.',
    stopped: 'توقف الفحص — شغّله مجدداً عندما تكون مستعداً.',
    repair: 'إضافة الاختصار الصحيح',
    repairBody: 'أضف أولاً الاختصار بالاسم الظاهر أدناه. إذا عرضت Apple خطأً، افحص الإجراء المحدد في الاختصارات قبل إعادة المحاولة.',
    name: 'اسم الاختصار', retry: 'إعادة تشغيل فحص الإعداد',
    permissions: 'مساعدة الأذونات',
    addedCheck: 'أضفته — شغّل فحص الإعداد', editExisting: 'تعديل أتمتة موجودة',
    existing: 'لديك أتمتة رسائل لوفرة؟ عدّلها لتستخدم هذا الاختصار بدلاً من إنشاء أتمتة ثانية.',
    autoCheck: 'عند عودتك من الاختصارات، يشغّل وفرة فحص الإعداد نيابةً عنك.',
    waitingAutomation: 'فُحص الإعداد. سيؤكد وفرة عمل الأتمتة عند وصول رسالتك التالية.',
    verifiedAutomation: 'تم التحقق من الأتمتة — وصلت رسالة جديدة إلى وفرة.',
    relinkTitle: 'وجّه الأتمتة إلى الاختصار الجديد',
    relinkBody: 'افتح أتمتة الرسائل الحالية، واستبدل اختصار وفرة القديم بـ {shortcut}، ثم اضغط «تم».',
    relinkConfirm: 'حدّثت الأتمتة',
    upgradeTitle: 'التحديث إلى Wafra Capture v3',
    upgradeBody: 'الالتقاط يعمل مع اختصارك الحالي. حدّث إلى Wafra Capture v3، ثم وجّه أتمتتك الحالية إليه. لا يتغير شيء حتى ينجح الاختصار الجديد في فحص الإعداد.',
    upgradeAction: 'تحديث الاختصار',
    upgradeDetail: 'يعمل · يتوفر تحديث',
    otherWays: 'طرق أخرى للربط',
    otherWaysBody: 'اختياري. يبقى إعداد الرسائل كما هو حتى يكتمل إعداد مصدر آخر.',
    statusSkipped: 'تم التخطي',
  },
};
export const iosShortcutSetupCopy = (language: string) => copy[language === 'ar' ? 'ar' : 'en'];
