export const merchantSpendingCopy = {
  en: {
    merchants: 'Merchants', browse: 'Spending by merchant', browseHint: 'Find a merchant and see your total',
    view: 'View merchant spending', activity: 'Merchant activity', total: 'Total spent',
    purchases: 'Transactions', average: 'Average transaction', last: 'Last spent',
    search: 'Search merchants', searchHint: 'Try a shop, restaurant or service', clear: 'Clear search',
    highest: 'Highest spending first', matching: 'Matching spending',
    spending: 'Spending', allActivity: 'All activity', received: 'Money received',
    receivedNote: 'Incoming payments are shown separately. They are not assumed to be refunds or subtracted from spending.',
    exclusions: 'Spending excludes transfers, card repayments and hidden accounts.',
    excludedRow: 'Not included in spending totals',
    identity: 'Grouped by the recorded merchant name. Different names are not automatically combined.',
    converted: 'Uses the converted amounts recorded in your ledger.',
    empty: 'No spending in this period', noMatch: 'No merchants match your search',
    emptyActivity: 'No activity in this period', allTime: 'See all time',
    pick: 'Choose a merchant', period: 'Change reporting period',
    sharedPeriod: 'Uses the same reporting period as Spending.', back: 'Back',
    recent: 'Recent transactions', viewAllTransactions: 'View all transactions',
    merchantDetails: 'View merchant details', entryDetails: 'Details',
  },
  ar: {
    merchants: 'التجار', browse: 'الإنفاق حسب التاجر', browseHint: 'ابحث عن تاجر واعرض إجمالي إنفاقك',
    view: 'عرض الإنفاق لدى التاجر', activity: 'حركات التاجر', total: 'إجمالي الإنفاق',
    purchases: 'الحركات', average: 'متوسط الحركة', last: 'آخر إنفاق',
    search: 'البحث عن تاجر', searchHint: 'متجر أو مطعم أو خدمة', clear: 'مسح البحث',
    highest: 'الأعلى إنفاقاً أولاً', matching: 'الإنفاق المطابق',
    spending: 'المصروفات', allActivity: 'كل الحركات', received: 'أموال مستلمة',
    receivedNote: 'تظهر الدفعات الواردة منفصلة. لا تُعتبر مبالغ مستردة تلقائياً ولا تُخصم من الإنفاق.',
    exclusions: 'لا يشمل الإنفاق التحويلات وسداد البطاقات والحسابات المخفية.',
    excludedRow: 'غير مشمولة في إجمالي الإنفاق',
    identity: 'التجميع حسب اسم التاجر المسجل. لا تُدمج الأسماء المختلفة تلقائياً.',
    converted: 'تُستخدم المبالغ المحوّلة المسجلة في سجلك.',
    empty: 'لا يوجد إنفاق في هذه الفترة', noMatch: 'لا يوجد تاجر يطابق بحثك',
    emptyActivity: 'لا توجد حركات في هذه الفترة', allTime: 'عرض كل الفترات',
    pick: 'اختر تاجراً', period: 'تغيير فترة التقرير',
    sharedPeriod: 'تُستخدم فترة التقرير نفسها في صفحة الإنفاق.', back: 'رجوع',
    recent: 'أحدث الحركات', viewAllTransactions: 'عرض كل الحركات',
    merchantDetails: 'عرض تفاصيل التاجر', entryDetails: 'التفاصيل',
  },
} as const;
