/**
 * Words for Accounts, account and goal detail, the card sheets and Bills.
 *
 * English and Arabic keep identical keys (a parity test checks). Figures come
 * in already formatted; this module only decides the sentence around them.
 * Everything here describes what Wafra RECORDS — it never sends or moves
 * money, and the copy never says it does.
 */

/** Arabic count agreement for "charges" (دفعة). */
const arCharges = (n: number): string =>
  n === 1 ? 'آخر دفعة' : n === 2 ? 'آخر دفعتين' : n >= 3 && n <= 10 ? `آخر ${n} دفعات` : `آخر ${n} دفعة`;

export const moneyPlacesCopy = {
  en: {
    // Wallet
    updateBalance: 'Update balance',
    hide: 'Hide',
    quietActionsA11y: (name: string) => `${name} has not had a new balance for a while`,
    addActivity: 'Add activity',
    importStatement: 'Import a bank statement',
    importStatementDetail: 'PDF or CSV files from your bank',
    addByHand: 'Add by hand',
    addByHandDetail: 'Cash, or anything Wafra missed',
    pasteMessage: 'Paste a bank message',
    pasteMessageDetail: 'For an alert Wafra did not catch',
    statementTotal: (amount: string) => `Statement ${amount}`,
    capturedThisMonth: (amount: string) => `${amount} captured this month`,
    capturedNote: 'Captured is spending Wafra recorded on this card, not a bank figure.',
    usedOfLimit: (used: string, limit: string) => `${used} used of your ${limit} limit`,
    markPaid: 'Mark paid',
    markMinimumPaid: 'Mark minimum paid',
    markPaidA11y: (card: string) => `Mark the ${card} statement paid`,
    markMinimumPaidA11y: (card: string) => `Mark the minimum on ${card} paid`,
    openAccountA11y: (name: string) => `Open ${name}`,
    // Account detail
    accountTitle: 'Account',
    bankAccount: 'Bank account',
    cashAccount: 'Cash',
    latestBalance: 'Latest balance',
    noBalanceYet: 'No balance reported yet',
    trackedByHand: 'Your opening balance plus the entries you added',
    recordedIn: 'Recorded in this month',
    recordedOut: 'Recorded out this month',
    recordedNote: 'From the entries Wafra has on this account. Not a bank statement.',
    balanceWrong: 'Balance looks wrong?',
    setTodaysBalance: 'Set today’s balance',
    setBalanceBody: 'Wafra keeps your transactions as they are.',
    setBalanceQuestion: (name: string) => `What is in ${name} today?`,
    balanceToday: 'Balance today',
    save: 'Save',
    recent: 'Recent',
    seeAll: 'See all',
    seeAllA11y: (name: string) => `See all transactions on ${name}`,
    noRecent: 'No entries on this account yet.',
    manage: 'Manage account',
    accountMissing: 'This account is no longer in Wafra.',
    back: 'Back',
    // Goals
    goalTitle: 'Goal',
    savedOf: (saved: string, target: string) => `${saved} of ${target}`,
    toGo: (amount: string) => `${amount} to go`,
    reached: 'Goal reached',
    progressA11y: (percent: number) => `${percent} percent saved`,
    addMoney: 'Add money',
    editGoal: 'Edit goal',
    deleteGoal: 'Delete goal',
    goalName: 'Goal name',
    goalTarget: 'Target amount',
    goalSavedSoFar: 'Saved so far',
    addMoneyQuestion: (goal: string) => `How much did you put aside for ${goal}?`,
    noMoneyMoves: 'Adding money here only records it in Wafra. No money moves between your accounts.',
    goalMissing: 'This goal is no longer in Wafra.',
    // Card detail
    statementBalance: 'Statement balance',
    leftOfStatement: (left: string, total: string) => `${left} left of ${total}`,
    dueOn: (date: string) => `Due ${date}`,
    minimum: (amount: string) => `Min ${amount}`,
    recordPayment: 'Record a payment',
    cardReminder: (date: string) =>
      `When notifications are on, Wafra reminds you three days before ${date} and again on the day.`,
    // Card payment sheet
    cardPaymentTitle: 'Card payment',
    cardPaymentFor: (card: string, date: string) => `${card} · due ${date}`,
    fullStatement: 'Full statement',
    restOfStatement: 'What is left on the statement',
    minimumDue: 'Minimum due',
    restOfMinimum: 'What is left of the minimum',
    anotherAmount: 'Another amount',
    amountField: 'Amount paid',
    overRemaining: (amount: string) => `Up to ${amount}, what is left on this statement.`,
    invalidAmount: 'Enter the amount you paid.',
    recordThisPayment: 'Record payment',
    recordPartialQuestion: 'Record this payment?',
    paymentNote: 'This only records a payment you made from your bank. Wafra sends no money, and it will not count as spending twice.',
    // Bills
    next30Days: 'Next 30 days',
    next30Total: 'Due in the next 30 days',
    today: 'Today',
    markedCancelled: (title: string) => `${title} marked as cancelled`,
    undo: 'Undo',
    allBills: 'All',
    everything: 'Everything',
    subscriptions: 'Subscriptions',
    perMonth: (amount: string) => `${amount} / month`,
    subscriptionsTotalA11y: (amount: string) => `Subscriptions, ${amount} a month`,
    billsAndCards: 'Bills and cards',
    wasPrice: (amount: string) => `was ${amount}`,
    priceWentUp: 'Price went up',
    likelyStopped: 'Likely stopped',
    markCancelled: 'Mark as cancelled',
    markCancelledQuestion: (title: string) => `Mark ${title} as cancelled?`,
    markCancelledBody: 'It leaves your upcoming bills and monthly totals, and its history stays. If the bank charges it again, it comes back.',
    cancelledByYou: 'Cancelled by you',
    cancelledOn: (date: string) => `You marked it cancelled on ${date}`,
    stillPaying: 'Still paying',
    stillPayingA11y: (title: string) => `Still paying ${title}`,
    timelineA11y: (count: number) => count === 1 ? '1 payment in the next 30 days' : `${count} payments in the next 30 days`,
    pinA11y: (title: string, date: string) => `${title}, ${date}`,
    nothingIn30Days: 'Nothing due in the next 30 days.',
    calendarA11y: 'Payment days this month',
    // Bill detail
    billTitle: 'Bill',
    estimateFrom: (n: number) => n === 1 ? 'Based on your last charge' : `Estimate from your last ${n} charges`,
    dueDayEachMonth: (day: number) => `Day ${day} of each month`,
    dueDayLabel: 'Due day',
    billReminder: 'When notifications are on, Wafra reminds you the day before and on the day.',
    renewalReminder: 'When notifications are on, Wafra reminds you the day before it renews.',
    editBill: 'Edit bill',
    billName: 'Name',
    billAmount: 'Amount',
    billDueDay: 'Due day (1–31)',
    saveBill: 'Save bill',
    dayNotInMonth: (date: string) => `That day does not exist in the month this yearly bill falls in (${date}).`,
    detectedCannotEdit: 'Wafra made this reminder from a detected charge and may update it from your bank notices, so it cannot be edited here. Delete it and add your own to change it.',
    // Design language E: bands and sheets
    billsViews: 'Bills view',
    paymentsCount: (n: number) => n === 1 ? '1 payment' : `${n} payments`,
    estimatesCount: (n: number) => n === 1 ? '1 is an estimate' : `${n} are estimates`,
    about: 'About',
    lastSixMonths: 'Last 6 months',
    cardsApart: (n: number) => n === 1 ? '1 card, shown on its own' : `${n} cards, shown on their own`,
    details: 'Details',
    detailsA11y: (card: string) => `Details for ${card}`,
    noBalanceFigure: 'No balance yet',
    savedWord: 'saved',
    leftToSave: 'Left to save',
    recordAmount: (amount: string) => `Record ${amount}`,
    settlesIt: 'Clears the statement',
    asBankStated: 'As your bank stated',
    typeIt: 'Type it',
    cardsCount: (n: number) => n === 1 ? '1 card' : `${n} cards`,
  },
  ar: {
    updateBalance: 'تحديث الرصيد',
    hide: 'إخفاء',
    quietActionsA11y: (name: string) => `لم يصل رصيد جديد لحساب ${name} منذ مدة`,
    addActivity: 'إضافة نشاط',
    importStatement: 'استيراد كشف حساب بنكي',
    importStatementDetail: 'ملفات PDF أو CSV من بنكك',
    addByHand: 'إضافة يدوياً',
    addByHandDetail: 'النقد، أو أي عملية فاتت وفرة',
    pasteMessage: 'ألصق رسالة بنكية',
    pasteMessageDetail: 'لتنبيه لم تلتقطه وفرة',
    statementTotal: (amount: string) => `الكشف ${amount}`,
    capturedThisMonth: (amount: string) => `${amount} مسجّلة هذا الشهر`,
    capturedNote: 'المسجّل هو ما رصدته وفرة من إنفاق على هذه البطاقة، وليس رقماً من البنك.',
    usedOfLimit: (used: string, limit: string) => `${used} مستخدمة من حدك البالغ ${limit}`,
    markPaid: 'تعليم كمدفوعة',
    markMinimumPaid: 'تعليم الحد الأدنى كمدفوع',
    markPaidA11y: (card: string) => `تعليم كشف ${card} كمدفوع`,
    markMinimumPaidA11y: (card: string) => `تعليم الحد الأدنى لـ ${card} كمدفوع`,
    openAccountA11y: (name: string) => `فتح ${name}`,
    accountTitle: 'الحساب',
    bankAccount: 'حساب بنكي',
    cashAccount: 'النقد',
    latestBalance: 'آخر رصيد',
    noBalanceYet: 'لم يصل أي رصيد بعد',
    trackedByHand: 'رصيدك الافتتاحي مع العمليات التي أضفتها',
    recordedIn: 'المسجّل وارداً هذا الشهر',
    recordedOut: 'المسجّل صادراً هذا الشهر',
    recordedNote: 'من العمليات المسجّلة لدى وفرة على هذا الحساب، وليس كشفاً بنكياً.',
    balanceWrong: 'الرصيد غير صحيح؟',
    setTodaysBalance: 'أدخل رصيد اليوم',
    setBalanceBody: 'تبقى عملياتك كما هي.',
    setBalanceQuestion: (name: string) => `كم في ${name} اليوم؟`,
    balanceToday: 'رصيد اليوم',
    save: 'حفظ',
    recent: 'الأحدث',
    seeAll: 'عرض الكل',
    seeAllA11y: (name: string) => `عرض كل العمليات على ${name}`,
    noRecent: 'لا توجد عمليات على هذا الحساب بعد.',
    manage: 'إدارة الحساب',
    accountMissing: 'لم يعد هذا الحساب في وفرة.',
    back: 'رجوع',
    goalTitle: 'الهدف',
    savedOf: (saved: string, target: string) => `${saved} من ${target}`,
    toGo: (amount: string) => `متبقٍ ${amount}`,
    reached: 'تحقق الهدف',
    progressA11y: (percent: number) => `تم ادخار ${percent} بالمئة`,
    addMoney: 'إضافة مبلغ',
    editGoal: 'تعديل الهدف',
    deleteGoal: 'حذف الهدف',
    goalName: 'اسم الهدف',
    goalTarget: 'المبلغ المستهدف',
    goalSavedSoFar: 'المدّخر حتى الآن',
    addMoneyQuestion: (goal: string) => `كم ادّخرت من أجل ${goal}؟`,
    noMoneyMoves: 'إضافة مبلغ هنا تسجّله في وفرة فقط، ولا تنقل أي مال بين حساباتك.',
    goalMissing: 'لم يعد هذا الهدف في وفرة.',
    statementBalance: 'رصيد الكشف',
    leftOfStatement: (left: string, total: string) => `متبقٍ ${left} من ${total}`,
    dueOn: (date: string) => `الاستحقاق ${date}`,
    minimum: (amount: string) => `الحد الأدنى ${amount}`,
    recordPayment: 'تسجيل دفعة',
    cardReminder: (date: string) =>
      `عند تفعيل الإشعارات، تذكّرك وفرة قبل ${date} بثلاثة أيام ومرة أخرى في يوم الاستحقاق.`,
    cardPaymentTitle: 'دفعة البطاقة',
    cardPaymentFor: (card: string, date: string) => `${card} · الاستحقاق ${date}`,
    fullStatement: 'الكشف كاملاً',
    restOfStatement: 'المتبقي من الكشف',
    minimumDue: 'الحد الأدنى المستحق',
    restOfMinimum: 'المتبقي من الحد الأدنى',
    anotherAmount: 'مبلغ آخر',
    amountField: 'المبلغ المدفوع',
    overRemaining: (amount: string) => `حتى ${amount}، وهو المتبقي من هذا الكشف.`,
    invalidAmount: 'أدخل المبلغ الذي دفعته.',
    recordThisPayment: 'تسجيل الدفعة',
    recordPartialQuestion: 'تسجيل هذه الدفعة؟',
    paymentNote: 'هذا يسجّل دفعة أجريتها من بنكك فقط. لا ترسل وفرة أي مال، ولن تُحتسب كإنفاق مرتين.',
    next30Days: 'الأيام الثلاثون القادمة',
    next30Total: 'المستحق خلال الأيام الثلاثين القادمة',
    today: 'اليوم',
    markedCancelled: (title: string) => `علّمت ${title} كملغى`,
    undo: 'تراجع',
    allBills: 'الكل',
    everything: 'كل الأنواع',
    subscriptions: 'الاشتراكات',
    perMonth: (amount: string) => `${amount} / شهرياً`,
    subscriptionsTotalA11y: (amount: string) => `الاشتراكات، ${amount} شهرياً`,
    billsAndCards: 'الفواتير والبطاقات',
    wasPrice: (amount: string) => `كان ${amount}`,
    priceWentUp: 'ارتفع السعر',
    likelyStopped: 'متوقف على الأرجح',
    markCancelled: 'تعليم كملغى',
    markCancelledQuestion: (title: string) => `تعليم ${title} كملغى؟`,
    markCancelledBody: 'سيُزال من فواتيرك القادمة ومجاميعك الشهرية ويبقى سجله. إن خصمه البنك مجدداً فسيعود.',
    cancelledByYou: 'ألغيتها بنفسك',
    cancelledOn: (date: string) => `علّمته كملغى في ${date}`,
    stillPaying: 'ما زلت أدفع',
    stillPayingA11y: (title: string) => `ما زلت أدفع ${title}`,
    timelineA11y: (count: number) => count === 1 ? 'دفعة واحدة خلال الأيام الثلاثين القادمة'
      : count === 2 ? 'دفعتان خلال الأيام الثلاثين القادمة'
        : count >= 3 && count <= 10 ? `${count} دفعات خلال الأيام الثلاثين القادمة`
          : `${count} دفعة خلال الأيام الثلاثين القادمة`,
    pinA11y: (title: string, date: string) => `${title}، ${date}`,
    nothingIn30Days: 'لا شيء مستحق خلال الأيام الثلاثين القادمة.',
    calendarA11y: 'أيام الدفع هذا الشهر',
    billTitle: 'الفاتورة',
    estimateFrom: (n: number) => n === 1 ? 'بناءً على آخر دفعة' : `تقدير من ${arCharges(n)}`,
    dueDayEachMonth: (day: number) => `اليوم ${day} من كل شهر`,
    dueDayLabel: 'يوم الاستحقاق',
    billReminder: 'عند تفعيل الإشعارات، تذكّرك وفرة قبل يوم ومرة أخرى في يوم الاستحقاق.',
    renewalReminder: 'عند تفعيل الإشعارات، تذكّرك وفرة قبل يوم من التجديد.',
    editBill: 'تعديل الفاتورة',
    billName: 'الاسم',
    billAmount: 'المبلغ',
    billDueDay: 'يوم الاستحقاق (1–31)',
    saveBill: 'حفظ الفاتورة',
    dayNotInMonth: (date: string) => `هذا اليوم غير موجود في شهر هذه الفاتورة السنوية (${date}).`,
    detectedCannotEdit: 'أنشأت وفرة هذا التذكير من عملية مكتشفة وقد تحدّثه من إشعارات بنكك، لذا لا يمكن تعديله هنا. احذفه وأضف تذكيرك الخاص لتغييره.',
    billsViews: 'عرض الفواتير',
    paymentsCount: (n: number) => n === 1 ? 'دفعة واحدة' : n === 2 ? 'دفعتان'
      : n >= 3 && n <= 10 ? `${n} دفعات` : `${n} دفعة`,
    estimatesCount: (n: number) => n === 1 ? 'واحدة منها تقديرية' : n === 2 ? 'اثنتان منها تقديريتان'
      : `${n} منها تقديرية`,
    about: 'حوالي',
    lastSixMonths: 'آخر 6 أشهر',
    cardsApart: (n: number) => n === 1 ? 'بطاقة واحدة تظهر منفصلة' : n === 2 ? 'بطاقتان تظهران منفصلتين'
      : n >= 3 && n <= 10 ? `${n} بطاقات تظهر منفصلة` : `${n} بطاقة تظهر منفصلة`,
    details: 'التفاصيل',
    detailsA11y: (card: string) => `تفاصيل ${card}`,
    noBalanceFigure: 'لا يوجد رصيد بعد',
    savedWord: 'مُدّخر',
    leftToSave: 'المتبقي للادخار',
    recordAmount: (amount: string) => `تسجيل ${amount}`,
    settlesIt: 'لا يبقى شيء في الكشف',
    asBankStated: 'كما ذكره بنكك',
    typeIt: 'اكتبه',
    cardsCount: (n: number) => n === 1 ? 'بطاقة واحدة' : n === 2 ? 'بطاقتان'
      : n >= 3 && n <= 10 ? `${n} بطاقات` : `${n} بطاقة`,
  },
} as const;

export type MoneyPlacesWords = (typeof moneyPlacesCopy)['en'];

export function moneyPlacesWords(language: string): MoneyPlacesWords {
  return (language === 'ar' ? moneyPlacesCopy.ar : moneyPlacesCopy.en) as MoneyPlacesWords;
}
