/** Localized editorial copy for the monthly/yearly recap story. */
export const recapCopy = {
  en: {
    recap: 'WAFRA RECAP',
    monthIntro: 'Your month, in money.',
    yearIntro: 'Your year, in money.',
    introBody: 'Spend · income · habits',
    spent: 'You spent',
    transactions: 'payments',
    merchants: 'merchants',
    income: 'Income',
    net: 'Net',
    less: 'less than the previous period',
    more: 'more than the previous period',
    categories: 'WHERE IT WENT',
    topCategory: 'took the largest share',
    merchant: 'MOST SPENT AT',
    visits: 'payments',
    account: 'MOST USED CARD',
    accountFallback: 'MOST USED ACCOUNT',
    used: 'used',
    rhythm: 'WHEN YOU SPENT',
    noSpend: 'no-spend days',
    average: 'average payment',
    busiest: 'had the most payments',
    morning: 'Morning', afternoon: 'Afternoon', evening: 'Evening', night: 'Night',
    favoriteTime: 'most payments',
    biggest: 'LARGEST PAYMENT',
    monthly: 'MONTH BY MONTH',
    quietest: 'Quietest month',
    highest: 'Highest month',
    finale: 'YOUR RECAP',
    wrapped: 'That’s the period, in one page.',
    done: 'Done',
    close: 'Close recap',
  },
  ar: {
    recap: 'ملخص وفرة',
    monthIntro: 'شهرك، بلغة المال.',
    yearIntro: 'سنتك، بلغة المال.',
    introBody: 'الإنفاق · الدخل · العادات',
    spent: 'أنفقت',
    transactions: 'دفعات',
    merchants: 'متجر',
    income: 'الدخل',
    net: 'الصافي',
    less: 'أقل من الفترة السابقة',
    more: 'أكثر من الفترة السابقة',
    categories: 'أين ذهب المال',
    topCategory: 'أخذت الحصة الأكبر',
    merchant: 'أعلى إنفاق لدى',
    visits: 'دفعات',
    account: 'البطاقة الأكثر استخداماً',
    accountFallback: 'الحساب الأكثر استخداماً',
    used: 'استُخدمت',
    rhythm: 'متى أنفقت',
    noSpend: 'أيام بلا إنفاق',
    average: 'متوسط الدفعة',
    busiest: 'شهد أكبر عدد من الدفعات',
    morning: 'الصباح', afternoon: 'بعد الظهر', evening: 'المساء', night: 'الليل',
    favoriteTime: 'أغلب الدفعات',
    biggest: 'أكبر دفعة',
    monthly: 'شهراً بشهر',
    quietest: 'أهدأ شهر',
    highest: 'أعلى شهر',
    finale: 'ملخصك',
    wrapped: 'الفترة كلها، في صفحة واحدة.',
    done: 'تم',
    close: 'إغلاق الملخص',
  },
} as const;
