/** Localized editorial copy for the monthly/yearly recap story. */
export const recapCopy = {
  en: {
    recap: 'WAFRA RECAP',
    monthIntro: 'Your month, in money.',
    yearIntro: 'Your year, in money.',
    introBody: 'The patterns behind what came in, what went out, and where it went.',
    spent: 'You spent',
    transactions: 'payments',
    merchants: 'merchants',
    less: 'less than the previous period',
    more: 'more than the previous period',
    categories: 'WHERE IT WENT',
    topCategory: 'was your biggest category',
    merchant: 'YOUR #1 MERCHANT',
    visits: 'payments',
    account: 'YOUR GO-TO CARD',
    accountFallback: 'YOUR GO-TO ACCOUNT',
    used: 'used',
    rhythm: 'YOUR MONEY RHYTHM',
    noSpend: 'no-spend days',
    average: 'average payment',
    busiest: 'busiest spending day',
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
    night: 'Night',
    favoriteTime: 'most payments happened in the',
    biggest: 'YOUR BIGGEST SPEND',
    monthly: 'THE SHAPE OF YOUR YEAR',
    quietest: 'Quietest month',
    highest: 'Highest month',
    finale: 'THAT WAS YOUR',
    wrapped: 'A clearer picture, built from your own ledger.',
    done: 'Done',
    close: 'Close recap',
  },
  ar: {
    recap: 'ملخص وفرة',
    monthIntro: 'شهرك، بلغة المال.',
    yearIntro: 'سنتك، بلغة المال.',
    introBody: 'الأنماط وراء ما دخل، وما خرج، وإلى أين ذهب.',
    spent: 'أنفقت',
    transactions: 'دفعات',
    merchants: 'متجر',
    less: 'أقل من الفترة السابقة',
    more: 'أكثر من الفترة السابقة',
    categories: 'أين ذهب المال',
    topCategory: 'كانت أكبر فئة لديك',
    merchant: 'متجرك الأول',
    visits: 'دفعات',
    account: 'بطاقتك الأكثر استخداماً',
    accountFallback: 'حسابك الأكثر استخداماً',
    used: 'استُخدمت',
    rhythm: 'إيقاع إنفاقك',
    noSpend: 'أيام بلا إنفاق',
    average: 'متوسط الدفعة',
    busiest: 'أكثر يوم إنفاقاً',
    morning: 'الصباح',
    afternoon: 'بعد الظهر',
    evening: 'المساء',
    night: 'الليل',
    favoriteTime: 'حدثت معظم الدفعات في',
    biggest: 'أكبر إنفاق',
    monthly: 'شكل سنتك',
    quietest: 'أهدأ شهر',
    highest: 'أعلى شهر',
    finale: 'كان هذا ملخص',
    wrapped: 'صورة أوضح، مبنية من سجلك أنت.',
    done: 'تم',
    close: 'إغلاق الملخص',
  },
} as const;
