/** Localized presentation vocabulary shared by the approved redesign. */

/** Arabic day counts: يوم واحد، يومان، ٣–١٠ أيام، ١١+ يوماً. */
function arabicDays(n: number): string {
  return n === 1 ? 'يوم واحد' : n === 2 ? 'يومين' : n <= 10 ? `${n} أيام` : `${n} يوماً`;
}

export const paymentAgendaCopy = {
  en: { overdue: 'Past due', 'expected-earlier': 'Expected earlier', soon: 'Next 7 days', later: 'Later', paid: 'Recently paid',
    estimate: 'Estimated', recorded: 'Paid · due', statement: 'Statement due', empty: 'Nothing coming up',
    emptyBody: 'Add a bill reminder or import your bank alerts. Wafra will show the dates it can verify.',
    note: 'Reminders, not payments', noteBody: 'Marking something paid only updates Wafra. No payment is sent.',
    today: 'Today', tomorrow: 'Tomorrow', paidStatement: 'Paid statement · due',
    subscriptions: 'Subscriptions', utilities: 'Utilities & telecom', cards: 'Card payments', loans: 'Loan repayments', other: 'Other bills',
    subscriptionsHint: 'Recurring memberships and services', utilitiesHint: 'Electricity, water, phone and internet',
    emptySubscriptions: 'No subscription renewals to show.', emptyUtilities: 'No utility bills to show.',
    emptyCards: 'No credit-card payments to show.', emptyLoans: 'No loan repayments to show.', emptyOther: 'No other bills to show.',
    showMore: (count: number) => `Show ${count} more` },
  ar: { overdue: 'متأخرة', 'expected-earlier': 'كانت متوقعة سابقاً', soon: 'خلال 7 أيام', later: 'لاحقاً', paid: 'مدفوعة مؤخراً',
    estimate: 'تقديري', recorded: 'مدفوعة · استحقاقها', statement: 'استحقاق الكشف', empty: 'لا توجد دفعات قادمة',
    emptyBody: 'أضف تذكيراً بفاتورة أو استورد تنبيهات البنك لعرض التواريخ المعروفة.',
    note: 'تذكيرات وليست خدمة دفع', noteBody: 'وضع علامة «مدفوع» يحدّث وفرة فقط. لا يتم إرسال أي دفعة.',
    today: 'اليوم', tomorrow: 'غداً', paidStatement: 'كشف مدفوع · استحقاقه',
    subscriptions: 'الاشتراكات', utilities: 'المرافق والاتصالات', cards: 'دفعات البطاقات', loans: 'أقساط القروض', other: 'فواتير أخرى',
    subscriptionsHint: 'العضويات والخدمات المتكررة', utilitiesHint: 'الكهرباء والمياه والهاتف والإنترنت',
    emptySubscriptions: 'لا توجد تجديدات اشتراكات لعرضها.', emptyUtilities: 'لا توجد فواتير مرافق لعرضها.',
    emptyCards: 'لا توجد دفعات بطاقات ائتمانية لعرضها.', emptyLoans: 'لا توجد أقساط قروض لعرضها.', emptyOther: 'لا توجد فواتير أخرى لعرضها.',
    showMore: (count: number) => `عرض ${count} أخرى` },
};

export const accountGroupsCopy = {
  en: { bank: 'Bank accounts', credit: 'Credit cards', debit: 'Other cards', cash: 'Cash',
    unknown: 'No recorded figure', manage: 'Manage account', empty: 'No accounts yet',
    sourceNote: 'Your accounts, clearly separated', sourceBody: 'Recorded balances are not a live bank connection. Credit-card dues are shown separately.' },
  ar: { bank: 'الحسابات المصرفية', credit: 'البطاقات الائتمانية', debit: 'بطاقات أخرى', cash: 'النقد',
    unknown: 'لا يوجد مبلغ مسجل', manage: 'إدارة الحساب', empty: 'لا توجد حسابات بعد',
    sourceNote: 'حساباتك بوضوح', sourceBody: 'الأرصدة المسجلة ليست اتصالاً مباشراً بالبنك. تظهر استحقاقات البطاقات الائتمانية منفصلة.' },
};

export const spendingCopy = {
  en: { categories: 'Categories', activity: 'Activity', trends: 'Trends', spent: 'Total spent',
    limited: 'Categories with limits', of: 'of', all: 'All', withLimits: 'With limits', noLimits: 'No limits',
    noLimit: 'No limit set', setLimit: 'Set monthly limit', manage: 'Edit monthly limit', monthlyOnly: 'Category limits are monthly. Choose a month to view them.',
    empty: 'No spending in this period', emptyBody: 'Add an expense or import bank alerts to see your categories here.',
    emptyFilter: 'No categories match this filter', left: 'left', over: 'over limit',
    details: 'View transactions', newLimit: 'New category limit', search: 'Search spending', allActivity: 'View all spending',
    noResults: 'No matching expenses', searchHint: 'Search by merchant or account',
    summaryNote: 'Only categories with a limit are included below.', used: 'used', month: 'This period',
    breakdown: 'Where it went', share: 'of spending', shareNote: 'Each category’s share of total spending', otherCategories: 'Other categories', budgetUsed: 'of limit used',
    lastSixMonths: 'Last 6 months', average: 'Avg', latest: 'Latest', vs: 'vs', askWafra: 'Ask Wafra', explain: 'Explain this',
    aboveAverage: (percent: number) => `Current total is ${percent}% above the 6-month average.`,
    belowAverage: (percent: number) => `Current total is ${percent}% below the 6-month average.`,
    nearAverage: 'Current total is close to the 6-month average.',
    compare: 'Compare', calendar: 'Calendar', shareBar: 'Share of spending by category',
    dayOf: (day: number, of: number) => `day ${day} of ${of}`,
    limitOf: (percent: number, limit: string) => `${percent}% of ${limit} limit`,
    history: 'Six months and top merchants' },
  ar: { categories: 'الفئات', activity: 'الحركات', trends: 'الاتجاهات', spent: 'إجمالي الإنفاق',
    limited: 'الفئات ذات الحدود', of: 'من', all: 'الكل', withLimits: 'بحد إنفاق', noLimits: 'بلا حد',
    noLimit: 'لا يوجد حد محدد', setLimit: 'تحديد حد شهري', manage: 'تعديل الحد الشهري', monthlyOnly: 'حدود الفئات شهرية. اختر شهراً لعرضها.',
    empty: 'لا يوجد إنفاق في هذه الفترة', emptyBody: 'أضف مصروفاً أو استورد تنبيهات البنك لعرض الفئات هنا.',
    emptyFilter: 'لا توجد فئات مطابقة', left: 'متبقٍ', over: 'فوق الحد',
    details: 'عرض العمليات', newLimit: 'حد إنفاق جديد', search: 'البحث في المصروفات', allActivity: 'عرض كل المصروفات',
    noResults: 'لا توجد مصروفات مطابقة', searchHint: 'ابحث باسم التاجر أو الحساب',
    summaryNote: 'يشمل المؤشر أدناه الفئات التي لها حد فقط.', used: 'مستخدم', month: 'هذه الفترة',
    breakdown: 'أين أنفقت', share: 'من الإنفاق', shareNote: 'حصة كل فئة من إجمالي الإنفاق', otherCategories: 'فئات أخرى', budgetUsed: 'من الحد مستخدم',
    lastSixMonths: 'آخر ٦ أشهر', average: 'المتوسط', latest: 'الأحدث', vs: 'مقابل', askWafra: 'اسأل وفرة', explain: 'اشرح هذا',
    aboveAverage: (percent: number) => `الإجمالي الحالي أعلى من متوسط ٦ أشهر بنسبة ${percent}٪.`,
    belowAverage: (percent: number) => `الإجمالي الحالي أقل من متوسط ٦ أشهر بنسبة ${percent}٪.`,
    nearAverage: 'الإجمالي الحالي قريب من متوسط ٦ أشهر.',
    compare: 'المقارنة', calendar: 'التقويم', shareBar: 'حصة كل فئة من الإنفاق',
    dayOf: (day: number, of: number) => `اليوم ${day} من ${of}`,
    limitOf: (percent: number, limit: string) => `${percent}٪ من حد ${limit}`,
    history: 'ستة أشهر وأبرز التجار' },
} as const;

export const spendingTrendsCopy = {
  en: { cashflow: 'Income & spending', sixMonths: 'Six money months', income: 'Income', spending: 'Spending', net: 'Net',
    latest: 'Latest', merchants: 'Top merchants', change: 'What changed', fewer: 'Less', more: 'More', vs: 'Compared with',
    noMerchants: 'Merchant trends will appear after you add spending.', noChange: 'No material category change for this comparison.',
    missingComparison: 'Choose a shorter period for a comparable view.', patterns: 'Spending by weekday',
    patternsNote: 'Recorded spending, excluding fixed commitments. This is not a forecast.',
    noData: 'No recorded activity', records: 'transactions', partial: 'The selected month may be incomplete.',
    spentLess: 'less than', spentMore: 'more than', spentSame: 'About the same as', byThisDay: 'by this day', youSpent: 'You’ve spent',
    fixedLeftOut: 'Rent and other fixed costs are left out.', spendingMore: 'Spending more', spendingLess: 'Spending less',
    calendarLegend: 'Stronger colour means more everyday spending. Rent and fixed costs are left out.',
    calendarNoSpend: (n: number) => `${n} no-spend ${n === 1 ? 'day' : 'days'}`,
    calendarShowing: 'Showing', calendarAll: 'Show all days', calendarNothing: 'nothing spent', calendarFixedOnly: 'fixed costs only',
    calendarWeekday: (column: number) => ['M', 'T', 'W', 'T', 'F', 'S', 'S'][column] ?? '' },
  ar: { cashflow: 'الدخل والإنفاق', sixMonths: 'ستة أشهر مالية', income: 'الدخل', spending: 'الإنفاق', net: 'الصافي',
    latest: 'الأحدث', merchants: 'أبرز التجار', change: 'ما الذي تغير', fewer: 'أقل', more: 'أكثر', vs: 'مقارنة مع',
    noMerchants: 'ستظهر اتجاهات التجار بعد إضافة المصروفات.', noChange: 'لا يوجد تغير كبير في الفئات لهذه المقارنة.',
    missingComparison: 'اختر فترة أقصر لعرض المقارنة.', patterns: 'الإنفاق حسب أيام الأسبوع',
    patternsNote: 'المصروفات المسجلة باستثناء الالتزامات الثابتة. ليست توقعات مستقبلية.',
    noData: 'لا توجد حركات مسجلة', records: 'حركات', partial: 'قد يكون الشهر المحدد غير مكتمل.',
    spentLess: 'أقل من', spentMore: 'أكثر من', spentSame: 'تقريباً مثل', byThisDay: 'حتى اليوم نفسه', youSpent: 'أنفقت',
    fixedLeftOut: 'الإيجار والتكاليف الثابتة الأخرى غير محسوبة.', spendingMore: 'إنفاق أكثر', spendingLess: 'إنفاق أقل',
    calendarLegend: 'اللون الأقوى يعني إنفاقاً يومياً أكبر. الإيجار والتكاليف الثابتة غير محسوبة.',
    calendarNoSpend: (n: number) => n === 1 ? 'يوم واحد بلا إنفاق' : n === 2 ? 'يومان بلا إنفاق' : n <= 10 ? `${n} أيام بلا إنفاق` : `${n} يوماً بلا إنفاق`,
    calendarShowing: 'عرض', calendarAll: 'عرض كل الأيام', calendarNothing: 'لا إنفاق', calendarFixedOnly: 'تكاليف ثابتة فقط',
    calendarWeekday: (column: number) => ['ن', 'ث', 'ر', 'خ', 'ج', 'س', 'ح'][column] ?? '' },
};

export const homeSummaryCopy = {
  en: { balance: 'Recorded balances', net: 'Net after spending', notBalance: 'Income minus spending · not your bank balance',
    moneyIn: 'Income', moneyOut: 'Spending', netLabel: 'Net',
    cashflowNote: 'Income minus spending',
    noIncome: 'No income recorded for this period.',
    add: 'Add', import: 'Import', accounts: 'Accounts', settings: 'Settings',
    spending: 'Spending', viewSpending: 'View spending breakdown', income: 'Income this period', period: 'This period', balanceDetail: 'View accounts',
    balanceNote: 'Latest known figures · not a live bank connection',
    today: 'Today', payment: 'payment', payments: 'payments', noPaymentsToday: 'No payments yet',
    leftToSpend: 'Left in budgets', perDay: 'a day',
    daysLeft: (n: number) => `${n} ${n === 1 ? 'day' : 'days'} left`,
    budgetsOver: (n: number) => `${n} ${n === 1 ? 'budget' : 'budgets'} over`,
    dailyAverage: 'Daily average', excludingFixed: 'excluding rent and fixed costs',
    overDays: (n: number) => `over ${n} ${n === 1 ? 'day' : 'days'}`,
    thisWeek: 'Last 7 days', weekTotal: 'Last 7 days, total', opensActivity: 'Opens all transactions',
    weekday: (day: number) => ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'][day] ?? '',
    weekdayFull: (day: number) => ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'][day] ?? '',
    setBudget: 'Set a budget', setBudgetBody: 'Set a monthly budget to see what’s left this period.',
    readyIos: 'Ready for your next bank text', readyAndroid: 'Ready for your next bank alert',
    readyBody: 'When your bank sends an alert for a payment, it appears here.',
    pastTitle: 'Fill in the past', pastImport: 'Import a bank statement', pastImportBody: 'PDF or CSV · brings in past months',
    addByHand: 'Add a transaction', addByHandBody: 'Cash, or anything without a bank alert',
    stoppedIos: (days: number) => `No bank texts for ${days} ${days === 1 ? 'day' : 'days'}`,
    stoppedAndroid: (days: number) => `No bank alerts for ${days} ${days === 1 ? 'day' : 'days'}`,
    rhythmSeveral: 'You usually get several a day.', rhythmDaily: 'You usually get about one a day.',
    rhythmEvery: (days: number) => `You usually get one every ${days} days.`,
    stoppedCauseIos: 'The Shortcuts automation may be off, or an iOS update may have paused it.',
    stoppedCauseAndroid: 'SMS or notification access may have been turned off, or battery settings may be stopping Wafra.',
    checkSetup: 'Check setup', away: 'I was away',
    mayBeHigh: 'May be too high until capture resumes', ask: 'Ask', askHint: 'Opens Ask Wafra',
    transfersToConfirm: (n: number) => `${n} ${n === 1 ? 'transfer' : 'transfers'} to confirm`,
    transfersNotCounted: 'Not counted in spending or income until you confirm.' },
  ar: { balance: 'الأرصدة المسجلة', net: 'الصافي بعد الإنفاق', notBalance: 'الدخل ناقص الإنفاق · ليس رصيد البنك',
    moneyIn: 'الدخل', moneyOut: 'المصروفات', netLabel: 'الصافي',
    cashflowNote: 'الدخل ناقص المصروفات',
    noIncome: 'لا يوجد دخل مسجل لهذه الفترة.',
    add: 'إضافة', import: 'استيراد', accounts: 'الحسابات', settings: 'الإعدادات',
    spending: 'الإنفاق', viewSpending: 'عرض تفاصيل الإنفاق', income: 'الدخل في هذه الفترة', period: 'هذه الفترة', balanceDetail: 'عرض الحسابات',
    balanceNote: 'آخر الأرصدة المعروفة · ليست بيانات مصرفية مباشرة',
    today: 'اليوم', payment: 'دفعة', payments: 'دفعات', noPaymentsToday: 'لا دفعات بعد',
    leftToSpend: 'المتبقي في الميزانيات', perDay: 'يومياً',
    daysLeft: (n: number) => n === 1 ? 'يوم واحد متبقٍ' : n === 2 ? 'يومان متبقيان' : n <= 10 ? `${n} أيام متبقية` : `${n} يوماً متبقياً`,
    budgetsOver: (n: number) => n === 1 ? 'ميزانية واحدة متجاوزة' : n === 2 ? 'ميزانيتان متجاوزتان' : n <= 10 ? `${n} ميزانيات متجاوزة` : `${n} ميزانية متجاوزة`,
    dailyAverage: 'المتوسط اليومي', excludingFixed: 'دون الإيجار والتكاليف الثابتة',
    overDays: (n: number) => n === 1 ? 'خلال يوم واحد' : n === 2 ? 'خلال يومين' : n <= 10 ? `خلال ${n} أيام` : `خلال ${n} يوماً`,
    thisWeek: 'آخر ٧ أيام', weekTotal: 'آخر ٧ أيام، المجموع', opensActivity: 'يفتح كل المعاملات',
    weekday: (day: number) => ['ح', 'ن', 'ث', 'ر', 'خ', 'ج', 'س'][day] ?? '',
    weekdayFull: (day: number) => ['الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'][day] ?? '',
    setBudget: 'حدّد ميزانية', setBudgetBody: 'حدّد ميزانية شهرية لترى المتبقي في هذه الفترة.',
    readyIos: 'جاهز لرسالة البنك التالية', readyAndroid: 'جاهز لتنبيه البنك التالي',
    readyBody: 'عندما يرسل بنكك تنبيهاً بدفعة، ستظهر هنا.',
    pastTitle: 'أكمل ما فات', pastImport: 'استيراد كشف حساب بنكي', pastImportBody: 'PDF أو CSV · يضيف الأشهر السابقة',
    addByHand: 'إضافة معاملة', addByHandBody: 'النقد أو أي دفعة بلا تنبيه من البنك',
    stoppedIos: (days: number) => `لا رسائل من البنك منذ ${arabicDays(days)}`,
    stoppedAndroid: (days: number) => `لا تنبيهات من البنك منذ ${arabicDays(days)}`,
    rhythmSeveral: 'عادةً تصلك عدة رسائل يومياً.', rhythmDaily: 'عادةً تصلك رسالة واحدة تقريباً كل يوم.',
    rhythmEvery: (days: number) => `عادةً تصلك رسالة كل ${arabicDays(days)}.`,
    stoppedCauseIos: 'قد تكون أتمتة الاختصارات متوقفة، أو ربما أوقفها تحديث iOS.',
    stoppedCauseAndroid: 'قد يكون الوصول إلى الرسائل أو الإشعارات متوقفاً، أو قد تمنع إعدادات البطارية وفرة من العمل.',
    checkSetup: 'تحقق من الإعداد', away: 'كنت غائباً',
    mayBeHigh: 'قد يكون أعلى من الحقيقي حتى يُستأنف الالتقاط', ask: 'اسأل', askHint: 'يفتح اسأل وفرة',
    transfersToConfirm: (n: number) => n === 1 ? 'تحويل واحد بحاجة إلى تأكيد' : n === 2 ? 'تحويلان بحاجة إلى تأكيد'
      : n <= 10 ? `${n} تحويلات بحاجة إلى تأكيد` : `${n} تحويلاً بحاجة إلى تأكيد`,
    transfersNotCounted: 'لا تُحتسب في الإنفاق أو الدخل حتى تؤكدها.' },
};

/** Entry detail additions: statement kind, direct transfer marking and the category sheet state. */
export const entryDetailCopy = {
  en: { statementPdf: 'Bank statement (PDF)', statementCsv: 'Bank statement (CSV)', applePay: 'Apple Pay (Wallet)', bankEmail: 'Bank email',
    markTransfer: 'Mark as transfer', markTransferQuestion: 'Mark as a transfer between your accounts?',
    markTransferBody: 'It stays in account balances but no longer counts as spending or income. You can undo this from Edit.',
    chooseCategory: 'Choose a category', done: 'Done' },
  ar: { statementPdf: 'كشف حساب بنكي (PDF)', statementCsv: 'كشف حساب بنكي (CSV)', applePay: 'Apple Pay (المحفظة)', bankEmail: 'بريد البنك',
    markTransfer: 'تحديد كتحويل', markTransferQuestion: 'هل هذا تحويل بين حساباتك؟',
    markTransferBody: 'يبقى في أرصدة الحسابات لكنه لا يُحتسب إنفاقاً أو دخلاً. يمكنك التراجع من «تعديل».',
    chooseCategory: 'اختر فئة', done: 'تم' },
};

/** Category limit sheet: steppers and the three-month picture. */
export const limitSheetCopy = {
  en: { lastMonths: 'Your last 3 months', limitLine: 'Limit', lower: (amount: string) => `Lower by ${amount}`, raise: (amount: string) => `Raise by ${amount}`,
    usual: (amount: string) => `Your usual is about ${amount}.`,
    roomy: 'This limit leaves some room.', tight: 'This limit is close to what you usually spend.', below: 'This limit is below what you usually spend.',
    thisMonth: 'so far', month: (label: string, amount: string) => `${label}, ${amount}` },
  ar: { lastMonths: 'آخر ٣ أشهر', limitLine: 'الحد', lower: (amount: string) => `خفض بمقدار ${amount}`, raise: (amount: string) => `زيادة بمقدار ${amount}`,
    usual: (amount: string) => `إنفاقك المعتاد حوالي ${amount}.`,
    roomy: 'هذا الحد يترك لك بعض المجال.', tight: 'هذا الحد قريب من إنفاقك المعتاد.', below: 'هذا الحد أقل من إنفاقك المعتاد.',
    thisMonth: 'حتى الآن', month: (label: string, amount: string) => `${label}، ${amount}` },
};
