/** Localized presentation vocabulary shared by the approved redesign. */

export const paymentAgendaCopy = {
  en: { overdue: 'Past due', 'expected-earlier': 'Expected earlier', soon: 'Next 7 days', later: 'Later', paid: 'Recently paid',
    estimate: 'Estimated', recorded: 'Paid · due', statement: 'Statement due', empty: 'Nothing coming up',
    emptyBody: 'Add a bill reminder or import your bank alerts. Wafra will show the dates it can verify.',
    note: 'Reminders, not payments', noteBody: 'Marking something paid only updates Wafra. No payment is sent.',
    today: 'Today', tomorrow: 'Tomorrow', paidStatement: 'Paid statement · due',
    subscriptions: 'Subscriptions', utilities: 'Utilities & telecom', cards: 'Card payments', loans: 'Loan repayments', other: 'Other bills',
    subscriptionsHint: 'Recurring memberships and services', utilitiesHint: 'Electricity, water, phone and internet',
    emptySubscriptions: 'No subscription renewals to show.', emptyUtilities: 'No utility bills to show.',
    emptyCards: 'No credit-card payments to show.', emptyLoans: 'No loan repayments to show.', emptyOther: 'No other bills to show.',
    showMore: (count: number) => `Show ${count} more` },
  ar: { overdue: 'متأخرة', 'expected-earlier': 'كانت متوقعة سابقاً', soon: 'خلال 7 أيام', later: 'لاحقاً', paid: 'مدفوعة مؤخراً',
    estimate: 'تقديري', recorded: 'مدفوعة · استحقاقها', statement: 'استحقاق الكشف', empty: 'لا توجد دفعات قادمة',
    emptyBody: 'أضف تذكيراً بفاتورة أو استورد تنبيهات البنك لعرض التواريخ المعروفة.',
    note: 'تذكيرات وليست خدمة دفع', noteBody: 'وضع علامة «مدفوع» يحدّث وفرة فقط. لا يتم إرسال أي دفعة.',
    today: 'اليوم', tomorrow: 'غداً', paidStatement: 'كشف مدفوع · استحقاقه',
    subscriptions: 'الاشتراكات', utilities: 'المرافق والاتصالات', cards: 'دفعات البطاقات', loans: 'أقساط القروض', other: 'فواتير أخرى',
    subscriptionsHint: 'العضويات والخدمات المتكررة', utilitiesHint: 'الكهرباء والمياه والهاتف والإنترنت',
    emptySubscriptions: 'لا توجد تجديدات اشتراكات لعرضها.', emptyUtilities: 'لا توجد فواتير مرافق لعرضها.',
    emptyCards: 'لا توجد دفعات بطاقات ائتمانية لعرضها.', emptyLoans: 'لا توجد أقساط قروض لعرضها.', emptyOther: 'لا توجد فواتير أخرى لعرضها.',
    showMore: (count: number) => `عرض ${count} أخرى` },
};

export const accountGroupsCopy = {
  en: { bank: 'Bank accounts', credit: 'Credit cards', debit: 'Other cards', cash: 'Cash',
    unknown: 'No recorded figure', manage: 'Manage account', empty: 'No accounts yet',
    sourceNote: 'Your accounts, clearly separated', sourceBody: 'Recorded balances are not a live bank connection. Credit-card dues are shown separately.' },
  ar: { bank: 'الحسابات المصرفية', credit: 'البطاقات الائتمانية', debit: 'بطاقات أخرى', cash: 'النقد',
    unknown: 'لا يوجد مبلغ مسجل', manage: 'إدارة الحساب', empty: 'لا توجد حسابات بعد',
    sourceNote: 'حساباتك بوضوح', sourceBody: 'الأرصدة المسجلة ليست اتصالاً مباشراً بالبنك. تظهر استحقاقات البطاقات الائتمانية منفصلة.' },
};

export const spendingCopy = {
  en: { categories: 'Categories', activity: 'Activity', trends: 'Trends', spent: 'Total spent',
    limited: 'Categories with limits', of: 'of', all: 'All', withLimits: 'With limits', noLimits: 'No limits',
    noLimit: 'No limit set', setLimit: 'Set monthly limit', manage: 'Edit monthly limit', monthlyOnly: 'Category limits are monthly. Choose a month to view them.',
    empty: 'No spending in this period', emptyBody: 'Add an expense or import bank alerts to see your categories here.',
    emptyFilter: 'No categories match this filter', left: 'left', over: 'over limit',
    details: 'View transactions', newLimit: 'New category limit', search: 'Search spending', allActivity: 'View all spending',
    noResults: 'No matching expenses', searchHint: 'Search by merchant or account',
    summaryNote: 'Only categories with a limit are included below.', used: 'used', month: 'This period',
    breakdown: 'Where it went', share: 'of spending', shareNote: 'Each category’s share of total spending', otherCategories: 'Other categories', budgetUsed: 'of limit used',
    lastSixMonths: 'Last 6 months', average: 'Avg', latest: 'Latest', vs: 'vs', askWafra: 'Ask Wafra', explain: 'Explain this',
    aboveAverage: (percent: number) => `Current total is ${percent}% above the 6-month average.`,
    belowAverage: (percent: number) => `Current total is ${percent}% below the 6-month average.`,
    nearAverage: 'Current total is close to the 6-month average.' },
  ar: { categories: 'الفئات', activity: 'الحركات', trends: 'الاتجاهات', spent: 'إجمالي الإنفاق',
    limited: 'الفئات ذات الحدود', of: 'من', all: 'الكل', withLimits: 'بحد إنفاق', noLimits: 'بلا حد',
    noLimit: 'لا يوجد حد محدد', setLimit: 'تحديد حد شهري', manage: 'تعديل الحد الشهري', monthlyOnly: 'حدود الفئات شهرية. اختر شهراً لعرضها.',
    empty: 'لا يوجد إنفاق في هذه الفترة', emptyBody: 'أضف مصروفاً أو استورد تنبيهات البنك لعرض الفئات هنا.',
    emptyFilter: 'لا توجد فئات مطابقة', left: 'متبقٍ', over: 'فوق الحد',
    details: 'عرض العمليات', newLimit: 'حد إنفاق جديد', search: 'البحث في المصروفات', allActivity: 'عرض كل المصروفات',
    noResults: 'لا توجد مصروفات مطابقة', searchHint: 'ابحث باسم التاجر أو الحساب',
    summaryNote: 'يشمل المؤشر أدناه الفئات التي لها حد فقط.', used: 'مستخدم', month: 'هذه الفترة',
    breakdown: 'أين أنفقت', share: 'من الإنفاق', shareNote: 'حصة كل فئة من إجمالي الإنفاق', otherCategories: 'فئات أخرى', budgetUsed: 'من الحد مستخدم',
    lastSixMonths: 'آخر ٦ أشهر', average: 'المتوسط', latest: 'الأحدث', vs: 'مقابل', askWafra: 'اسأل وفرة', explain: 'اشرح هذا',
    aboveAverage: (percent: number) => `الإجمالي الحالي أعلى من متوسط ٦ أشهر بنسبة ${percent}٪.`,
    belowAverage: (percent: number) => `الإجمالي الحالي أقل من متوسط ٦ أشهر بنسبة ${percent}٪.`,
    nearAverage: 'الإجمالي الحالي قريب من متوسط ٦ أشهر.' },
} as const;

export const spendingTrendsCopy = {
  en: { cashflow: 'Income & spending', sixMonths: 'Six money months', income: 'Income', spending: 'Spending', net: 'Net',
    latest: 'Latest', merchants: 'Top merchants', change: 'What changed', fewer: 'Less', more: 'More', vs: 'Compared with',
    noMerchants: 'Merchant trends will appear after you add spending.', noChange: 'No material category change for this comparison.',
    missingComparison: 'Choose a shorter period for a comparable view.', patterns: 'Spending by weekday',
    patternsNote: 'Recorded spending, excluding fixed commitments. This is not a forecast.',
    noData: 'No recorded activity', records: 'transactions', partial: 'The selected month may be incomplete.',
    spentLess: 'less than', spentMore: 'more than', spentSame: 'About the same as', byThisDay: 'by this day', youSpent: 'You’ve spent',
    fixedLeftOut: 'Rent and other fixed costs are left out.', spendingMore: 'Spending more', spendingLess: 'Spending less' },
  ar: { cashflow: 'الدخل والإنفاق', sixMonths: 'ستة أشهر مالية', income: 'الدخل', spending: 'الإنفاق', net: 'الصافي',
    latest: 'الأحدث', merchants: 'أبرز التجار', change: 'ما الذي تغير', fewer: 'أقل', more: 'أكثر', vs: 'مقارنة مع',
    noMerchants: 'ستظهر اتجاهات التجار بعد إضافة المصروفات.', noChange: 'لا يوجد تغير كبير في الفئات لهذه المقارنة.',
    missingComparison: 'اختر فترة أقصر لعرض المقارنة.', patterns: 'الإنفاق حسب أيام الأسبوع',
    patternsNote: 'المصروفات المسجلة باستثناء الالتزامات الثابتة. ليست توقعات مستقبلية.',
    noData: 'لا توجد حركات مسجلة', records: 'حركات', partial: 'قد يكون الشهر المحدد غير مكتمل.',
    spentLess: 'أقل من', spentMore: 'أكثر من', spentSame: 'تقريباً مثل', byThisDay: 'حتى اليوم نفسه', youSpent: 'أنفقت',
    fixedLeftOut: 'الإيجار والتكاليف الثابتة الأخرى غير محسوبة.', spendingMore: 'إنفاق أكثر', spendingLess: 'إنفاق أقل' },
};

export const homeSummaryCopy = {
  en: { balance: 'Recorded balances', net: 'Net after spending', notBalance: 'Income minus spending · not your bank balance',
    moneyIn: 'Income', moneyOut: 'Spending', netLabel: 'Net',
    cashflowNote: 'Income minus spending',
    noIncome: 'No income recorded for this period.',
    add: 'Add', import: 'Import', accounts: 'Accounts', settings: 'Settings',
    spending: 'Spending', viewSpending: 'View spending breakdown', income: 'Income this period', period: 'This period', balanceDetail: 'View accounts',
    balanceNote: 'Latest known figures · not a live bank connection',
    today: 'Today', payment: 'payment', payments: 'payments', noPaymentsToday: 'No payments yet',
    leftToSpend: 'Left in budgets', perDay: 'a day',
    daysLeft: (n: number) => `${n} ${n === 1 ? 'day' : 'days'} left`,
    budgetsOver: (n: number) => `${n} ${n === 1 ? 'budget' : 'budgets'} over`,
    dailyAverage: 'Daily average', excludingFixed: 'excluding rent and fixed costs',
    overDays: (n: number) => `over ${n} ${n === 1 ? 'day' : 'days'}`,
    thisWeek: 'Last 7 days', weekTotal: 'Last 7 days, total', opensActivity: 'Opens all transactions',
    weekday: (day: number) => ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'][day] ?? '' },
  ar: { balance: 'الأرصدة المسجلة', net: 'الصافي بعد الإنفاق', notBalance: 'الدخل ناقص الإنفاق · ليس رصيد البنك',
    moneyIn: 'الدخل', moneyOut: 'المصروفات', netLabel: 'الصافي',
    cashflowNote: 'الدخل ناقص المصروفات',
    noIncome: 'لا يوجد دخل مسجل لهذه الفترة.',
    add: 'إضافة', import: 'استيراد', accounts: 'الحسابات', settings: 'الإعدادات',
    spending: 'الإنفاق', viewSpending: 'عرض تفاصيل الإنفاق', income: 'الدخل في هذه الفترة', period: 'هذه الفترة', balanceDetail: 'عرض الحسابات',
    balanceNote: 'آخر الأرصدة المعروفة · ليست بيانات مصرفية مباشرة',
    today: 'اليوم', payment: 'دفعة', payments: 'دفعات', noPaymentsToday: 'لا دفعات بعد',
    leftToSpend: 'المتبقي في الميزانيات', perDay: 'يومياً',
    daysLeft: (n: number) => n === 1 ? 'يوم واحد متبقٍ' : n === 2 ? 'يومان متبقيان' : n <= 10 ? `${n} أيام متبقية` : `${n} يوماً متبقياً`,
    budgetsOver: (n: number) => n === 1 ? 'ميزانية واحدة متجاوزة' : n === 2 ? 'ميزانيتان متجاوزتان' : n <= 10 ? `${n} ميزانيات متجاوزة` : `${n} ميزانية متجاوزة`,
    dailyAverage: 'المتوسط اليومي', excludingFixed: 'دون الإيجار والتكاليف الثابتة',
    overDays: (n: number) => n === 1 ? 'خلال يوم واحد' : n === 2 ? 'خلال يومين' : n <= 10 ? `خلال ${n} أيام` : `خلال ${n} يوماً`,
    thisWeek: 'آخر ٧ أيام', weekTotal: 'آخر ٧ أيام، المجموع', opensActivity: 'يفتح كل المعاملات',
    weekday: (day: number) => ['ح', 'ن', 'ث', 'ر', 'خ', 'ج', 'س'][day] ?? '' },
};
