export const SUPPLEMENT_COPY = {
  en: {
    header: 'STATEMENTS & EMAIL',
    title: 'Backfill without typing',
    introAndroid: 'SMS stays on this phone. These optional imports use Wafra’s secure relay only when you choose them.',
    introIos: 'Shortcut capture stays automatic. Use these for statements and bank emails it cannot see.',
    privateTitle: 'Cloud imports are off in Private Mode',
    privateBody: 'Your Android SMS tracking still runs on-device. Turn Private Mode off to import a PDF or forwarded email.',
    connectTitle: 'Connect secure import',
    connectBody: 'Creates a device-only key and a private relay connection. No Wafra account is required.',
    connect: 'Connect',
    connecting: 'Connecting…',
    unavailable: 'This build has no import service configured.',
    retry: 'Retry',
    checking: 'Checking support…',
    serviceError: 'Could not verify the import service. Nothing was uploaded.',
    pdfTitle: 'PDF statement',
    pdfBody: 'Original text PDF with dated rows and an explicit DR/CR or debit/credit marker.',
    pdfLimits: 'Up to {mb} MB · {pages} pages · {rows} rows',
    choosePdf: 'Choose PDF',
    uploading: 'Reading statement…',
    pdfSuccess: '{accepted} rows read across {pages} pages · {imported} new',
    pdfNoNew: '{accepted} rows read · everything was already in your ledger',
    emailTitle: 'Forwarded bank email',
    emailBody: 'Forward a bank alert or statement from your email app to one private Wafra address.',
    createAddress: 'Create private address',
    creatingAddress: 'Creating address…',
    copyAddress: 'Copy address',
    copied: 'Copied · clipboard clears in 60 seconds',
    checkEmail: 'Check for imports',
    checkingEmail: 'Checking…',
    emailSuccess: '{imported} new transactions filed',
    emailNoNew: 'No new supported bank transactions found',
    revoke: 'Revoke address',
    revokeTitle: 'Revoke forwarding address?',
    revokeBody: 'Emails sent to this address will stop importing. Your iPhone Shortcut connection stays intact.',
    revoking: 'Revoking…',
    oldConnection: 'Create a private address for this existing connection.',
    privacyTitle: 'Raw body is not kept',
    privacyBody: 'The relay parses in memory, seals only structured rows to this device, then discards the PDF or email body. Unsupported files are rejected, never guessed.',
    notHydrated: 'Your encrypted ledger is still loading. Try again in a moment.',
    errNetwork: 'Could not reach Wafra. Nothing was imported; check your connection and retry.',
    errAuth: 'This secure connection expired. Disconnect and reconnect Wafra capture.',
    errInvalid: 'That file is not a valid PDF.',
    errLarge: 'That statement exceeds the supported file, page, or row limit.',
    errUnreadable: 'Wafra could not read this PDF. Password-protected and scanned PDFs are not supported.',
    errFormat: 'This statement does not label rows as DR/CR or debit/credit, so Wafra will not guess.',
    errRate: 'Too many imports were requested. Wait a moment and retry.',
    errEmailOff: 'Forwarded email is not enabled on this Wafra service yet.',
    errUnexpected: 'The import service returned an unexpected response. Nothing was filed.',
    acceptedPending: '{accepted} rows reached Wafra, but could not sync to this phone yet. Tap “Check for imports” to retry.',
  },
  ar: {
    header: 'الكشوف والبريد',
    title: 'استورد دون كتابة',
    introAndroid: 'تبقى الرسائل النصية على هاتفك. تستخدم هذه الواردات الاختيارية خدمة وفرة الآمنة فقط عند اختيارك.',
    introIos: 'يبقى الالتقاط عبر الاختصار تلقائياً. استخدم هذه الطرق للكشوف ورسائل البنك التي لا يراها الاختصار.',
    privateTitle: 'الواردات السحابية متوقفة في الوضع الخاص',
    privateBody: 'يستمر تتبع رسائل أندرويد على الجهاز. أوقف الوضع الخاص لاستيراد ملف PDF أو بريد محوّل.',
    connectTitle: 'ربط الاستيراد الآمن',
    connectBody: 'ينشئ مفتاحاً خاصاً بالجهاز واتصالاً مشفراً. لا تحتاج إلى حساب وفرة.',
    connect: 'ربط',
    connecting: 'جارٍ الربط…',
    unavailable: 'خدمة الاستيراد غير مهيأة في هذا الإصدار.',
    retry: 'إعادة المحاولة',
    checking: 'جارٍ التحقق من الدعم…',
    serviceError: 'تعذّر التحقق من خدمة الاستيراد. لم يُرفع شيء.',
    pdfTitle: 'كشف حساب PDF',
    pdfBody: 'ملف PDF نصي أصلي بصفوف مؤرخة وعلامة DR/CR أو مدين/دائن واضحة.',
    pdfLimits: 'حتى {mb} م.ب · {pages} صفحة · {rows} صف',
    choosePdf: 'اختيار PDF',
    uploading: 'جارٍ قراءة الكشف…',
    pdfSuccess: 'قُرئ {accepted} صفاً في {pages} صفحة · {imported} جديد',
    pdfNoNew: 'قُرئ {accepted} صفاً · كلها موجودة في سجلك',
    emailTitle: 'بريد البنك المحوّل',
    emailBody: 'حوّل تنبيه بنك أو كشف حساب من تطبيق البريد إلى عنوان وفرة خاص واحد.',
    createAddress: 'إنشاء عنوان خاص',
    creatingAddress: 'جارٍ إنشاء العنوان…',
    copyAddress: 'نسخ العنوان',
    copied: 'تم النسخ · تُمسح الحافظة خلال ٦٠ ثانية',
    checkEmail: 'التحقق من الواردات',
    checkingEmail: 'جارٍ التحقق…',
    emailSuccess: 'أُضيفت {imported} عملية جديدة',
    emailNoNew: 'لا توجد عمليات بنكية جديدة مدعومة',
    revoke: 'إلغاء العنوان',
    revokeTitle: 'إلغاء عنوان التحويل؟',
    revokeBody: 'سيتوقف استيراد الرسائل المرسلة إليه. سيبقى اتصال اختصار الآيفون كما هو.',
    revoking: 'جارٍ الإلغاء…',
    oldConnection: 'أنشئ عنواناً خاصاً لهذا الاتصال الحالي.',
    privacyTitle: 'لا نحتفظ بالمحتوى الخام',
    privacyBody: 'تُحلّل الخدمة الملف في الذاكرة وتشفّر الصفوف المنظمة لهذا الجهاز ثم تتخلص من ملف PDF أو نص البريد. تُرفض الملفات غير المدعومة ولا نخمن بياناتها.',
    notHydrated: 'لا يزال سجلك المشفر قيد التحميل. حاول بعد لحظة.',
    errNetwork: 'تعذّر الوصول إلى وفرة. لم يُستورد شيء؛ تحقق من الاتصال وحاول مجدداً.',
    errAuth: 'انتهت صلاحية الاتصال الآمن. افصل التقاط وفرة وأعد ربطه.',
    errInvalid: 'هذا الملف ليس PDF صالحاً.',
    errLarge: 'يتجاوز الكشف حد حجم الملف أو عدد الصفحات أو الصفوف.',
    errUnreadable: 'تعذّرت قراءة الملف. لا ندعم ملفات PDF المصورة أو المحمية بكلمة مرور.',
    errFormat: 'لا يوضح الكشف الصفوف كمدين/دائن أو DR/CR، لذلك لن يخمن وفرة.',
    errRate: 'طُلبت واردات كثيرة. انتظر قليلاً ثم حاول مجدداً.',
    errEmailOff: 'تحويل البريد غير مفعّل على خدمة وفرة بعد.',
    errUnexpected: 'أعادت خدمة الاستيراد استجابة غير متوقعة. لم تُسجّل أي عملية.',
    acceptedPending: 'وصل {accepted} صفاً إلى وفرة لكن لم تتزامن مع الهاتف بعد. اضغط «التحقق من الواردات» للمحاولة.',
  },
} as const;
