export const SUPPLEMENT_COPY = {
  en: {
    header: 'STATEMENTS',
    title: 'Import statement history',
    introAndroid: 'Add older bank history from PDF, CSV, or TSV statements. Wafra keeps track of the months you have already added.',
    introIos: 'Shortcut capture stays automatic. Add older history from PDF, CSV, or TSV statements and track which months are covered.',
    privateTitle: 'Cloud imports are paused',
    reviewPrivacy: 'Review saved preference',
    privateBody: 'Local capture still works. Review your saved local-only choice in Settings → Privacy and data to use cloud imports.',
    connectTitle: 'Connect secure import',
    connectBody: 'Creates a device-only key and a private relay connection. No Wafra account is required.',
    connect: 'Connect',
    connecting: 'Connecting…',
    unavailable: 'This build has no import service configured.',
    retry: 'Retry',
    checking: 'Checking support…',
    serviceError: 'Could not verify the import service. Nothing was uploaded.',
    statementTitle: 'Import bank statement history',
    statementBody: 'Choose one or several PDF, CSV, or TSV statements. Wafra imports them in order and reconciles supported accounts, cards, and transactions.',
    statementLimits: 'PDF {pdfMb} MB / {pages} pages · CSV or TSV {csvMb} MB · {rows} rows',
    chooseStatement: 'Choose statement',
    chooseStatements: 'Choose statements',
    uploading: 'Reading statement…',
    passwordTitle: 'This PDF needs a password',
    passwordBody: 'Enter the statement password. It is used once to open this file, then cleared.',
    passwordLabel: 'PDF password',
    passwordPlaceholder: 'Enter password',
    passwordRetry: 'Unlock & import',
    passwordCancel: 'Cancel',
    passwordWrong: 'That password did not open the PDF. Try again.',
    coverageTitle: 'Statement coverage',
    coverageEmpty: 'Import a statement and Wafra will remember which months are covered.',
    coverageImported: '{range} imported',
    coverageComplete: 'No gaps through {month}',
    coverageMissing: 'Missing: {months}',
    statementsSuccess: '{files} statements · {accepted} rows read · {rejected} skipped · {imported} new',
    statementsNoNew: '{files} statements · {accepted} rows read · everything supported was already in your ledger',
    pdfSuccess: '{accepted} rows read across {pages} pages · {imported} new',
    pdfNoNew: '{accepted} rows read · everything was already in your ledger',
    csvSuccess: '{accepted} rows read · {rejected} skipped · {imported} new',
    csvNoNew: '{accepted} rows read · {rejected} skipped · no new ledger rows',
    privacyTitle: 'Raw body is not kept',
    privacyBody: 'The relay parses the statement in memory, seals only structured rows to this device, then discards the file. PDF passwords are used only to open that upload and are not saved by Wafra.',
    notHydrated: 'Your encrypted ledger is still loading. Try again in a moment.',
    errNetwork: 'Could not reach Wafra. Nothing was imported; check your connection and retry.',
    errAuth: 'This secure connection expired. Disconnect and reconnect Wafra capture.',
    errInvalid: 'That file is not a valid supported statement.',
    errLarge: 'That statement exceeds the supported file, page, or row limit.',
    errUnreadable: 'Wafra could not read this PDF. Scanned/image-only PDFs are not supported yet.',
    errFormat: 'This statement lacks supported date, description, and explicit debit/credit fields, so Wafra will not guess.',
    errRate: 'Too many imports were requested. Wait a moment and retry.',
    errUnexpected: 'The import service returned an unexpected response. Nothing was filed.',
    acceptedPending: '{accepted} rows reached Wafra but could not sync to this phone yet. Try again in a moment.',
  },
  ar: {
    header: 'الكشوف',
    title: 'استيراد سجل الكشوف',
    introAndroid: 'أضف السجل البنكي القديم من كشوف PDF أو CSV أو TSV. يتتبع وفرة الأشهر التي أضفتها بالفعل.',
    introIos: 'يبقى الالتقاط عبر الاختصار تلقائياً. أضف السجل القديم من كشوف PDF أو CSV أو TSV وتابع الأشهر المغطاة.',
    privateTitle: 'الواردات السحابية متوقفة مؤقتاً',
    reviewPrivacy: 'مراجعة التفضيل المحفوظ',
    privateBody: 'يستمر الالتقاط المحلي. راجع اختيارك المحفوظ في الإعدادات ← الخصوصية والبيانات لاستخدام الاستيراد السحابي.',
    connectTitle: 'ربط الاستيراد الآمن',
    connectBody: 'ينشئ مفتاحاً خاصاً بالجهاز واتصالاً مشفراً. لا تحتاج إلى حساب وفرة.',
    connect: 'ربط',
    connecting: 'جارٍ الربط…',
    unavailable: 'خدمة الاستيراد غير مهيأة في هذا الإصدار.',
    retry: 'إعادة المحاولة',
    checking: 'جارٍ التحقق من الدعم…',
    serviceError: 'تعذّر التحقق من خدمة الاستيراد. لم يُرفع شيء.',
    statementTitle: 'استيراد سجل كشوف البنك',
    statementBody: 'اختر كشفاً واحداً أو عدة كشوف PDF أو CSV أو TSV. يستوردها وفرة بالترتيب ويطابق الحسابات والبطاقات والعمليات المدعومة.',
    statementLimits: 'PDF ‏{pdfMb} م.ب / {pages} صفحة · CSV أو TSV ‏{csvMb} م.ب · {rows} صف',
    chooseStatement: 'اختيار كشف',
    chooseStatements: 'اختيار كشوف',
    uploading: 'جارٍ قراءة الكشف…',
    passwordTitle: 'ملف PDF يحتاج كلمة مرور',
    passwordBody: 'أدخل كلمة مرور الكشف. تُستخدم مرة واحدة لفتح الملف ثم تُمسح.',
    passwordLabel: 'كلمة مرور PDF',
    passwordPlaceholder: 'أدخل كلمة المرور',
    passwordRetry: 'فتح واستيراد',
    passwordCancel: 'إلغاء',
    passwordWrong: 'كلمة المرور لم تفتح الملف. حاول مرة أخرى.',
    coverageTitle: 'تغطية الكشوف',
    coverageEmpty: 'استورد كشفاً وسيتذكر وفرة الأشهر التي تمت تغطيتها.',
    coverageImported: 'تم استيراد {range}',
    coverageComplete: 'لا توجد فجوات حتى {month}',
    coverageMissing: 'الناقص: {months}',
    statementsSuccess: '{files} كشوف · قُرئ {accepted} صفاً · تم تجاوز {rejected} · {imported} جديد',
    statementsNoNew: '{files} كشوف · قُرئ {accepted} صفاً · كل العمليات المدعومة موجودة في سجلك',
    pdfSuccess: 'قُرئ {accepted} صفاً في {pages} صفحة · {imported} جديد',
    pdfNoNew: 'قُرئ {accepted} صفاً · كلها موجودة في سجلك',
    csvSuccess: 'قُرئ {accepted} صفاً · تم تجاوز {rejected} · {imported} جديد',
    csvNoNew: 'قُرئ {accepted} صفاً · تم تجاوز {rejected} · لا توجد صفوف جديدة',
    privacyTitle: 'لا نحتفظ بالمحتوى الخام',
    privacyBody: 'تُحلّل الخدمة الكشف في الذاكرة وتشفّر الصفوف المنظمة لهذا الجهاز ثم تتخلص من الملف. تُستخدم كلمة مرور PDF لفتح هذا الرفع فقط ولا يحفظها وفرة.',
    notHydrated: 'لا يزال سجلك المشفر قيد التحميل. حاول بعد لحظة.',
    errNetwork: 'تعذّر الوصول إلى وفرة. لم يُستورد شيء؛ تحقق من الاتصال وحاول مجدداً.',
    errAuth: 'انتهت صلاحية الاتصال الآمن. افصل التقاط وفرة وأعد ربطه.',
    errInvalid: 'هذا الملف ليس كشفاً صالحاً ومدعوماً.',
    errLarge: 'يتجاوز الكشف حد حجم الملف أو عدد الصفحات أو الصفوف.',
    errUnreadable: 'تعذّرت قراءة ملف PDF. ملفات PDF المصورة فقط غير مدعومة حالياً.',
    errFormat: 'يفتقد الكشف حقول التاريخ والوصف واتجاه مدين/دائن المدعومة، لذلك لن يخمن وفرة.',
    errRate: 'طُلبت واردات كثيرة. انتظر قليلاً ثم حاول مجدداً.',
    errUnexpected: 'أعادت خدمة الاستيراد استجابة غير متوقعة. لم تُسجّل أي عملية.',
    acceptedPending: 'وصل {accepted} صفاً إلى وفرة لكن لم تتزامن مع الهاتف بعد. حاول مرة أخرى بعد لحظة.',
  },
} as const;
