import { getLanguage } from '@/lib/i18n';

const en = {
  title: 'Transfers',
  intro: 'Money moving between your accounts or to and from someone else.',
  recordsNote: 'Each bank record stays available. Both sides of a transfer may appear here; they are not added together as spending.',
  search: 'Search transfers',
  searchPlaceholder: 'Description or account',
  all: 'All',
  confirmed: 'Confirmed',
  unconfirmedScope: 'Not confirmed',
  own: 'Between your accounts',
  external: 'With someone else',
  unconfirmed: 'Ownership not confirmed',
  needsReview: 'Ownership needs review',
  incoming: 'Received',
  outgoing: 'Sent',
  review: 'Review ownership',
  empty: 'No transfers in this view',
  emptyBody: 'Try another period or search. Transfers appear here instead of the regular transaction list.',
  accountUnknown: 'Account not identified',
  viewAll: 'View all transfers',
  viewDetails: 'View transfer details',
  netIncluding: 'Net including transfers',
  transferIncome: 'Transfer income',
  transferSpending: 'Transfer spending',
  records: (count: number) => `${count} transfer record${count === 1 ? '' : 's'}`,
  separated: (count: number) => `${count} transfer record${count === 1 ? ' is' : 's are'} shown separately.`,
  reviewNote: 'Some of these transfers need an ownership review in Transfers.',
  countsNote: 'Transfers with other people still count toward income or spending. The net above includes them.',
  activityCountsNote: 'Transfers with other people still count toward spending totals.',
  walletDetail: 'Browse transfers and check ownership',
};

const ar: typeof en = {
  title: 'التحويلات',
  intro: 'حركة الأموال بين حساباتك أو من وإلى أشخاص آخرين.',
  recordsNote: 'يبقى كل سجل بنكي متاحاً. قد يظهر طرفا التحويل هنا، ولا يُجمعان كمصروفات.',
  search: 'البحث في التحويلات',
  searchPlaceholder: 'الوصف أو الحساب',
  all: 'الكل',
  confirmed: 'مؤكدة',
  unconfirmedScope: 'غير مؤكدة',
  own: 'بين حساباتك',
  external: 'مع شخص آخر',
  unconfirmed: 'الملكية غير مؤكدة',
  needsReview: 'الملكية تحتاج مراجعة',
  incoming: 'مستلم',
  outgoing: 'مرسل',
  review: 'مراجعة الملكية',
  empty: 'لا توجد تحويلات في هذا العرض',
  emptyBody: 'جرّب فترة أو بحثاً آخر. تظهر التحويلات هنا بدلاً من قائمة المعاملات العادية.',
  accountUnknown: 'الحساب غير محدد',
  viewAll: 'عرض كل التحويلات',
  viewDetails: 'عرض تفاصيل التحويل',
  netIncluding: 'الصافي شاملاً التحويلات',
  transferIncome: 'دخل التحويلات',
  transferSpending: 'مصروفات التحويلات',
  records: (count) => `${count} من سجلات التحويل`,
  separated: (count) => `تُعرض ${count} من سجلات التحويل بشكل منفصل.`,
  reviewNote: 'بعض هذه التحويلات تحتاج إلى مراجعة الملكية في التحويلات.',
  countsNote: 'تبقى التحويلات مع الآخرين ضمن الدخل أو المصروفات. ويشملها الصافي أعلاه.',
  activityCountsNote: 'تبقى التحويلات مع الآخرين ضمن إجمالي المصروفات.',
  walletDetail: 'تصفح التحويلات وراجع الملكية',
};

export function transferActivityCopy(language = getLanguage()) {
  return language === 'ar' ? ar : en;
}
