import { getLanguage } from '@/lib/i18n';

const en = {
  title: 'Transfers',
  back: 'Back',
  pending: 'Unclassified',
  reviewed: 'Confirmed',
  noticeTitle: (_count: number) => 'Transfers kept separate',
  noticeBody: 'Unclassified transfers are excluded from income, spending and Net.',
  noticeCount: (count: number) => `${count.toLocaleString('en-US')} unclassified · Not included in totals`,
  intro: 'No need to work through your history. Classify only transfers you recognise; the rest stay separate from income and spending.',
  reviewedIntro: 'Transfers confirmed by bank evidence or your choice. Review an automatic match, or undo your choice to change it.',
  moneyIn: 'Money in',
  moneyOut: 'Money out',
  count: (count: number) => `${count} entr${count === 1 ? 'y' : 'ies'}`,
  accountUnknown: 'Account unavailable',
  counterpartyUnknown: 'Counterparty not identified',
  accountEnding: (last4: string) => `Account ending ${last4}`,
  cardEnding: (last4: string) => `Card ending ${last4}`,
  review: 'Classify transfer',
  reviewGroup: (count: number) => `Classify these ${count} transfers`,
  individualOnly: 'These share an account, not a confirmed recipient. Leave them unclassified unless you recognise an entry.',
  recent: 'Last 90 days',
  allHistory: 'All history',
  newestFirst: 'Newest first',
  search: 'Search account, name or amount',
  clearSearch: 'Clear search',
  historyAvailable: (count: number) => `${count.toLocaleString('en-US')} more in All history`,
  shown: (count: number, groups: number) => `${count.toLocaleString('en-US')} transfers · ${groups.toLocaleString('en-US')} groups`,
  expand: (count: number) => `Show ${count.toLocaleString('en-US')} transfers`,
  collapse: 'Hide transfers',
  more: (shown: number, count: number) => `Show more · ${shown.toLocaleString('en-US')} of ${count.toLocaleString('en-US')}`,
  recentEmpty: 'No unclassified transfers in the last 90 days',
  searchEmpty: 'No matches in this view',
  searchEmptyBody: 'Try another name or amount, or switch to All history.',
  sent: 'Sent',
  received: 'Received',
  reference: 'Bank reference',
  bankRecord: 'Recorded bank alert',
  manualRecord: 'Manual entry',
  keepSeparate: 'Leave unclassified',
  own: 'Between my own accounts',
  ownBody: 'Exclude these amounts from income and spending. They stay recorded as account movements.',
  externalIn: 'Money received from someone else',
  externalOut: 'Paid someone else',
  externalInBody: 'Include this money in income and Net.',
  externalOutBody: 'Include this payment in spending and Net.',
  choose: 'What was this transfer?',
  groupChoose: 'Do all these transfers have the same purpose?',
  groupHint: 'Confirm only if this choice applies to every entry shown in the count and total.',
  confirm: 'Save classification',
  saving: 'Saving…',
  saved: 'Classification saved',
  cancel: 'Cancel',
  undo: 'Undo decision',
  undoTitle: 'Return this entry to review?',
  undoBody: 'Remove your saved classification. Wafra will reassess the available evidence; unresolved amounts stay outside confirmed income, spending and Net.',
  undone: 'Decision removed',
  changed: 'These entries changed while you were reviewing them. Close this panel and open them again to review the latest details.',
  saveFailed: 'Could not save this decision. Close this panel and review the latest details before trying again.',
  durabilityFailed: 'Your decision is applied on this screen but has not been safely saved. Retry saving before leaving this panel.',
  retrySave: 'Retry saving',
  empty: 'No unclassified transfers in this view',
  emptyBody: 'Older transfers remain available in All history. Nothing is deleted or classified by changing this view.',
  reviewedEmpty: 'No confirmed transfers in this view',
  reviewedEmptyBody: 'Confirmed transfers will appear here so you can review them again.',
  missingRoute: 'This entry is no longer available for transfer review.',
  notPending: 'This entry has no pending ownership decision.',
  showAll: 'Show all transfers',
  ownershipUnknown: 'Unclassified transfer',
  ambiguous: 'More than one possible match',
  counterpartMissing: 'Other account entry not found',
  confirmedOwn: 'Between your accounts',
  confirmedExternal: 'With someone else',
  cardRepayment: 'Credit-card repayment',
  corroborating: 'Extra bank confirmation · not counted twice',
  likelyOwn: 'Possible transfer between your accounts',
  likelyCard: 'Possible credit-card repayment',
  suggestedOnly: 'Matching amount and timing are a suggestion, not confirmed ownership.',
  knownAccountEvidence: 'Recognised automatically: other bank SMS identify this account as yours. No matching receipt is required for ownership.',
  knownCardEvidence: 'Recognised automatically: other bank SMS identify the receiving credit card as yours. The bank payment is recorded; a card receipt has not been linked.',
  linkedEntry: 'Matching bank entry',
  linkOwn: 'Confirm and link both entries',
  unidentifiedBank: (bank: string) => `${bank} · Source account not identified`,
};

const ar: typeof en = {
  title: 'التحويلات',
  back: 'رجوع',
  pending: 'غير المصنفة',
  reviewed: 'المؤكدة',
  noticeTitle: () => 'تحويلات محفوظة بشكل منفصل',
  noticeBody: 'التحويلات غير المصنفة غير محتسبة ضمن الدخل والمصروفات والصافي.',
  noticeCount: (count) => `${count.toLocaleString('ar-AE')} غير مصنفة · غير محتسبة في الإجماليات`,
  intro: 'لا حاجة لمراجعة سجلك كله. صنّف فقط التحويلات التي تعرفها؛ وتبقى البقية منفصلة عن الدخل والمصروفات.',
  reviewedIntro: 'تحويلات مؤكدة بدليل البنك أو باختيارك. يمكنك مراجعة المطابقة التلقائية أو التراجع عن اختيارك لتغييره.',
  moneyIn: 'أموال واردة',
  moneyOut: 'أموال صادرة',
  count: (count) => `عدد العمليات: ${count}`,
  accountUnknown: 'الحساب غير متاح',
  counterpartyUnknown: 'الطرف الآخر غير محدد',
  accountEnding: (last4) => `حساب ينتهي بـ ${last4}`,
  cardEnding: (last4) => `بطاقة تنتهي بـ ${last4}`,
  review: 'تصنيف التحويل',
  reviewGroup: (count) => `تصنيف هذه التحويلات وعددها ${count}`,
  individualOnly: 'هذه العمليات من الحساب نفسه، لكن ليس بالضرورة للمستلم نفسه. اتركها غير مصنفة ما لم تتعرف على العملية.',
  recent: 'آخر 90 يوماً',
  allHistory: 'كل السجل',
  newestFirst: 'الأحدث أولاً',
  search: 'ابحث بالحساب أو الاسم أو المبلغ',
  clearSearch: 'مسح البحث',
  historyAvailable: (count) => `${count.toLocaleString('ar-AE')} عملية أخرى في كل السجل`,
  shown: (count, groups) => `${count.toLocaleString('ar-AE')} تحويلات · ${groups.toLocaleString('ar-AE')} مجموعات`,
  expand: (count) => `عرض ${count.toLocaleString('ar-AE')} تحويلات`,
  collapse: 'إخفاء التحويلات',
  more: (shown, count) => `عرض المزيد · ${shown.toLocaleString('ar-AE')} من ${count.toLocaleString('ar-AE')}`,
  recentEmpty: 'لا توجد تحويلات غير مصنفة خلال آخر 90 يوماً',
  searchEmpty: 'لا توجد نتائج في هذا العرض',
  searchEmptyBody: 'جرّب اسماً أو مبلغاً آخر، أو اختر كل السجل.',
  sent: 'صادر',
  received: 'وارد',
  reference: 'مرجع البنك',
  bankRecord: 'إشعار بنكي مسجل',
  manualRecord: 'إدخال يدوي',
  keepSeparate: 'تركه غير مصنف',
  own: 'بين حساباتي الشخصية',
  ownBody: 'استبعاد هذه المبالغ من الدخل والمصروفات. ستبقى مسجلة كحركات بين الحسابات.',
  externalIn: 'أموال تلقيتها من طرف آخر',
  externalOut: 'دفعت لطرف آخر',
  externalInBody: 'احتساب هذه الأموال ضمن الدخل والصافي.',
  externalOutBody: 'احتساب هذه الدفعة ضمن المصروفات والصافي.',
  choose: 'ما طبيعة هذا التحويل؟',
  groupChoose: 'هل لجميع هذه التحويلات الغرض نفسه؟',
  groupHint: 'أكّد فقط إذا كان هذا الاختيار ينطبق على كل العمليات المشمولة في العدد والإجمالي.',
  confirm: 'حفظ التصنيف',
  saving: 'جارٍ الحفظ…',
  saved: 'تم حفظ التصنيف',
  cancel: 'إلغاء',
  undo: 'التراجع عن القرار',
  undoTitle: 'إعادة هذه العملية للمراجعة؟',
  undoBody: 'إزالة تصنيفك المحفوظ. ستعيد وفرة تقييم الأدلة المتاحة؛ وتبقى المبالغ غير المحسومة خارج الدخل والمصروفات المؤكدة والصافي.',
  undone: 'تمت إزالة القرار',
  changed: 'تغيّرت هذه العمليات أثناء مراجعتها. أغلق هذه اللوحة وافتحها مجدداً لمراجعة أحدث التفاصيل.',
  saveFailed: 'تعذّر حفظ القرار. أغلق هذه اللوحة وراجع أحدث التفاصيل قبل المحاولة مجدداً.',
  durabilityFailed: 'تم تطبيق قرارك على هذه الشاشة، لكنه لم يُحفظ بأمان بعد. أعد محاولة الحفظ قبل مغادرة هذه اللوحة.',
  retrySave: 'إعادة محاولة الحفظ',
  empty: 'لا توجد تحويلات غير مصنفة في هذا العرض',
  emptyBody: 'تبقى التحويلات الأقدم متاحة في كل السجل. تغيير العرض لا يحذف أي عملية أو يصنّفها.',
  reviewedEmpty: 'لا توجد تحويلات مؤكدة في هذا العرض',
  reviewedEmptyBody: 'ستظهر التحويلات المؤكدة هنا لتتمكن من مراجعتها مجدداً.',
  missingRoute: 'لم تعد هذه العملية متاحة لمراجعة التحويلات.',
  notPending: 'لا يوجد قرار معلّق بشأن ملكية هذه العملية.',
  showAll: 'عرض كل التحويلات',
  ownershipUnknown: 'تحويل غير مصنف',
  ambiguous: 'أكثر من عملية مطابقة محتملة',
  counterpartMissing: 'لم تُعثر على عملية الحساب الآخر',
  confirmedOwn: 'بين حساباتك',
  confirmedExternal: 'مع طرف آخر',
  cardRepayment: 'سداد بطاقة ائتمان',
  corroborating: 'تأكيد بنكي إضافي · لا يُحتسب مرتين',
  likelyOwn: 'تحويل محتمل بين حساباتك',
  likelyCard: 'سداد محتمل لبطاقة ائتمان',
  suggestedOnly: 'تطابق المبلغ والتوقيت اقتراح، وليس تأكيداً لملكية الحساب.',
  knownAccountEvidence: 'تم التعرّف عليه تلقائياً: رسائل بنكية أخرى تثبت أن هذا الحساب لك. لا يلزم إشعار استلام مطابق لإثبات الملكية.',
  knownCardEvidence: 'تم التعرّف عليه تلقائياً: رسائل بنكية أخرى تثبت أن بطاقة الائتمان المستلمة لك. الدفعة البنكية مسجلة، ولم يُربط بها إشعار استلام من البطاقة.',
  linkedEntry: 'العملية البنكية المطابقة',
  linkOwn: 'تأكيد وربط العمليتين',
  unidentifiedBank: (bank) => `${bank} · حساب المصدر غير محدد`,
};

export const transferReviewCopy = (language: string = getLanguage()): typeof en =>
  language === 'ar' ? ar : en;
