import { getLanguage } from '@/lib/i18n';

const en = {
  title: 'Review transfers',
  back: 'Back',
  pending: 'To review',
  reviewed: 'Confirmed',
  noticeTitle: (count: number) => `${count} transfer${count === 1 ? '' : 's'} to review`,
  noticeBody: 'Pending transfers may affect income, spending and Net. Confirm them so Wafra excludes only moves between your own accounts.',
  intro: 'Confirm who owns the money on the other side. Wafra excludes confirmed own-account moves; unresolved transfers with a known account remain in totals until you review them.',
  reviewedIntro: 'Transfers confirmed by bank evidence or your choice. Review an automatic match, or undo your choice to change it.',
  moneyIn: 'Money in',
  moneyOut: 'Money out',
  count: (count: number) => `${count} entr${count === 1 ? 'y' : 'ies'}`,
  accountUnknown: 'Account unavailable',
  counterpartyUnknown: 'Counterparty not identified',
  accountEnding: (last4: string) => `Account ending ${last4}`,
  cardEnding: (last4: string) => `Card ending ${last4}`,
  review: 'Review entry',
  reviewGroup: (count: number) => `Review ${count} entries together`,
  individualOnly: 'Review each entry separately. Their counterparty is not confirmed.',
  own: 'Between my own accounts',
  ownBody: 'Exclude these amounts from income and spending. They stay recorded as account movements.',
  externalIn: 'Money received from someone else',
  externalOut: 'Paid someone else',
  externalInBody: 'Include this money in income and Net.',
  externalOutBody: 'Include this payment in spending and Net.',
  choose: 'What was this transfer?',
  groupChoose: 'Do all these transfers have the same purpose?',
  groupHint: 'Confirm only if this choice applies to every entry shown in the count and total.',
  confirm: 'Save classification',
  saving: 'Saving…',
  saved: 'Classification saved',
  cancel: 'Cancel',
  undo: 'Undo decision',
  undoTitle: 'Return this entry to review?',
  undoBody: 'Remove your saved classification. Wafra will reassess the available evidence; an unresolved transfer may affect totals until you review it again.',
  undone: 'Decision removed',
  changed: 'These entries changed while you were reviewing them. Close this panel and open them again to review the latest details.',
  saveFailed: 'Could not save this decision. Close this panel and review the latest details before trying again.',
  durabilityFailed: 'Your decision is applied on this screen but has not been safely saved. Retry saving before leaving this panel.',
  retrySave: 'Retry saving',
  empty: 'No transfers need review',
  emptyBody: 'Transfers needing your decision will appear here.',
  reviewedEmpty: 'No confirmed transfers',
  reviewedEmptyBody: 'Confirmed transfers will appear here so you can review them again.',
  missingRoute: 'This entry is no longer available for transfer review.',
  notPending: 'This entry has no pending ownership decision.',
  showAll: 'Show all transfers',
  ownershipUnknown: 'Ownership needs confirmation',
  ambiguous: 'More than one possible match',
  counterpartMissing: 'Other account entry not found',
  confirmedOwn: 'Between your accounts',
  confirmedExternal: 'With someone else',
};

const ar: typeof en = {
  title: 'مراجعة التحويلات',
  back: 'رجوع',
  pending: 'للمراجعة',
  reviewed: 'المؤكدة',
  noticeTitle: (count) => `تحويلات للمراجعة: ${count}`,
  noticeBody: 'قد تؤثر التحويلات المعلّقة في الدخل والمصروفات والصافي. أكّدها لكي تستبعد وفرة فقط التحويلات بين حساباتك.',
  intro: 'أكّد ملكية الأموال في الطرف الآخر من التحويل. تستبعد وفرة التحويلات المؤكدة بين حساباتك، بينما تبقى التحويلات غير المحسومة ذات الحساب المعروف ضمن الإجماليات حتى تراجعها.',
  reviewedIntro: 'تحويلات مؤكدة بدليل البنك أو باختيارك. يمكنك مراجعة المطابقة التلقائية أو التراجع عن اختيارك لتغييره.',
  moneyIn: 'أموال واردة',
  moneyOut: 'أموال صادرة',
  count: (count) => `عدد العمليات: ${count}`,
  accountUnknown: 'الحساب غير متاح',
  counterpartyUnknown: 'الطرف الآخر غير محدد',
  accountEnding: (last4) => `حساب ينتهي بـ ${last4}`,
  cardEnding: (last4) => `بطاقة تنتهي بـ ${last4}`,
  review: 'مراجعة العملية',
  reviewGroup: (count) => `مراجعة ${count} عمليات معاً`,
  individualOnly: 'راجع كل عملية على حدة. لم يتم تأكيد الطرف الآخر.',
  own: 'بين حساباتي الشخصية',
  ownBody: 'استبعاد هذه المبالغ من الدخل والمصروفات. ستبقى مسجلة كحركات بين الحسابات.',
  externalIn: 'أموال تلقيتها من طرف آخر',
  externalOut: 'دفعت لطرف آخر',
  externalInBody: 'احتساب هذه الأموال ضمن الدخل والصافي.',
  externalOutBody: 'احتساب هذه الدفعة ضمن المصروفات والصافي.',
  choose: 'ما طبيعة هذا التحويل؟',
  groupChoose: 'هل لجميع هذه التحويلات الغرض نفسه؟',
  groupHint: 'أكّد فقط إذا كان هذا الاختيار ينطبق على كل العمليات المشمولة في العدد والإجمالي.',
  confirm: 'حفظ التصنيف',
  saving: 'جارٍ الحفظ…',
  saved: 'تم حفظ التصنيف',
  cancel: 'إلغاء',
  undo: 'التراجع عن القرار',
  undoTitle: 'إعادة هذه العملية للمراجعة؟',
  undoBody: 'إزالة تصنيفك المحفوظ. ستعيد وفرة تقييم الأدلة المتاحة؛ وقد تؤثر العملية غير المحسومة في الإجماليات حتى تراجعها مرة أخرى.',
  undone: 'تمت إزالة القرار',
  changed: 'تغيّرت هذه العمليات أثناء مراجعتها. أغلق هذه اللوحة وافتحها مجدداً لمراجعة أحدث التفاصيل.',
  saveFailed: 'تعذّر حفظ القرار. أغلق هذه اللوحة وراجع أحدث التفاصيل قبل المحاولة مجدداً.',
  durabilityFailed: 'تم تطبيق قرارك على هذه الشاشة، لكنه لم يُحفظ بأمان بعد. أعد محاولة الحفظ قبل مغادرة هذه اللوحة.',
  retrySave: 'إعادة محاولة الحفظ',
  empty: 'لا توجد تحويلات تحتاج إلى مراجعة',
  emptyBody: 'ستظهر هنا التحويلات التي تحتاج إلى قرارك.',
  reviewedEmpty: 'لا توجد تحويلات مؤكدة',
  reviewedEmptyBody: 'ستظهر التحويلات المؤكدة هنا لتتمكن من مراجعتها مجدداً.',
  missingRoute: 'لم تعد هذه العملية متاحة لمراجعة التحويلات.',
  notPending: 'لا يوجد قرار معلّق بشأن ملكية هذه العملية.',
  showAll: 'عرض كل التحويلات',
  ownershipUnknown: 'ملكية الأموال تحتاج إلى تأكيد',
  ambiguous: 'أكثر من عملية مطابقة محتملة',
  counterpartMissing: 'لم تُعثر على عملية الحساب الآخر',
  confirmedOwn: 'بين حساباتك',
  confirmedExternal: 'مع طرف آخر',
};

export const transferReviewCopy = (language: string = getLanguage()): typeof en =>
  language === 'ar' ? ar : en;
