import { canonicalCaptureSourceKey, captureSourceTimeMatches, isUsableCaptureSourceIdentity, isValidAndroidSourceKey } from '@/lib/capture-source-identity';
import { categorySupportsType } from '@/lib/categories';
import {
  ledgerMoneyMatchesCurrentMetadata,
  ledgerMoneySpec,
  migrateLegacyLedgerMoney,
} from '@/lib/ledger-money';
import type { Account, AppState, CaptureInstrument, CategoryId, ImportBatchInput } from '@/lib/types';
import type { UniversalBankEvent, UniversalField, UniversalInstrument, UniversalMoney } from '@/lib/universal-types';

/**
 * Supplied by an explicit review action, never inferred from parser confidence.
 * The host must bind these choices, sourceKey and observedAt to the same
 * immutable captured source that produced the reviewed UniversalBankEvent.
 */
export interface UniversalImportConfirmation {
  confirmed: true;
  postingStatus: 'posted';
  amount: UniversalMoney;
  direction: 'debit' | 'credit';
  accountId: string;
  title: string;
  category: CategoryId;
  date: string;
  /** Opaque capture identity supplied by the host, not text generated by a parser. */
  sourceKey: string;
  observedAt: number;
  /** Required when the source contains multiple possible instruments. */
  instrument?: UniversalInstrument;
  betweenOwnAccounts?: boolean;
}

export type UniversalImportRefusal =
  | 'confirmation-required' | 'not-hydrated' | 'invalid-event' | 'ignored-event'
  | 'unsupported-event' | 'not-posted' | 'direction-conflict' | 'invalid-money'
  | 'ungrounded-money' | 'currency-mismatch' | 'invalid-account' | 'instrument-ambiguous'
  | 'instrument-mismatch' | 'invalid-category' | 'invalid-title' | 'invalid-date'
  | 'invalid-source' | 'invalid-transfer';

export type ConfirmedUniversalImportPlan =
  | { outcome: 'ready'; batch: ImportBatchInput }
  | { outcome: 'duplicate'; transactionId: string }
  | { outcome: 'refused'; reason: UniversalImportRefusal };

const refuse = (reason: UniversalImportRefusal): ConfirmedUniversalImportPlan => ({ outcome: 'refused', reason });
const transactionFamilies = new Set(['purchase', 'transfer', 'cash-withdrawal', 'refund', 'fee', 'utility', 'recurring-payment', 'unknown']);

/**
 * Preserve host provider identities across review and inbox/history import.
 * Android sourceEventId `a123` is stored by the existing importer as `ha123`.
 * Its explicit review alias can bridge to that key; an opaque arc1 hash
 * cannot recover a provider id and must never be guessed into one.
 */
export const canonicalUniversalSourceKey = canonicalCaptureSourceKey;

const validSourceKey = (key: unknown): key is string => {
  if (typeof key !== 'string') return false;
  if (key.startsWith('android_message_review_source_')) {
    return isValidAndroidSourceKey(key);
  }
  if (key.startsWith('ha')) {
    return isValidAndroidSourceKey(key) || /^h[a-f0-9]{64}$/.test(key);
  }
  return /^[A-Za-z0-9_-]{16,128}$/.test(key);
};

const equalMoney = (a: UniversalMoney, b: UniversalMoney): boolean =>
  Boolean(a && b) && a.currency === b.currency && a.exponent === b.exponent && a.minorUnits === b.minorUnits;

const grounded = <T>(field: UniversalField<T> | undefined, value: T, equal: (a: T, b: T) => boolean): boolean =>
  Boolean(field && (field.evidence === 'explicit' || field.evidence === 'ambiguous') &&
    ((field.value !== null && equal(field.value, value)) ||
      (Array.isArray(field.alternatives) && field.alternatives.some((alternative) => equal(alternative, value)))));

const validDate = (value: unknown): value is string => {
  if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return false;
  const date = new Date(`${value}T00:00:00Z`);
  return Number.isFinite(date.getTime()) && date.toISOString().slice(0, 10) === value;
};

const validInstrument = (instrument: UniversalInstrument): boolean =>
  Boolean(instrument) && ['card', 'account', 'wallet'].includes(instrument.kind) &&
    (instrument.last4 === null || (typeof instrument.last4 === 'string' && /^\d{4}$/.test(instrument.last4)));
const equalInstrument = (a: UniversalInstrument, b: UniversalInstrument): boolean =>
  Boolean(a && b) && a.kind === b.kind && a.last4 === b.last4;
const compatibleAccount = (account: Account, instrument: UniversalInstrument): boolean => {
  if (instrument.last4 && account.last4 && instrument.last4 !== account.last4) return false;
  if (instrument.kind === 'card') return account.kind === 'card';
  if (instrument.kind === 'account') return account.kind === 'bank';
  // Wallets have no distinct stored Account kind. An explicit user selection
  // may use a bank/cash bucket, but cannot turn a named wallet into a card.
  return account.kind !== 'card';
};

/**
 * Adapt one confirmed, source-grounded posting without entering the legacy
 * two-decimal Gulf parser. The ordinary store commit still revalidates money
 * against the authoritative ledger and provides encrypted durability.
 *
 * Statements, balance notices and future bills deliberately have no posting
 * adapter here. Their facts cannot be represented by a made-up transaction.
 *
 * Host contract: validate the source/confirmation binding and call with the
 * latest authoritative state in one serialized replan-and-commit operation.
 * Ready batches are single-use: the existing reducer preserves user-edited
 * rows, so replaying a cached ready batch can duplicate the same source key.
 * A returned batch is not reusable authorization for a changed review.
 * This source-free event cannot itself detect two equal-value sources being
 * swapped, and currency validation alone does not protect stale source IDs.
 */
export function planConfirmedUniversalImport(
  state: AppState,
  event: UniversalBankEvent,
  confirmation: UniversalImportConfirmation,
): ConfirmedUniversalImportPlan {
  if (!confirmation || confirmation.confirmed !== true || confirmation.postingStatus !== 'posted') {
    return refuse('confirmation-required');
  }
  if (!state.hydrated) return refuse('not-hydrated');
  if (!event || event.version !== 1 || !['review', 'ignore'].includes(event.decision)) return refuse('invalid-event');
  if (event.decision === 'ignore') return refuse('ignored-event');
  if (!transactionFamilies.has(event.family)) return refuse('unsupported-event');
  if (event.status !== 'posted' && event.status !== 'unknown') return refuse('not-posted');
  if (!['debit', 'credit'].includes(confirmation.direction)) return refuse('confirmation-required');
  if (event.direction !== 'unknown' && event.direction !== confirmation.direction) return refuse('direction-conflict');

  const selected = confirmation.amount;
  if (!selected || typeof selected.currency !== 'string' ||
    !/^[A-Z]{3}$/.test(selected.currency) || typeof selected.minorUnits !== 'string' ||
    !/^[1-9]\d{0,39}$/.test(selected.minorUnits)) return refuse('invalid-money');
  const money = ledgerMoneySpec(selected.currency);
  if (!money || money.exponent !== selected.exponent || !ledgerMoneyMatchesCurrentMetadata(money)) {
    return refuse('invalid-money');
  }
  if (!grounded(event.amount, selected, equalMoney)) return refuse('ungrounded-money');
  const minor = BigInt(selected.minorUnits);
  if (minor > BigInt(Number.MAX_SAFE_INTEGER)) return refuse('invalid-money');
  try {
    const current = migrateLegacyLedgerMoney(state);
    if (current && (!ledgerMoneyMatchesCurrentMetadata(current) ||
      current.currency !== money.currency || current.exponent !== money.exponent)) {
      return refuse('currency-mismatch');
    }
  } catch {
    return refuse('invalid-money');
  }

  const account = state.accounts.find((candidate) => candidate.id === confirmation.accountId);
  if (!account) return refuse('invalid-account');
  if (!event.instrument || !['explicit', 'ambiguous', 'missing'].includes(event.instrument.evidence)) {
    return refuse('invalid-event');
  }
  let instrument: UniversalInstrument | null = null;
  if (event.instrument?.evidence === 'ambiguous') {
    if (!confirmation.instrument) return refuse('instrument-ambiguous');
    if (!grounded(event.instrument, confirmation.instrument, equalInstrument)) return refuse('instrument-mismatch');
    instrument = confirmation.instrument;
  } else if (event.instrument?.evidence === 'explicit') {
    instrument = event.instrument.value;
    if (!instrument || (confirmation.instrument && !equalInstrument(instrument, confirmation.instrument))) {
      return refuse('instrument-mismatch');
    }
  } else if (confirmation.instrument) {
    return refuse('instrument-mismatch');
  }
  if (instrument && (!validInstrument(instrument) || !compatibleAccount(account, instrument))) {
    return refuse('instrument-mismatch');
  }
  const type = confirmation.direction === 'credit' ? 'income' : 'expense';
  if (!categorySupportsType(confirmation.category, type)) {
    return refuse('invalid-category');
  }
  if (typeof confirmation.title !== 'string') return refuse('invalid-title');
  const title = confirmation.title.trim();
  if (!title || title.length > 80 || /[\u0000-\u001F\u007F-\u009F]/u.test(title)) return refuse('invalid-title');
  if (!validDate(confirmation.date)) return refuse('invalid-date');
  if (!validSourceKey(confirmation.sourceKey) || !captureSourceTimeMatches(confirmation.sourceKey, confirmation.observedAt) ||
    !Number.isSafeInteger(confirmation.observedAt) || confirmation.observedAt < 0 ||
    !Number.isFinite(new Date(confirmation.observedAt).getTime())) return refuse('invalid-source');
  if (confirmation.betweenOwnAccounts !== undefined && typeof confirmation.betweenOwnAccounts !== 'boolean') {
    return refuse('invalid-transfer');
  }
  if (confirmation.betweenOwnAccounts && event.family !== 'transfer') return refuse('invalid-transfer');

  const sourceKey = canonicalUniversalSourceKey(confirmation.sourceKey, confirmation.observedAt);
  const duplicate = state.transactions.find((transaction) => transaction.smsKey &&
    isUsableCaptureSourceIdentity(transaction.smsKey, transaction.ts) &&
    canonicalUniversalSourceKey(transaction.smsKey, transaction.ts) === sourceKey);
  if (duplicate) return { outcome: 'duplicate', transactionId: duplicate.id };
  const captureInstrument: CaptureInstrument | undefined = instrument?.last4 ? {
    last4: instrument.last4,
    kind: instrument.kind === 'account' ? 'account' : 'unknown',
  } : undefined;

  return {
    outcome: 'ready',
    batch: {
      importMoney: money,
      transactions: [{
        amountFils: Number(minor), type, accountId: account.id, title,
        category: confirmation.category, date: confirmation.date,
        ts: confirmation.observedAt, source: 'sms', smsKey: sourceKey,
        userEdited: true, titleEdited: true,
        ...(captureInstrument ? { captureInstrument } : {}),
        ...(confirmation.betweenOwnAccounts ? { isTransfer: true } : {}),
        ...(event.family === 'transfer' ? { transferDecision: {
          version: 1 as const, ownership: confirmation.betweenOwnAccounts ? 'own' as const : 'external' as const,
          decidedAt: Date.now(),
        } } : {}),
      }],
      newAccounts: [], newDues: [], newBills: [], newHints: {}, snapshots: {}, bankNames: {}, cardTypes: {}, updates: [],
      // An explicit review decision must not skip other unread capture events.
      lastScanTs: state.lastScanTs,
    },
  };
}
