/** Presentation copy only. No capture, account or subscription capabilities are inferred here. */
const en = {
  welcomeTitle: 'Your money.\nMore clarity.',
  welcomeBody: 'Bring your spending, bills and accounts into one calm place.',
  welcomeFootnote: 'Choose what to import. You stay in control.',
  overview: 'Overview', preferences: 'Preferences', capture: 'Imports', privacy: 'Privacy & data', help: 'Help',
  settingsTitle: 'Make Wafra yours',
  settingsBody: 'Your preferences, import controls and data. All in one place.',
  settingsNavigation: 'Settings sections',
  reviewTitle: 'A quick check from you',
  reviewBody: 'These alerts are not included in your totals. Review the details before adding them.',
  pending: 'Awaiting review', complete: 'All caught up',
  sortTitle: 'Give every merchant a home',
  sortBody: 'Choose a category for a merchant. The rule updates its matching entries and future spending.',
  merchants: 'Merchants left', entries: 'Matching entries',
  importTitle: 'Bring your activity together',
  importBody: 'Choose a source, check the results, then save your transactions.',
  importSteps: 'Import stages', source: 'Source', review: 'Review', save: 'Save',
  setupTitle: 'Bank alerts, your way',
  setupBody: 'Set up future alerts or bring in past messages. Each step explains what to do next.',
  feedbackTitle: 'Help shape Wafra',
  feedbackBody: 'Tell us what happened. Check exactly what will be shared before sending.',
  devicesTitle: 'You choose who has access',
  devicesBody: 'Manage the devices linked to your encrypted vault. Pairing is optional.',
  proTitle: 'More help with your money',
  proBody: 'Review the available features and store price before choosing a plan.',
  recorded: 'Recorded activity', manualTitle: 'Add a money entry',
  manualBody: 'Check the amount, account and category before saving.',
  privacyTitle: 'Your data stays in your hands',
  privacyBody: 'Exports, privacy controls and removal are separate actions. Nothing is shared or deleted by opening this screen.',
  needsReview: 'Needs your review', chooseCategory: 'Choose a category',
  stepCurrent: 'Current step', stepComplete: 'Completed step',
} as const;
const ar: Record<keyof typeof en, string> = {
  welcomeTitle: 'أموالك.\nصورة أوضح.',
  welcomeBody: 'إنفاقك وفواتيرك وحساباتك في مكان واحد مريح.',
  welcomeFootnote: 'اختر ما تستورده. القرار لك دائماً.',
  overview: 'نظرة عامة', preferences: 'التفضيلات', capture: 'الاستيراد', privacy: 'الخصوصية والبيانات', help: 'المساعدة',
  settingsTitle: 'وفرة على طريقتك',
  settingsBody: 'تفضيلاتك وإعدادات الاستيراد وبياناتك في مكان واحد.',
  settingsNavigation: 'أقسام الإعدادات',
  reviewTitle: 'مراجعة بسيطة منك',
  reviewBody: 'هذه التنبيهات غير محسوبة في إجمالياتك. راجع التفاصيل قبل إضافتها.',
  pending: 'بانتظار المراجعة', complete: 'اكتملت المراجعة',
  sortTitle: 'فئة واضحة لكل متجر',
  sortBody: 'اختر فئة للمتجر. تطبّق القاعدة على حركاته المطابقة والإنفاق القادم.',
  merchants: 'المتاجر المتبقية', entries: 'الحركات المطابقة',
  importTitle: 'اجمع حركاتك في مكان واحد',
  importBody: 'اختر المصدر، ثم راجع النتائج واحفظ حركاتك.',
  importSteps: 'مراحل الاستيراد', source: 'المصدر', review: 'المراجعة', save: 'الحفظ',
  setupTitle: 'تنبيهات البنك على طريقتك',
  setupBody: 'أعدّ التنبيهات القادمة أو استورد الرسائل السابقة. كل خطوة توضح ما يليها.',
  feedbackTitle: 'ساهم في تحسين وفرة',
  feedbackBody: 'أخبرنا بما حدث. راجع ما سيُشارك بالتحديد قبل الإرسال.',
  devicesTitle: 'أنت تختار من يصل إلى بياناتك',
  devicesBody: 'أدر الأجهزة المرتبطة بخزنتك المشفّرة. الربط اختياري.',
  proTitle: 'مساعدة أكبر في إدارة أموالك',
  proBody: 'راجع المزايا المتاحة وسعر المتجر قبل اختيار الخطة.',
  recorded: 'الحركات المسجلة', manualTitle: 'أضف حركة مالية',
  manualBody: 'تحقق من المبلغ والحساب والفئة قبل الحفظ.',
  privacyTitle: 'بياناتك تحت سيطرتك',
  privacyBody: 'التصدير والخصوصية والحذف إجراءات منفصلة. فتح هذه الشاشة لا يشارك بياناتك ولا يحذفها.',
  needsReview: 'يحتاج إلى مراجعتك', chooseCategory: 'اختر الفئة',
  stepCurrent: 'الخطوة الحالية', stepComplete: 'خطوة مكتملة',
};
export function workflowCopy(language: string): Record<keyof typeof en, string> {
  return language === 'ar' ? ar : en;
}
