'use strict';
/**
 * Ask Wafra question templates, per language and intent.
 *
 * Placeholders: {CAT} {MER} {ACCT} {PERIOD} {CMP} {N}. `{PERIOD!}` / `{CMP!}`
 * render the bare period (no language preposition/postposition), for
 * "compare X with Y" shapes. `[ ... ]` is an optional group. Arabic templates
 * prefixed `g|` are Gulf dialect; the rest are MSA.
 *
 * Template ORDER is part of the split contract (see questions.cjs): append new
 * templates at the end of a list so existing train/dev/test assignment holds.
 */

const EN = {
  spending_total: [
    'How much did I spend on {CAT}[ {PERIOD}]?',
    'How much did I spend at {MER}[ {PERIOD}]?',
    'How much have I spent[ {PERIOD}]?',
    'What did I spend on {CAT} {PERIOD}?',
    'Total spending {PERIOD}',
    "What's my {CAT} spending[ {PERIOD}]?",
    'How much went to {MER}[ {PERIOD}]?',
    'Show my spending at {MER} {PERIOD}',
    'How much money did I spend {PERIOD}[ with {ACCT}]?',
    'What have I spent on {CAT}[ using {ACCT}] {PERIOD}?',
    'My total expenses {PERIOD}',
    'How much did {MER} cost me[ {PERIOD}]?',
    'How much do I spend on {CAT}?',
    'Spending on {CAT} {PERIOD}',
    'How much did I pay {MER}[ {PERIOD}]?',
    'What was my total spend[ on {ACCT}] {PERIOD}?',
    'Give me my {CAT} expenses for {PERIOD!}',
  ],
  income_total: [
    'How much did I earn[ {PERIOD}]?',
    'What was my income {PERIOD}?',
    'How much income did I receive[ {PERIOD}]?',
    'How much salary did I get {PERIOD}?',
    'Total income {PERIOD}',
    'How much money came in {PERIOD}?',
    'How much did I get paid {PERIOD}?',
    'What did I earn {PERIOD}[ in {ACCT}]?',
    'Show my income[ {PERIOD}]',
    'How much have I received {PERIOD}?',
    'My earnings {PERIOD}',
    "What's my total income[ {PERIOD}]?",
    'How much did I make {PERIOD}?',
    'How much was deposited[ to {ACCT}] {PERIOD}?',
    'How much income came into {ACCT} {PERIOD}?',
  ],
  compare_periods: [
    'Compare {PERIOD!} with {CMP!}',
    'How does {PERIOD!} compare to {CMP!}?',
    'Did I spend more {PERIOD} than {CMP}?',
    '{PERIOD!} vs {CMP!} spending',
    'Is my spending up compared to {CMP!}?',
    'Did my {CAT} spending go up {PERIOD}?',
    'Why did my spending change {PERIOD}?',
    'Did I spend less on {CAT} {PERIOD} than {CMP}?',
    'Compare my {CAT} spending {PERIOD} and {CMP}',
    'Spending difference between {PERIOD!} and {CMP!}',
    'Am I spending more at {MER} {PERIOD} than {CMP}?',
    'Did my spending increase?',
    'Why is my spending higher {PERIOD}?',
    'Has my {CAT} spending decreased compared to {CMP!}?',
    'Was {PERIOD!} more expensive than {CMP!}?',
  ],
  top_merchants: [
    'What are my top {N} merchants[ {PERIOD}]?',
    'Top merchants {PERIOD}',
    'Where do I spend the most[ {PERIOD}]?',
    'Which merchants did I spend the most at {PERIOD}?',
    'Show my top {N} shops {PERIOD}',
    'Who got most of my money {PERIOD}?',
    'Top {N} places I spent money[ {PERIOD}]',
    'Which stores did I spend the most at {PERIOD}?',
    'My biggest merchants {PERIOD}',
    'Rank my merchants by spending {PERIOD}',
    'Which {N} merchants took the most money[ {PERIOD}]?',
    'Top merchants for {CAT} {PERIOD}',
    'Where did I spend the most on {CAT}[ {PERIOD}]?',
    'List the merchants I spent most at[ {PERIOD}]',
    'Which merchant did I spend the most at {PERIOD}?',
    'Biggest merchant[ {PERIOD}]?',
  ],
  top_categories: [
    'What are my top {N} categories[ {PERIOD}]?',
    'Where did my money go[ {PERIOD}]?',
    'What did I spend the most on {PERIOD}?',
    'Top spending categories {PERIOD}',
    'Which categories cost me the most {PERIOD}?',
    'Break down my spending by category[ {PERIOD}]',
    'My biggest categories {PERIOD}',
    'Which category did I spend most on[ {PERIOD}]?',
    'Show spending by category {PERIOD}',
    'Top {N} categories {PERIOD}',
    'What are my biggest expense categories[ {PERIOD}]?',
    'Where is my money going?',
    'Category breakdown {PERIOD}',
    'Rank my categories {PERIOD}',
    'What do I spend the most on?',
    'Which {N} categories were highest {PERIOD}?',
  ],
  largest_purchases: [
    'What were my biggest purchases[ {PERIOD}]?',
    'Show my top {N} purchases {PERIOD}',
    'Largest transactions {PERIOD}',
    "What's the most expensive thing I bought {PERIOD}?",
    'My {N} largest purchases[ {PERIOD}]',
    'Biggest spends {PERIOD}',
    'Show the largest {CAT} purchases {PERIOD}',
    'What was my largest purchase at {MER}[ {PERIOD}]?',
    'Top {N} transactions[ {PERIOD}]',
    'Largest purchases[ on {ACCT}] {PERIOD}',
    'Which purchases were the biggest {PERIOD}?',
    'List my most expensive purchases {PERIOD}',
    'What are the {N} biggest charges {PERIOD}?',
    'Biggest single purchase[ {PERIOD}]',
    'Show my largest transactions for {CAT}',
    'What did I buy that cost the most {PERIOD}?',
  ],
  daily_average: [
    "What's my daily average spending[ {PERIOD}]?",
    'How much do I spend per day[ {PERIOD}]?',
    'Average daily spend {PERIOD}',
    'How much am I spending each day {PERIOD}?',
    "What's my average spend per day on {CAT}[ {PERIOD}]?",
    'Daily average {PERIOD}',
    'On average, how much do I spend a day[ {PERIOD}]?',
    'Per day spending {PERIOD}',
    'How much did I spend daily {PERIOD}?',
    'Average per day at {MER} {PERIOD}',
    'What is my spending per day[ with {ACCT}]?',
    'Daily {CAT} spending average {PERIOD}',
    'How much per day am I burning {PERIOD}?',
    'Average amount spent each day {PERIOD}',
    'Daily spend rate[ {PERIOD}]',
  ],
  net_income_spending: [
    'Did I spend more than I earned[ {PERIOD}]?',
    "What's my net {PERIOD}?",
    'Income minus spending {PERIOD}',
    "What's my net cash flow {PERIOD}?",
    'Am I in the positive {PERIOD}?',
    'Earned vs spent {PERIOD}',
    'Did I earn more than I spent {PERIOD}?',
    'Net income and spending[ {PERIOD}]',
    'How much more did I spend than earn {PERIOD}?',
    'Show income versus expenses {PERIOD}',
    'Is my spending higher than my income {PERIOD}?',
    "What's the difference between my income and spending[ {PERIOD}]?",
    'Net spending {PERIOD}',
    'Did I overspend my income {PERIOD}?',
    'Money in minus money out {PERIOD}',
    'Am I spending more than I make?',
  ],
  subscriptions: [
    'What subscriptions do I have?',
    'Show my subscriptions',
    'List my recurring subscriptions',
    'What am I subscribed to?',
    'Which services am I paying for every month?',
    'How much do my subscriptions cost?',
    'What memberships do I have?',
    'Show my active subscriptions',
    'Which subscriptions are active?',
    'What recurring charges do I have?',
    'Do I have any subscriptions?',
    'List all my subs',
    'What streaming services am I paying for?',
    "What's charging me every month?",
    'Show recurring payments',
    'My monthly subscriptions',
  ],
  upcoming_payments: [
    'What payments are due soon?',
    'What bills are coming up?',
    'What do I owe soon?',
    'Upcoming payments',
    'Which bills are due?',
    "What's coming up?",
    'Show my upcoming bills',
    'Do I have any payments due?',
    'What needs paying?',
    'What payments are next?',
    'Any bills due soon?',
    "What's due?",
    'List upcoming payments',
    'Which card payments are due?',
    'Are any bills coming up?',
    "Show what's due",
  ],
  unusual_charges: [
    'Any unusual charges[ {PERIOD}]?',
    'Were there any weird charges {PERIOD}?',
    'Show unusual transactions {PERIOD}',
    'Any outliers in my spending {PERIOD}?',
    'Show odd charges {PERIOD}',
    'Were any purchases unusually high {PERIOD}?',
    'Unusual spending at {MER}[ {PERIOD}]?',
    'Which charges were out of the ordinary {PERIOD}?',
    'Flag unusual purchases[ {PERIOD}]',
    'Any strange charges on {ACCT}[ {PERIOD}]?',
    'Did I have any abnormal transactions {PERIOD}?',
    'Are there unusual purchases {PERIOD}?',
    'Spot any unusual charges[ {PERIOD}]',
    'Show purchases that are higher than normal {PERIOD}',
    'Which transactions look unusual {PERIOD}?',
  ],
  possible_duplicates: [
    'Was I charged twice[ {PERIOD}]?',
    'Any duplicate charges {PERIOD}?',
    'Did {MER} charge me twice[ {PERIOD}]?',
    'Show possible duplicate transactions {PERIOD}',
    'Were there double charges {PERIOD}?',
    'Did I pay twice for anything {PERIOD}?',
    'Find duplicate payments[ {PERIOD}]',
    'Any repeated charges at {MER} {PERIOD}?',
    'Have I been double charged {PERIOD}?',
    'Check for duplicates[ on {ACCT}] {PERIOD}',
    'Same charge twice {PERIOD}?',
    'Did anything get charged two times[ {PERIOD}]?',
    'Duplicate purchases {PERIOD}',
    'Was {MER} billed twice {PERIOD}?',
    'Look for double payments {PERIOD}',
  ],
  recurring_changes: [
    'Which recurring charges changed[ {PERIOD}]?',
    'Did any subscriptions increase {PERIOD}?',
    'Have my subscriptions changed?',
    'Which subscriptions went up {PERIOD}?',
    'Did {MER} raise its price[ {PERIOD}]?',
    'Show changes in my recurring payments',
    'Any subscription price changes {PERIOD}?',
    'Did any recurring payments get more expensive {PERIOD}?',
    'Which memberships changed price?',
    'Recurring charges that changed {PERIOD}',
    'Did my {MER} subscription change?',
    'Have any renewals increased {PERIOD}?',
    'Show subscription changes[ {PERIOD}]',
    'Did any recurring charge decrease {PERIOD}?',
    'Price changes in my subscriptions',
  ],
  month_forecast: [
    'Am I on track[ {PERIOD}]?',
    'What will I spend by the end of the month?',
    'Forecast my spending[ {PERIOD}]',
    'How much will I have spent by month end?',
    'Projected spending[ {PERIOD}]',
    'At this rate, how much will I spend {PERIOD}?',
    "What's my spending forecast?",
    'Estimate my total spending for the month',
    'Where will my spending end up {PERIOD}?',
    'Projected {CAT} spending {PERIOD}',
    'How is my {CAT} spending tracking {PERIOD}?',
    'End of month spending estimate',
    'Predict my spending {PERIOD}',
    "What's the projection for {PERIOD!}?",
    'Am I on pace to overspend {PERIOD}?',
    'How much will I spend on {CAT} by the end of the month?',
  ],
  top_accounts: [
    'Which card did I use the most[ {PERIOD}]?',
    'Which account do I spend the most from {PERIOD}?',
    'Top {N} cards by spending {PERIOD}',
    'What card do I spend most on[ {PERIOD}]?',
    'Rank my accounts by spending {PERIOD}',
    'Which account had the most spending {PERIOD}?',
    'Which card has the highest spending[ {PERIOD}]?',
    'Top accounts {PERIOD}',
    'Which of my cards is used most for {CAT}[ {PERIOD}]?',
    'What account did I spend the most with at {MER}?',
    'My most used card {PERIOD}',
    'Which bank account did I use most {PERIOD}?',
    'Show spending by account[ {PERIOD}]',
    'Which account costs me the most {PERIOD}?',
    'Top {N} accounts[ {PERIOD}]',
  ],
  account_inventory: [
    'How many cards do I have?',
    'List my accounts',
    'What accounts do I have?',
    'Show my cards',
    'How many bank accounts do I have?',
    'Which cards do I have?',
    'Show me all my accounts',
    'What credit cards do I have?',
    'How many accounts are in Wafra?',
    'List my credit cards',
    'What cards are mine?',
    'Show my bank accounts',
    'How many credit cards have I got?',
    'Which accounts are connected?',
    'What debit cards do I have?',
    'Count my accounts',
  ],
  unknown: [
    "What's the weather tomorrow?",
    'Should I buy Tesla stock?',
    'Transfer 500 to Ahmed',
    'Send money to my brother',
    'Pay my bill now',
    'Delete all my {MER} transactions',
    'Change the category of {MER} to {CAT}',
    'Set a budget of 2000 for {CAT}',
    "What's my bank password?",
    'Tell me a joke',
    'Who won the football match?',
    'Convert 100 dollars to euros',
    "What's the price of bitcoin?",
    'Book a flight to London',
    'Can I afford a new car?',
    'Move 1000 from savings to {ACCT}',
    'Cancel my {MER} subscription',
    'Give me stock tips',
    'Pay {MER} 200 dirhams',
    'Write an email to my landlord',
    'What is the capital of France?',
    'Rename my {ACCT} account',
    'Lend me some money',
    'Open a new savings account',
    'How do I reset my PIN?',
  ],
};

const AR = {
  spending_total: [
    'g|كم صرفت على {CAT}[ {PERIOD}]؟',
    'كم أنفقت على {CAT}[ {PERIOD}]؟',
    'g|كم صرفت في {MER}[ {PERIOD}]؟',
    'كم أنفقت في {MER} {PERIOD}؟',
    'ما مجموع مصاريفي {PERIOD}؟',
    'g|كم مصروفي {PERIOD}؟',
    'كم دفعت إلى {MER}[ {PERIOD}]؟',
    'g|قد إيش صرفت على {CAT} {PERIOD}؟',
    'ما هو إنفاقي على {CAT} {PERIOD}؟',
    'g|وش صرفت {PERIOD}؟',
    'أظهر مصاريفي على {CAT}[ {PERIOD}]',
    'g|كم طلع علي {MER} {PERIOD}؟',
    'كم أنفقت[ من {ACCT}] {PERIOD}؟',
    'g|كم صرفت بالبطاقة {ACCT} {PERIOD}؟',
    'إجمالي الإنفاق {PERIOD}',
    'g|كم راح علي في {CAT}[ {PERIOD}]؟',
    'g|أبي أعرف كم صرفت على {CAT} {PERIOD}',
    'كم كانت مصروفاتي في {MER}[ {PERIOD}]؟',
  ],
  income_total: [
    'كم كان دخلي[ {PERIOD}]؟',
    'g|كم دخل علي {PERIOD}؟',
    'كم ربحت {PERIOD}؟',
    'ما إجمالي دخلي {PERIOD}؟',
    'g|كم نزل راتبي {PERIOD}؟',
    'كم استلمت من الراتب {PERIOD}؟',
    'أظهر دخلي[ {PERIOD}]',
    'g|كم جاني فلوس {PERIOD}؟',
    'كم المبلغ الذي دخل حسابي {ACCT} {PERIOD}؟',
    'ما هي إيراداتي {PERIOD}؟',
    'g|كم دخلي {PERIOD}؟',
    'كم كسبت[ {PERIOD}]؟',
    'g|وش مجموع الدخل {PERIOD}؟',
    'كم تلقيت من دخل {PERIOD}؟',
    'الدخل {PERIOD}',
    'g|كم الدخل اللي نزل في {ACCT} {PERIOD}؟',
  ],
  compare_periods: [
    'قارن {PERIOD!} مع {CMP!}',
    'g|هل صرفت {PERIOD!} أكثر من {CMP!}؟',
    'كيف يقارن إنفاقي {PERIOD!} مع {CMP!}؟',
    'g|مصاريفي {PERIOD!} مقارنة مع {CMP!}',
    'هل زاد إنفاقي على {CAT} {PERIOD}؟',
    'g|ليش زادت مصاريفي {PERIOD}؟',
    'لماذا تغير إنفاقي {PERIOD}؟',
    'g|صرفي على {CAT} {PERIOD!} ولا {CMP!} أكثر؟',
    'الفرق بين إنفاقي {PERIOD!} مقابل {CMP!}',
    'هل أنفقت أقل على {CAT} {PERIOD!} مقارنة مع {CMP!}؟',
    'g|هل مصروفي زاد؟',
    'هل ارتفع إنفاقي مقارنة مع {CMP!}؟',
    'g|قارن صرفي في {MER} {PERIOD!} مع {CMP!}',
    'هل انخفض إنفاقي {PERIOD}؟',
    'g|وش الفرق بين {PERIOD!} و {CMP!}؟',
    'هل تغيرت مصاريفي على {CAT}؟',
  ],
  top_merchants: [
    'ما هي أكثر {N} متاجر صرفت فيها[ {PERIOD}]؟',
    'g|وين أكثر مكان صرفت فيه {PERIOD}؟',
    'أين أنفقت أكثر[ {PERIOD}]؟',
    'g|أكثر المحلات اللي صرفت فيها {PERIOD}',
    'أعلى {N} تجار من حيث الإنفاق {PERIOD}',
    'ما المتجر الذي أنفقت فيه أكثر {PERIOD}؟',
    'g|وش أكثر محل أخذ فلوسي {PERIOD}؟',
    'رتب المتاجر حسب الإنفاق[ {PERIOD}]',
    'g|أكثر {N} محلات صرفت فيها',
    'أكبر التجار {PERIOD}',
    'أين أنفقت أكثر على {CAT} {PERIOD}؟',
    'g|وين أصرف أكثر شي؟',
    'قائمة بأكثر المتاجر إنفاقاً[ {PERIOD}]',
    'g|مين أكثر تاجر صرفت عنده {PERIOD}؟',
    'أعلى المتاجر في {CAT}[ {PERIOD}]',
  ],
  top_categories: [
    'g|وش أكثر شي صرفت عليه[ {PERIOD}]؟',
    'على ماذا أنفقت أكثر {PERIOD}؟',
    'أين ذهبت أموالي[ {PERIOD}]؟',
    'g|وين راحت فلوسي {PERIOD}؟',
    'ما هي أعلى {N} فئات إنفاق {PERIOD}؟',
    'فئات الإنفاق الأعلى {PERIOD}',
    'g|أكثر الفئات اللي صرفت عليها {PERIOD}',
    'وزع إنفاقي حسب الفئة[ {PERIOD}]',
    'ما الفئة التي أنفقت عليها أكثر {PERIOD}؟',
    'g|وين تروح فلوسي؟',
    'أكبر {N} فئات {PERIOD}',
    'أظهر الإنفاق حسب الفئة {PERIOD}',
    'g|على إيش أصرف أكثر؟',
    'ترتيب الفئات حسب الإنفاق {PERIOD}',
    'ما أكثر بنود الصرف {PERIOD}؟',
  ],
  largest_purchases: [
    'ما هي أكبر مشترياتي[ {PERIOD}]؟',
    'g|وش أغلى شي اشتريته {PERIOD}؟',
    'أكبر {N} عمليات شراء {PERIOD}',
    'أعلى المعاملات {PERIOD}',
    'g|أكبر مبلغ صرفته {PERIOD}',
    'أظهر أكبر {N} معاملات[ {PERIOD}]',
    'ما أغلى عملية شراء على {CAT} {PERIOD}؟',
    'g|أكبر مشترياتي من {MER}[ {PERIOD}]',
    'أكبر عمليات الشراء من {ACCT} {PERIOD}',
    'g|وش أكبر {N} مشتريات {PERIOD}؟',
    'ما هي أغلى المعاملات {PERIOD}؟',
    'أكبر المصاريف الفردية[ {PERIOD}]',
    'g|طلع لي أكبر المشتريات {PERIOD}',
    'اعرض أكبر {N} مشتريات على {CAT}',
    'ما أكبر معاملة {PERIOD}؟',
  ],
  daily_average: [
    'ما متوسط إنفاقي اليومي[ {PERIOD}]؟',
    'g|كم أصرف في اليوم {PERIOD}؟',
    'متوسط الصرف اليومي {PERIOD}',
    'g|كم معدل صرفي باليوم {PERIOD}؟',
    'كم أنفق يومياً[ {PERIOD}]؟',
    'المعدل اليومي لإنفاقي على {CAT} {PERIOD}',
    'g|كم أصرف كل يوم على {CAT}؟',
    'ما هو معدل الإنفاق اليومي {PERIOD}؟',
    'g|معدل صرفي اليومي في {MER} {PERIOD}',
    'متوسط المصروف لكل يوم {PERIOD}',
    'كم يبلغ إنفاقي اليومي[ من {ACCT}]؟',
    'g|كم أصرف باليوم تقريباً؟',
    'احسب متوسط إنفاقي اليومي {PERIOD}',
    'كم أنفق في المتوسط يومياً {PERIOD}؟',
    'g|وش معدل مصروفي اليومي[ {PERIOD}]؟',
  ],
  net_income_spending: [
    'هل أنفقت أكثر مما كسبت[ {PERIOD}]؟',
    'g|صرفت أكثر من دخلي {PERIOD}؟',
    'ما صافي دخلي بعد المصاريف {PERIOD}؟',
    'الدخل ناقص المصاريف {PERIOD}',
    'g|كم الفرق بين دخلي ومصروفي {PERIOD}؟',
    'هل دخلي أكبر من إنفاقي {PERIOD}؟',
    'g|أنا بالموجب ولا بالسالب {PERIOD}؟',
    'صافي التدفق النقدي {PERIOD}',
    'قارن دخلي مع مصاريفي[ {PERIOD}]',
    'g|دخلي مقابل صرفي {PERIOD}',
    'هل تجاوز إنفاقي دخلي {PERIOD}؟',
    'الفرق بين الدخل والإنفاق[ {PERIOD}]',
    'g|كسبت أكثر ولا صرفت أكثر {PERIOD}؟',
    'ما هو صافي الإنفاق {PERIOD}؟',
    'هل أصرف أكثر مما أكسب؟',
  ],
  subscriptions: [
    'ما هي اشتراكاتي؟',
    'g|وش الاشتراكات اللي عندي؟',
    'أظهر اشتراكاتي النشطة',
    'كم تكلفني الاشتراكات؟',
    'g|كم أدفع على الاشتراكات كل شهر؟',
    'ما الخدمات التي أدفع لها شهرياً؟',
    'g|عطني قائمة الاشتراكات',
    'هل لدي أي اشتراكات؟',
    'ما هي المدفوعات المتكررة؟',
    'g|وش الأشياء اللي تنسحب مني كل شهر؟',
    'اعرض الاشتراكات الشهرية',
    'قائمة العضويات الخاصة بي',
    'g|عندي اشتراكات؟',
    'ما هي الرسوم المتكررة لدي؟',
    'أظهر كل اشتراكاتي',
  ],
  upcoming_payments: [
    'ما هي الدفعات المستحقة قريباً؟',
    'g|وش الفواتير اللي علي قريب؟',
    'هل لدي فواتير مستحقة؟',
    'ما المدفوعات القادمة؟',
    'g|وش لازم أدفع قريب؟',
    'أظهر الفواتير القادمة',
    'ما الذي يستحق الدفع؟',
    'g|فيه شي مستحق علي؟',
    'قائمة الدفعات القادمة',
    'متى موعد الدفعات القادمة؟',
    'g|وش المستحقات اللي جاية؟',
    'هل هناك مبالغ مستحقة قريباً؟',
    'ما هي الفواتير المستحقة؟',
    'g|عطني المدفوعات الجاية',
    'ماذا علي أن أدفع قريباً؟',
  ],
  unusual_charges: [
    'هل هناك رسوم غير عادية[ {PERIOD}]؟',
    'g|فيه مصاريف غريبة {PERIOD}؟',
    'أظهر المعاملات غير المعتادة {PERIOD}',
    'هل توجد مشتريات مرتفعة بشكل غير طبيعي {PERIOD}؟',
    'g|فيه شي غريب في {MER}[ {PERIOD}]؟',
    'المعاملات الشاذة {PERIOD}',
    'g|طلع لي المصاريف الغريبة[ {PERIOD}]',
    'هل هناك عمليات غير مألوفة على {ACCT} {PERIOD}؟',
    'ما هي المشتريات غير العادية {PERIOD}؟',
    'g|فيه خصومات غريبة علي {PERIOD}؟',
    'اكتشف الرسوم غير الطبيعية[ {PERIOD}]',
    'هل كانت هناك مصاريف أعلى من المعتاد {PERIOD}؟',
    'g|وش المصاريف اللي مو طبيعية {PERIOD}؟',
    'معاملات غير اعتيادية {PERIOD}',
    'هل لاحظت أي رسوم غريبة[ {PERIOD}]؟',
  ],
  possible_duplicates: [
    'هل تم خصم مبلغ مرتين[ {PERIOD}]؟',
    'g|انخصم مني مرتين {PERIOD}؟',
    'هل هناك رسوم مكررة {PERIOD}؟',
    'g|هل {MER} خصم مني مرتين {PERIOD}؟',
    'أظهر المعاملات المكررة المحتملة {PERIOD}',
    'هل دفعت مرتين لأي شيء[ {PERIOD}]؟',
    'g|فيه عمليات مكررة {PERIOD}؟',
    'ابحث عن المدفوعات المكررة[ {PERIOD}]',
    'هل هناك خصم مزدوج على {ACCT} {PERIOD}؟',
    'g|دفعت نفس المبلغ مرتين {PERIOD}؟',
    'المعاملات المكررة {PERIOD}',
    'هل تكرر خصم {MER}[ {PERIOD}]؟',
    'g|شيك لي إذا فيه تكرار في المدفوعات {PERIOD}',
    'هل تم احتساب أي عملية مرتين {PERIOD}؟',
    'رسوم مزدوجة[ {PERIOD}]',
  ],
  recurring_changes: [
    'أي الرسوم المتكررة تغيرت[ {PERIOD}]؟',
    'g|فيه اشتراكات زاد سعرها {PERIOD}؟',
    'هل تغيرت اشتراكاتي؟',
    'هل رفع {MER} السعر[ {PERIOD}]؟',
    'g|وش الاشتراكات اللي تغيرت؟',
    'أظهر التغييرات في المدفوعات المتكررة {PERIOD}',
    'هل زادت أي اشتراكات {PERIOD}؟',
    'g|اشتراك {MER} تغير؟',
    'تغيرات أسعار الاشتراكات[ {PERIOD}]',
    'هل انخفض أي اشتراك {PERIOD}؟',
    'g|فيه مدفوعات متكررة صارت أغلى {PERIOD}؟',
    'ما المدفوعات المتكررة التي تغيرت؟',
    'هل تغيرت قيمة التجديدات {PERIOD}؟',
    'g|أي اشتراك غلا علي[ {PERIOD}]؟',
    'تغيرات الرسوم الشهرية المتكررة',
  ],
  month_forecast: [
    'هل أنا على المسار الصحيح[ {PERIOD}]؟',
    'g|كم بصرف لين آخر الشهر؟',
    'ما توقع إنفاقي[ {PERIOD}]؟',
    'كم سأنفق بنهاية الشهر؟',
    'g|على هالمعدل كم بيطلع مصروفي {PERIOD}؟',
    'الإنفاق المتوقع {PERIOD}',
    'توقع مصاريفي على {CAT}[ {PERIOD}]',
    'g|بكم بخلص الشهر؟',
    'تقدير إجمالي الإنفاق حتى نهاية الشهر',
    'كيف يسير إنفاقي على {CAT} {PERIOD}؟',
    'g|وش توقعك لمصروفي {PERIOD}؟',
    'ما هو الإنفاق المتوقع حتى نهاية الشهر؟',
    'كم سيكون إنفاقي في {MER} بنهاية الشهر؟',
    'g|كم متوقع أصرف على {CAT} {PERIOD}؟',
    'توقعات الإنفاق الشهري',
    'g|مصروفي ماشي صح {PERIOD}؟',
  ],
  top_accounts: [
    'أي بطاقة استخدمتها أكثر[ {PERIOD}]؟',
    'g|وش أكثر كرت صرفت منه {PERIOD}؟',
    'ما الحساب الذي أنفقت منه أكثر {PERIOD}؟',
    'رتب حساباتي حسب الإنفاق[ {PERIOD}]',
    'g|أي حساب أصرف منه أكثر شي؟',
    'أعلى {N} بطاقات من حيث الإنفاق {PERIOD}',
    'أي بطاقة عليها أعلى إنفاق {PERIOD}؟',
    'g|أكثر بطاقة استخدمتها في {CAT}[ {PERIOD}]',
    'الحسابات الأكثر استخداماً {PERIOD}',
    'أي بطاقة استخدمت أكثر في {MER}؟',
    'g|وش الحساب اللي طلع منه أكثر فلوس {PERIOD}؟',
    'أظهر الإنفاق حسب الحساب[ {PERIOD}]',
    'أي حساب بنكي استخدمته أكثر {PERIOD}؟',
    'g|أكثر {N} حسابات صرفت منها',
    'ما البطاقة الأكثر إنفاقاً {PERIOD}؟',
  ],
  account_inventory: [
    'كم بطاقة لدي؟',
    'g|كم كرت عندي؟',
    'ما هي حساباتي؟',
    'أظهر بطاقاتي',
    'g|وش الحسابات اللي عندي؟',
    'كم حساباً بنكياً لدي؟',
    'اعرض كل حساباتي',
    'g|عطني قائمة البطاقات',
    'ما البطاقات الائتمانية التي أملكها؟',
    'كم عدد حساباتي؟',
    'g|كم حساب مسجل عندي؟',
    'قائمة الحسابات البنكية',
    'ما هي البطاقات المسجلة؟',
    'g|وريني حساباتي',
    'كم بطاقة ائتمان لدي؟',
  ],
  unknown: [
    'g|كيف الطقس بكرة؟',
    'هل أشتري سهم أرامكو؟',
    'حول 500 درهم إلى أحمد',
    'g|حول فلوس لأخوي',
    'ادفع الفاتورة الآن',
    'احذف كل معاملات {MER}',
    'g|غير تصنيف {MER} إلى {CAT}',
    'ضع ميزانية 2000 على {CAT}',
    'ما هي كلمة سر حسابي؟',
    'g|قول لي نكتة',
    'من فاز بالمباراة؟',
    'كم سعر البيتكوين؟',
    'g|احجز لي رحلة إلى لندن',
    'هل أقدر أشتري سيارة جديدة؟',
    'انقل 1000 من حسابي إلى {ACCT}',
    'g|ألغ اشتراكي في {MER}',
    'ادفع إلى {MER} 200 ريال',
    'اكتب رسالة لصاحب البيت',
    'g|وش أحسن سهم أشتريه؟',
    'افتح حساب توفير جديد',
    'g|سلفني فلوس',
    'كيف أغير الرقم السري؟',
    'ما عاصمة فرنسا؟',
  ],
};

const ES = {
  spending_total: ['¿Cuánto gasté en {CAT}[ {PERIOD}]?', '¿Cuánto he gastado en {MER}[ {PERIOD}]?', '¿Cuánto gasté {PERIOD}[ con {ACCT}]?',
    'Gasto total en {CAT} {PERIOD}', '¿Cuánto dinero se fue en {MER} {PERIOD}?', 'Muéstrame mis gastos {PERIOD}'],
  income_total: ['¿Cuánto gané[ {PERIOD}]?', '¿Cuáles fueron mis ingresos {PERIOD}?', '¿Cuánto dinero recibí {PERIOD}?',
    'Ingresos totales {PERIOD}', '¿Cuánto cobré de sueldo {PERIOD}?', '¿Cuánto entró en {ACCT} {PERIOD}?'],
  compare_periods: ['Compara {PERIOD!} con {CMP!}', '¿Gasté más {PERIOD!} que {CMP!}?', '¿Aumentó mi gasto en {CAT} {PERIOD}?',
    '¿Por qué cambió mi gasto {PERIOD}?', 'Gastos de {PERIOD!} comparado con {CMP!}', '¿Gasto más en {MER} {PERIOD!} que {CMP!}?'],
  top_merchants: ['¿Cuáles son mis {N} comercios principales[ {PERIOD}]?', '¿Dónde gasto más[ {PERIOD}]?', 'Top {N} tiendas {PERIOD}',
    '¿En qué comercio gasté más {PERIOD}?', 'Comercios donde más gasté en {CAT}[ {PERIOD}]', 'Ranking de comercios por gasto {PERIOD}'],
  top_categories: ['¿En qué gasté más[ {PERIOD}]?', '¿A dónde se fue mi dinero {PERIOD}?', 'Mis {N} categorías principales {PERIOD}',
    'Gastos por categoría[ {PERIOD}]', '¿Cuál es la categoría con más gasto {PERIOD}?', '¿En qué se me va el dinero?'],
  largest_purchases: ['¿Cuáles fueron mis compras más grandes[ {PERIOD}]?', 'Mis {N} compras más caras {PERIOD}', 'Transacciones más grandes {PERIOD}',
    '¿Cuál fue la compra más cara en {MER}[ {PERIOD}]?', 'Las mayores compras de {CAT} {PERIOD}', '¿Qué fue lo más caro que compré {PERIOD}?'],
  daily_average: ['¿Cuánto gasto al día[ {PERIOD}]?', 'Promedio de gasto diario {PERIOD}', '¿Cuál es mi gasto medio por día {PERIOD}?',
    '¿Cuánto gasto diario en {CAT}[ {PERIOD}]?', 'Gasto promedio por día en {MER} {PERIOD}', 'Media diaria de gastos[ {PERIOD}]'],
  net_income_spending: ['¿Gasté más de lo que gané[ {PERIOD}]?', 'Ingresos menos gastos {PERIOD}', '¿Cuál es mi balance neto {PERIOD}?',
    '¿Gané más de lo que gasté {PERIOD}?', 'Diferencia entre ingresos y gastos[ {PERIOD}]', '¿Estoy gastando más de lo que ingreso?'],
  subscriptions: ['¿Qué suscripciones tengo?', 'Muéstrame mis suscripciones activas', '¿Cuánto me cuestan las suscripciones?',
    '¿Qué pagos recurrentes tengo?', '¿A qué servicios estoy suscrito?', 'Lista de mis suscripciones'],
  upcoming_payments: ['¿Qué pagos vencen pronto?', '¿Tengo facturas pendientes?', 'Próximos pagos',
    '¿Qué tengo que pagar pronto?', '¿Qué recibos vienen?', 'Muéstrame los pagos que vencen'],
  unusual_charges: ['¿Hay cargos inusuales[ {PERIOD}]?', 'Muéstrame transacciones raras {PERIOD}', '¿Algún gasto fuera de lo normal {PERIOD}?',
    '¿Hubo algo inusual en {MER}[ {PERIOD}]?', 'Compras anormalmente altas {PERIOD}', '¿Cargos extraños en {ACCT} {PERIOD}?'],
  possible_duplicates: ['¿Me cobraron dos veces[ {PERIOD}]?', '¿Hay cargos duplicados {PERIOD}?', '¿{MER} me cobró dos veces {PERIOD}?',
    'Buscar pagos duplicados[ {PERIOD}]', '¿Pagué algo dos veces {PERIOD}?', 'Cobros repetidos en {ACCT}[ {PERIOD}]'],
  recurring_changes: ['¿Qué cargos recurrentes cambiaron[ {PERIOD}]?', '¿Subió el precio de alguna suscripción {PERIOD}?', '¿{MER} subió su precio?',
    'Cambios en mis suscripciones[ {PERIOD}]', '¿Alguna suscripción bajó {PERIOD}?', '¿Han cambiado mis pagos recurrentes?'],
  month_forecast: ['¿Voy bien de gastos[ {PERIOD}]?', '¿Cuánto habré gastado a fin de mes?', 'Previsión de gastos[ {PERIOD}]',
    '¿Cuánto voy a gastar en {CAT} a fin de mes?', 'Gasto proyectado {PERIOD}', 'A este ritmo, ¿cuánto gastaré {PERIOD}?'],
  top_accounts: ['¿Qué tarjeta usé más[ {PERIOD}]?', '¿Con qué cuenta gasto más {PERIOD}?', 'Top {N} tarjetas por gasto {PERIOD}',
    'Ordena mis cuentas por gasto[ {PERIOD}]', '¿Qué tarjeta uso más para {CAT}?', '¿Qué cuenta tuvo más gastos {PERIOD}?'],
  account_inventory: ['¿Cuántas tarjetas tengo?', '¿Qué cuentas tengo?', 'Muéstrame mis tarjetas',
    'Lista de mis cuentas', '¿Cuántas cuentas bancarias tengo?', '¿Qué tarjetas de crédito tengo?'],
  unknown: ['¿Qué tiempo hará mañana?', 'Transfiere 200 euros a Juan', '¿Debería comprar acciones de Tesla?', 'Borra mis transacciones de {MER}',
    'Cambia la categoría de {MER} a {CAT}', 'Cuéntame un chiste', 'Paga mi factura ahora', '¿Cuál es el precio del bitcoin?'],
};

const PT = {
  spending_total: ['Quanto gastei com {CAT}[ {PERIOD}]?', 'Quanto gastei no {MER}[ {PERIOD}]?', 'Quanto eu gastei {PERIOD}[ com o {ACCT}]?',
    'Gasto total com {CAT} {PERIOD}', 'Quanto dinheiro foi para o {MER} {PERIOD}?', 'Mostra meus gastos {PERIOD}'],
  income_total: ['Quanto eu ganhei[ {PERIOD}]?', 'Qual foi minha renda {PERIOD}?', 'Quanto dinheiro recebi {PERIOD}?',
    'Receita total {PERIOD}', 'Quanto caiu de salário {PERIOD}?', 'Quanto entrou na conta {ACCT} {PERIOD}?'],
  compare_periods: ['Compare {PERIOD!} com {CMP!}', 'Gastei mais {PERIOD!} do que {CMP!}?', 'Meus gastos com {CAT} aumentaram {PERIOD}?',
    'Por que meus gastos mudaram {PERIOD}?', 'Gastos {PERIOD!} em comparação com {CMP!}', 'Gastei mais no {MER} {PERIOD!} do que {CMP!}?'],
  top_merchants: ['Quais são minhas {N} lojas principais[ {PERIOD}]?', 'Onde eu gasto mais[ {PERIOD}]?', 'Top {N} estabelecimentos {PERIOD}',
    'Em qual loja gastei mais {PERIOD}?', 'Onde gastei mais com {CAT}[ {PERIOD}]?', 'Ranking de lojas por gasto {PERIOD}'],
  top_categories: ['Com o que gastei mais[ {PERIOD}]?', 'Para onde foi meu dinheiro {PERIOD}?', 'Minhas {N} principais categorias {PERIOD}',
    'Gastos por categoria[ {PERIOD}]', 'Qual categoria teve mais gasto {PERIOD}?', 'Com o que eu mais gasto?'],
  largest_purchases: ['Quais foram minhas maiores compras[ {PERIOD}]?', 'Minhas {N} compras mais caras {PERIOD}', 'Maiores transações {PERIOD}',
    'Qual foi a compra mais cara no {MER}[ {PERIOD}]?', 'Maiores compras de {CAT} {PERIOD}', 'O que comprei de mais caro {PERIOD}?'],
  daily_average: ['Quanto gasto por dia[ {PERIOD}]?', 'Média de gasto diário {PERIOD}', 'Qual é meu gasto médio por dia {PERIOD}?',
    'Quanto gasto por dia com {CAT}[ {PERIOD}]?', 'Gasto médio diário no {MER} {PERIOD}', 'Média diária de despesas[ {PERIOD}]'],
  net_income_spending: ['Gastei mais do que ganhei[ {PERIOD}]?', 'Receitas menos despesas {PERIOD}', 'Qual é meu saldo líquido {PERIOD}?',
    'Ganhei mais do que gastei {PERIOD}?', 'Diferença entre renda e gastos[ {PERIOD}]', 'Estou gastando mais do que ganho?'],
  subscriptions: ['Quais assinaturas eu tenho?', 'Mostra minhas assinaturas ativas', 'Quanto custam minhas assinaturas?',
    'Quais pagamentos recorrentes eu tenho?', 'Em quais serviços estou inscrito?', 'Lista das minhas assinaturas'],
  upcoming_payments: ['Quais pagamentos vencem em breve?', 'Tenho contas a pagar?', 'Próximos pagamentos',
    'O que preciso pagar em breve?', 'Quais boletos estão chegando?', 'Mostra os pagamentos que vão vencer'],
  unusual_charges: ['Há cobranças incomuns[ {PERIOD}]?', 'Mostra transações estranhas {PERIOD}', 'Algum gasto fora do normal {PERIOD}?',
    'Teve algo incomum no {MER}[ {PERIOD}]?', 'Compras anormalmente altas {PERIOD}', 'Cobranças estranhas no {ACCT} {PERIOD}?'],
  possible_duplicates: ['Fui cobrado duas vezes[ {PERIOD}]?', 'Há cobranças duplicadas {PERIOD}?', 'O {MER} me cobrou duas vezes {PERIOD}?',
    'Procurar pagamentos duplicados[ {PERIOD}]', 'Paguei algo em dobro {PERIOD}?', 'Cobranças repetidas no {ACCT}[ {PERIOD}]'],
  recurring_changes: ['Quais cobranças recorrentes mudaram[ {PERIOD}]?', 'Alguma assinatura ficou mais cara {PERIOD}?', 'O {MER} aumentou o preço?',
    'Mudanças nas minhas assinaturas[ {PERIOD}]', 'Alguma assinatura baixou {PERIOD}?', 'Meus pagamentos recorrentes mudaram?'],
  month_forecast: ['Estou no caminho certo[ {PERIOD}]?', 'Quanto vou ter gasto no fim do mês?', 'Previsão de gastos[ {PERIOD}]',
    'Quanto vou gastar com {CAT} até o fim do mês?', 'Gasto projetado {PERIOD}', 'Nesse ritmo, quanto vou gastar {PERIOD}?'],
  top_accounts: ['Qual cartão usei mais[ {PERIOD}]?', 'Com qual conta gasto mais {PERIOD}?', 'Top {N} cartões por gasto {PERIOD}',
    'Ordene minhas contas por gasto[ {PERIOD}]', 'Qual cartão uso mais para {CAT}?', 'Qual conta teve mais gastos {PERIOD}?'],
  account_inventory: ['Quantos cartões eu tenho?', 'Quais contas eu tenho?', 'Mostra meus cartões',
    'Lista das minhas contas', 'Quantas contas bancárias eu tenho?', 'Quais cartões de crédito eu tenho?'],
  unknown: ['Como vai estar o tempo amanhã?', 'Transfere 100 reais para o João', 'Devo comprar ações da Petrobras?', 'Apaga minhas transações do {MER}',
    'Muda a categoria do {MER} para {CAT}', 'Me conta uma piada', 'Paga meu boleto agora', 'Qual o preço do bitcoin?'],
};

const FR = {
  spending_total: ["Combien j'ai dépensé en {CAT}[ {PERIOD}] ?", 'Combien ai-je dépensé chez {MER}[ {PERIOD}] ?', "Combien j'ai dépensé {PERIOD}[ avec {ACCT}] ?",
    'Dépenses totales en {CAT} {PERIOD}', "Combien d'argent est parti chez {MER} {PERIOD} ?", 'Montre-moi mes dépenses {PERIOD}'],
  income_total: ["Combien j'ai gagné[ {PERIOD}] ?", 'Quels ont été mes revenus {PERIOD} ?', "Combien d'argent ai-je reçu {PERIOD} ?",
    'Revenus totaux {PERIOD}', "Combien de salaire j'ai touché {PERIOD} ?", 'Combien est entré sur {ACCT} {PERIOD} ?'],
  compare_periods: ['Compare {PERIOD!} avec {CMP!}', 'Ai-je plus dépensé {PERIOD} que {CMP} ?', 'Mes dépenses en {CAT} ont-elles augmenté {PERIOD} ?',
    'Pourquoi mes dépenses ont changé {PERIOD} ?', 'Dépenses : {PERIOD!} contre {CMP!}', 'Est-ce que je dépense plus chez {MER} {PERIOD} que {CMP} ?'],
  top_merchants: ['Quels sont mes {N} principaux commerçants[ {PERIOD}] ?', "Où est-ce que je dépense le plus[ {PERIOD}] ?", 'Top {N} magasins {PERIOD}',
    'Dans quel magasin ai-je le plus dépensé {PERIOD} ?', 'Où ai-je le plus dépensé en {CAT}[ {PERIOD}] ?', 'Classement des commerçants par dépenses {PERIOD}'],
  top_categories: ['Pour quoi ai-je le plus dépensé[ {PERIOD}] ?', 'Où est passé mon argent {PERIOD} ?', 'Mes {N} catégories principales {PERIOD}',
    'Dépenses par catégorie[ {PERIOD}]', "Quelle catégorie m'a coûté le plus {PERIOD} ?", 'Dans quoi part mon argent ?'],
  largest_purchases: ['Quels ont été mes plus gros achats[ {PERIOD}] ?', 'Mes {N} achats les plus chers {PERIOD}', 'Plus grosses transactions {PERIOD}',
    "Quel a été l'achat le plus cher chez {MER}[ {PERIOD}] ?", 'Plus gros achats en {CAT} {PERIOD}', "Qu'est-ce que j'ai acheté de plus cher {PERIOD} ?"],
  daily_average: ['Combien je dépense par jour[ {PERIOD}] ?', 'Moyenne de dépenses quotidiennes {PERIOD}', 'Quelle est ma dépense moyenne par jour {PERIOD} ?',
    'Combien je dépense par jour en {CAT}[ {PERIOD}] ?', 'Dépense moyenne quotidienne chez {MER} {PERIOD}', 'Moyenne journalière[ {PERIOD}]'],
  net_income_spending: ["Ai-je dépensé plus que ce que j'ai gagné[ {PERIOD}] ?", 'Revenus moins dépenses {PERIOD}', 'Quel est mon solde net {PERIOD} ?',
    "Ai-je gagné plus que j'ai dépensé {PERIOD} ?", 'Différence entre revenus et dépenses[ {PERIOD}]', 'Est-ce que je dépense plus que je gagne ?'],
  subscriptions: ['Quels abonnements ai-je ?', 'Montre mes abonnements actifs', 'Combien me coûtent mes abonnements ?',
    'Quels paiements récurrents ai-je ?', 'À quels services suis-je abonné ?', 'Liste de mes abonnements'],
  upcoming_payments: ['Quels paiements arrivent bientôt ?', 'Ai-je des factures à payer ?', 'Prochains paiements',
    "Qu'est-ce que je dois payer bientôt ?", 'Quelles échéances arrivent ?', 'Montre les paiements à venir'],
  unusual_charges: ['Y a-t-il des frais inhabituels[ {PERIOD}] ?', 'Montre les transactions bizarres {PERIOD}', 'Des dépenses anormales {PERIOD} ?',
    "Quelque chose d'inhabituel chez {MER}[ {PERIOD}] ?", 'Achats anormalement élevés {PERIOD}', 'Des débits étranges sur {ACCT} {PERIOD} ?'],
  possible_duplicates: ['Ai-je été débité deux fois[ {PERIOD}] ?', 'Y a-t-il des doublons {PERIOD} ?', "Est-ce que {MER} m'a débité deux fois {PERIOD} ?",
    'Chercher les paiements en double[ {PERIOD}]', 'Ai-je payé quelque chose deux fois {PERIOD} ?', 'Débits répétés sur {ACCT}[ {PERIOD}]'],
  recurring_changes: ['Quels prélèvements récurrents ont changé[ {PERIOD}] ?', 'Un abonnement a-t-il augmenté {PERIOD} ?', 'Est-ce que {MER} a augmenté son prix ?',
    'Changements dans mes abonnements[ {PERIOD}]', 'Un abonnement a-t-il baissé {PERIOD} ?', 'Mes paiements récurrents ont-ils changé ?'],
  month_forecast: ['Est-ce que je suis dans les clous[ {PERIOD}] ?', "Combien j'aurai dépensé à la fin du mois ?", 'Prévision de dépenses[ {PERIOD}]',
    "Combien vais-je dépenser en {CAT} d'ici la fin du mois ?", 'Dépenses projetées {PERIOD}', 'À ce rythme, combien vais-je dépenser {PERIOD} ?'],
  top_accounts: ['Quelle carte ai-je le plus utilisée[ {PERIOD}] ?', 'Avec quel compte je dépense le plus {PERIOD} ?', 'Top {N} cartes par dépenses {PERIOD}',
    'Classe mes comptes par dépenses[ {PERIOD}]', "Quelle carte j'utilise le plus pour {CAT} ?", 'Quel compte a eu le plus de dépenses {PERIOD} ?'],
  account_inventory: ['Combien de cartes ai-je ?', 'Quels comptes ai-je ?', 'Montre mes cartes',
    'Liste de mes comptes', "Combien de comptes bancaires j'ai ?", 'Quelles cartes de crédit ai-je ?'],
  unknown: ['Quel temps fera-t-il demain ?', 'Vire 100 euros à Pierre', 'Dois-je acheter des actions Tesla ?', 'Supprime mes transactions {MER}',
    'Change la catégorie de {MER} en {CAT}', 'Raconte-moi une blague', 'Paie ma facture maintenant', 'Quel est le cours du bitcoin ?'],
};

const DE = {
  spending_total: ['Wie viel habe ich[ {PERIOD}] für {CAT} ausgegeben?', 'Wie viel habe ich[ {PERIOD}] bei {MER} ausgegeben?', 'Was habe ich {PERIOD}[ mit {ACCT}] ausgegeben?',
    'Gesamtausgaben für {CAT} {PERIOD}', 'Wie viel Geld ging {PERIOD} an {MER}?', 'Zeig mir meine Ausgaben {PERIOD}'],
  income_total: ['Wie viel habe ich[ {PERIOD}] verdient?', 'Wie hoch war mein Einkommen {PERIOD}?', 'Wie viel Geld habe ich {PERIOD} erhalten?',
    'Gesamteinnahmen {PERIOD}', 'Wie viel Gehalt kam {PERIOD} rein?', 'Wie viel ging {PERIOD} auf {ACCT} ein?'],
  compare_periods: ['Vergleiche {PERIOD!} mit {CMP!}', 'Habe ich {PERIOD} mehr ausgegeben als {CMP}?', 'Sind meine Ausgaben für {CAT} {PERIOD} gestiegen?',
    'Warum haben sich meine Ausgaben {PERIOD} verändert?', 'Ausgaben {PERIOD!} gegenüber {CMP!}', 'Gebe ich bei {MER} {PERIOD} mehr aus als {CMP}?'],
  top_merchants: ['Was sind meine Top {N} Händler[ {PERIOD}]?', 'Wo gebe ich[ {PERIOD}] am meisten aus?', 'Top {N} Geschäfte {PERIOD}',
    'Bei welchem Händler habe ich {PERIOD} am meisten ausgegeben?', 'Wo habe ich[ {PERIOD}] am meisten für {CAT} ausgegeben?', 'Rangliste der Händler nach Ausgaben {PERIOD}'],
  top_categories: ['Wofür habe ich[ {PERIOD}] am meisten ausgegeben?', 'Wohin ist mein Geld {PERIOD} gegangen?', 'Meine Top {N} Kategorien {PERIOD}',
    'Ausgaben nach Kategorie[ {PERIOD}]', 'Welche Kategorie hat {PERIOD} am meisten gekostet?', 'Wofür gebe ich das meiste Geld aus?'],
  largest_purchases: ['Was waren meine größten Einkäufe[ {PERIOD}]?', 'Meine {N} teuersten Käufe {PERIOD}', 'Größte Transaktionen {PERIOD}',
    'Was war der teuerste Kauf bei {MER}[ {PERIOD}]?', 'Größte Ausgaben für {CAT} {PERIOD}', 'Was habe ich {PERIOD} Teuerstes gekauft?'],
  daily_average: ['Wie viel gebe ich[ {PERIOD}] pro Tag aus?', 'Durchschnittliche Tagesausgaben {PERIOD}', 'Was sind meine durchschnittlichen Ausgaben pro Tag {PERIOD}?',
    'Wie viel gebe ich täglich für {CAT} aus?', 'Tagesdurchschnitt bei {MER} {PERIOD}', 'Täglicher Durchschnitt[ {PERIOD}]'],
  net_income_spending: ['Habe ich[ {PERIOD}] mehr ausgegeben als verdient?', 'Einnahmen minus Ausgaben {PERIOD}', 'Wie sieht mein Nettosaldo {PERIOD} aus?',
    'Habe ich {PERIOD} mehr verdient als ausgegeben?', 'Differenz zwischen Einnahmen und Ausgaben[ {PERIOD}]', 'Gebe ich mehr aus, als ich verdiene?'],
  subscriptions: ['Welche Abos habe ich?', 'Zeig meine aktiven Abonnements', 'Wie viel kosten meine Abos?',
    'Welche wiederkehrenden Zahlungen habe ich?', 'Welche Dienste habe ich abonniert?', 'Liste meiner Abonnements'],
  upcoming_payments: ['Welche Zahlungen sind bald fällig?', 'Habe ich offene Rechnungen?', 'Anstehende Zahlungen',
    'Was muss ich bald bezahlen?', 'Welche Rechnungen kommen demnächst?', 'Zeig mir die fälligen Zahlungen'],
  unusual_charges: ['Gibt es ungewöhnliche Abbuchungen[ {PERIOD}]?', 'Zeig mir seltsame Transaktionen {PERIOD}', 'Irgendwelche auffälligen Ausgaben {PERIOD}?',
    'War bei {MER}[ {PERIOD}] etwas ungewöhnlich?', 'Ungewöhnlich hohe Käufe {PERIOD}', 'Seltsame Belastungen auf {ACCT} {PERIOD}?'],
  possible_duplicates: ['Wurde ich[ {PERIOD}] doppelt belastet?', 'Gibt es doppelte Abbuchungen {PERIOD}?', 'Hat {MER} {PERIOD} doppelt abgebucht?',
    'Doppelte Zahlungen suchen[ {PERIOD}]', 'Habe ich {PERIOD} etwas zweimal bezahlt?', 'Wiederholte Abbuchungen auf {ACCT}[ {PERIOD}]'],
  recurring_changes: ['Welche wiederkehrenden Zahlungen haben sich[ {PERIOD}] geändert?', 'Ist ein Abo {PERIOD} teurer geworden?', 'Hat {MER} den Preis erhöht?',
    'Änderungen bei meinen Abos[ {PERIOD}]', 'Ist ein Abo {PERIOD} günstiger geworden?', 'Haben sich meine Daueraufträge geändert?'],
  month_forecast: ['Bin ich[ {PERIOD}] im Plan?', 'Wie viel werde ich bis Monatsende ausgegeben haben?', 'Ausgabenprognose[ {PERIOD}]',
    'Wie viel werde ich bis Monatsende für {CAT} ausgeben?', 'Voraussichtliche Ausgaben {PERIOD}', 'Wie viel gebe ich bei diesem Tempo {PERIOD} aus?'],
  top_accounts: ['Welche Karte habe ich[ {PERIOD}] am meisten benutzt?', 'Mit welchem Konto gebe ich {PERIOD} am meisten aus?', 'Top {N} Karten nach Ausgaben {PERIOD}',
    'Sortiere meine Konten nach Ausgaben[ {PERIOD}]', 'Welche Karte nutze ich am meisten für {CAT}?', 'Welches Konto hatte {PERIOD} die meisten Ausgaben?'],
  account_inventory: ['Wie viele Karten habe ich?', 'Welche Konten habe ich?', 'Zeig meine Karten',
    'Liste meiner Konten', 'Wie viele Bankkonten habe ich?', 'Welche Kreditkarten habe ich?'],
  unknown: ['Wie wird das Wetter morgen?', 'Überweise 100 Euro an Max', 'Soll ich Tesla-Aktien kaufen?', 'Lösche meine {MER} Transaktionen',
    'Ändere die Kategorie von {MER} auf {CAT}', 'Erzähl mir einen Witz', 'Bezahl meine Rechnung jetzt', 'Wie steht der Bitcoin-Kurs?'],
};

const IT = {
  spending_total: ['Quanto ho speso per {CAT}[ {PERIOD}]?', 'Quanto ho speso da {MER}[ {PERIOD}]?', 'Quanto ho speso {PERIOD}[ con {ACCT}]?',
    'Totale uscite per {CAT} {PERIOD}', 'Quanti soldi sono andati a {MER} {PERIOD}?', 'Mostrami le mie spese {PERIOD}'],
  income_total: ['Quanto ho guadagnato[ {PERIOD}]?', 'Quali sono state le mie entrate {PERIOD}?', 'Quanti soldi ho ricevuto {PERIOD}?',
    'Entrate totali {PERIOD}', 'Quanto stipendio ho preso {PERIOD}?', 'Quanto è entrato su {ACCT} {PERIOD}?'],
  compare_periods: ['Confronta {PERIOD!} con {CMP!}', 'Ho speso più {PERIOD!} o {CMP!}?', 'Le mie uscite per {CAT} sono aumentate {PERIOD}?',
    'Perché le mie spese sono cambiate {PERIOD}?', 'Uscite {PERIOD!} contro {CMP!}', 'Spendo di più da {MER} {PERIOD!} o {CMP!}?'],
  top_merchants: ['Quali sono i miei {N} negozi principali[ {PERIOD}]?', 'Dove spendo di più[ {PERIOD}]?', 'Top {N} esercenti {PERIOD}',
    'In quale negozio ho speso di più {PERIOD}?', 'Dove ho speso di più per {CAT}[ {PERIOD}]?', 'Classifica dei negozi per spesa {PERIOD}'],
  top_categories: ['Per cosa ho speso di più[ {PERIOD}]?', 'Dove sono finiti i miei soldi {PERIOD}?', 'Le mie {N} categorie principali {PERIOD}',
    'Uscite per categoria[ {PERIOD}]', 'Quale categoria mi è costata di più {PERIOD}?', 'In cosa spendo di più?'],
  largest_purchases: ['Quali sono stati i miei acquisti più grandi[ {PERIOD}]?', 'I miei {N} acquisti più cari {PERIOD}', 'Transazioni più grandi {PERIOD}',
    "Qual è stato l'acquisto più caro da {MER}[ {PERIOD}]?", 'Acquisti più grandi per {CAT} {PERIOD}', 'Qual è la cosa più cara che ho comprato {PERIOD}?'],
  daily_average: ['Quanto spendo al giorno[ {PERIOD}]?', 'Media delle uscite giornaliere {PERIOD}', 'Qual è la mia spesa media al giorno {PERIOD}?',
    'Quanto spendo al giorno per {CAT}[ {PERIOD}]?', 'Media giornaliera da {MER} {PERIOD}', 'Media quotidiana[ {PERIOD}]'],
  net_income_spending: ['Ho speso più di quanto ho guadagnato[ {PERIOD}]?', 'Entrate meno uscite {PERIOD}', 'Qual è il mio saldo netto {PERIOD}?',
    'Ho guadagnato più di quanto ho speso {PERIOD}?', 'Differenza tra entrate e uscite[ {PERIOD}]', 'Sto spendendo più di quanto guadagno?'],
  subscriptions: ['Quali abbonamenti ho?', 'Mostra i miei abbonamenti attivi', 'Quanto mi costano gli abbonamenti?',
    'Quali pagamenti ricorrenti ho?', 'A quali servizi sono abbonato?', 'Elenco dei miei abbonamenti'],
  upcoming_payments: ['Quali pagamenti scadono a breve?', 'Ho delle bollette da pagare?', 'Prossimi pagamenti',
    'Cosa devo pagare a breve?', 'Quali scadenze stanno arrivando?', 'Mostrami i pagamenti in scadenza'],
  unusual_charges: ['Ci sono addebiti insoliti[ {PERIOD}]?', 'Mostrami transazioni strane {PERIOD}', 'Qualche spesa fuori dal normale {PERIOD}?',
    "C'è stato qualcosa di insolito da {MER}[ {PERIOD}]?", 'Acquisti anormalmente alti {PERIOD}', 'Addebiti strani su {ACCT} {PERIOD}?'],
  possible_duplicates: ['Mi hanno addebitato due volte[ {PERIOD}]?', 'Ci sono addebiti duplicati {PERIOD}?', '{MER} mi ha addebitato due volte {PERIOD}?',
    'Cerca pagamenti doppi[ {PERIOD}]', 'Ho pagato qualcosa due volte {PERIOD}?', 'Addebiti ripetuti su {ACCT}[ {PERIOD}]'],
  recurring_changes: ['Quali addebiti ricorrenti sono cambiati[ {PERIOD}]?', 'Qualche abbonamento è aumentato {PERIOD}?', '{MER} ha aumentato il prezzo?',
    'Cambiamenti nei miei abbonamenti[ {PERIOD}]', 'Qualche abbonamento è diminuito {PERIOD}?', 'I miei pagamenti ricorrenti sono cambiati?'],
  month_forecast: ['Sono in linea con le spese[ {PERIOD}]?', 'Quanto avrò speso a fine mese?', 'Previsione delle spese[ {PERIOD}]',
    'Quanto spenderò per {CAT} entro fine mese?', 'Spesa prevista {PERIOD}', 'A questo ritmo, quanto spenderò {PERIOD}?'],
  top_accounts: ['Quale carta ho usato di più[ {PERIOD}]?', 'Con quale conto spendo di più {PERIOD}?', 'Top {N} carte per spesa {PERIOD}',
    'Ordina i miei conti per spesa[ {PERIOD}]', 'Quale carta uso di più per {CAT}?', 'Quale conto ha avuto più uscite {PERIOD}?'],
  account_inventory: ['Quante carte ho?', 'Quali conti ho?', 'Mostrami le mie carte',
    'Elenco dei miei conti', 'Quanti conti bancari ho?', 'Quali carte di credito ho?'],
  unknown: ['Che tempo farà domani?', 'Trasferisci 100 euro a Marco', 'Dovrei comprare azioni Tesla?', 'Cancella le mie transazioni {MER}',
    'Cambia la categoria di {MER} in {CAT}', 'Raccontami una barzelletta', 'Paga la mia bolletta adesso', 'Quanto vale il bitcoin?'],
};

const NL = {
  spending_total: ['Hoeveel heb ik[ {PERIOD}] aan {CAT} uitgegeven?', 'Hoeveel heb ik[ {PERIOD}] bij {MER} uitgegeven?', 'Wat heb ik {PERIOD}[ met {ACCT}] uitgegeven?',
    'Totale uitgaven aan {CAT} {PERIOD}', 'Hoeveel geld ging er {PERIOD} naar {MER}?', 'Laat mijn uitgaven {PERIOD} zien'],
  income_total: ['Hoeveel heb ik[ {PERIOD}] verdiend?', 'Wat was mijn inkomen {PERIOD}?', 'Hoeveel geld heb ik {PERIOD} ontvangen?',
    'Totale inkomsten {PERIOD}', 'Hoeveel salaris kwam er {PERIOD} binnen?', 'Hoeveel kwam er {PERIOD} op {ACCT} binnen?'],
  compare_periods: ['Vergelijk {PERIOD!} met {CMP!}', 'Heb ik {PERIOD} meer uitgegeven dan {CMP}?', 'Zijn mijn uitgaven aan {CAT} {PERIOD} gestegen?',
    'Waarom zijn mijn uitgaven {PERIOD} veranderd?', 'Uitgaven {PERIOD!} tegenover {CMP!}', 'Geef ik bij {MER} {PERIOD} meer uit dan {CMP}?'],
  top_merchants: ['Wat zijn mijn top {N} winkels[ {PERIOD}]?', 'Waar geef ik[ {PERIOD}] het meeste uit?', 'Top {N} verkopers {PERIOD}',
    'Bij welke winkel heb ik {PERIOD} het meest uitgegeven?', 'Waar heb ik[ {PERIOD}] het meest aan {CAT} uitgegeven?', 'Ranglijst van winkels op uitgaven {PERIOD}'],
  top_categories: ['Waaraan heb ik[ {PERIOD}] het meest uitgegeven?', 'Waar is mijn geld {PERIOD} gebleven?', 'Mijn top {N} categorieën {PERIOD}',
    'Uitgaven per categorie[ {PERIOD}]', 'Welke categorie kostte {PERIOD} het meest?', 'Waar gaat mijn geld naartoe?'],
  largest_purchases: ['Wat waren mijn grootste aankopen[ {PERIOD}]?', 'Mijn {N} duurste aankopen {PERIOD}', 'Grootste transacties {PERIOD}',
    'Wat was de duurste aankoop bij {MER}[ {PERIOD}]?', 'Grootste uitgaven aan {CAT} {PERIOD}', 'Wat was het duurste dat ik {PERIOD} kocht?'],
  daily_average: ['Hoeveel geef ik[ {PERIOD}] per dag uit?', 'Gemiddelde dagelijkse uitgaven {PERIOD}', 'Wat zijn mijn gemiddelde uitgaven per dag {PERIOD}?',
    'Hoeveel geef ik per dag uit aan {CAT}?', 'Daggemiddelde bij {MER} {PERIOD}', 'Dagelijks gemiddelde[ {PERIOD}]'],
  net_income_spending: ['Heb ik[ {PERIOD}] meer uitgegeven dan verdiend?', 'Inkomsten min uitgaven {PERIOD}', 'Wat is mijn netto saldo {PERIOD}?',
    'Heb ik {PERIOD} meer verdiend dan uitgegeven?', 'Verschil tussen inkomsten en uitgaven[ {PERIOD}]', 'Geef ik meer uit dan ik verdien?'],
  subscriptions: ['Welke abonnementen heb ik?', 'Toon mijn actieve abonnementen', 'Hoeveel kosten mijn abonnementen?',
    'Welke terugkerende betalingen heb ik?', 'Op welke diensten ben ik geabonneerd?', 'Lijst van mijn abonnementen'],
  upcoming_payments: ['Welke betalingen komen binnenkort?', 'Heb ik openstaande rekeningen?', 'Aankomende betalingen',
    'Wat moet ik binnenkort betalen?', 'Welke rekeningen komen eraan?', 'Laat de verschuldigde betalingen zien'],
  unusual_charges: ['Zijn er ongebruikelijke afschrijvingen[ {PERIOD}]?', 'Toon vreemde transacties {PERIOD}', 'Afwijkende uitgaven {PERIOD}?',
    'Was er iets ongewoons bij {MER}[ {PERIOD}]?', 'Ongewoon hoge aankopen {PERIOD}', 'Vreemde afschrijvingen op {ACCT} {PERIOD}?'],
  possible_duplicates: ['Ben ik[ {PERIOD}] dubbel afgeschreven?', 'Zijn er dubbele afschrijvingen {PERIOD}?', 'Heeft {MER} {PERIOD} twee keer afgeschreven?',
    'Zoek dubbele betalingen[ {PERIOD}]', 'Heb ik {PERIOD} iets twee keer betaald?', 'Herhaalde afschrijvingen op {ACCT}[ {PERIOD}]'],
  recurring_changes: ['Welke terugkerende kosten zijn[ {PERIOD}] veranderd?', 'Is een abonnement {PERIOD} duurder geworden?', 'Heeft {MER} de prijs verhoogd?',
    'Wijzigingen in mijn abonnementen[ {PERIOD}]', 'Is een abonnement {PERIOD} goedkoper geworden?', 'Zijn mijn vaste lasten veranderd?'],
  month_forecast: ['Lig ik[ {PERIOD}] op koers?', 'Hoeveel heb ik aan het eind van de maand uitgegeven?', 'Uitgavenprognose[ {PERIOD}]',
    'Hoeveel ga ik tot het eind van de maand aan {CAT} uitgeven?', 'Verwachte uitgaven {PERIOD}', 'Hoeveel geef ik in dit tempo {PERIOD} uit?'],
  top_accounts: ['Welke kaart heb ik[ {PERIOD}] het meest gebruikt?', 'Met welke rekening geef ik {PERIOD} het meest uit?', 'Top {N} kaarten op uitgaven {PERIOD}',
    'Sorteer mijn rekeningen op uitgaven[ {PERIOD}]', 'Welke kaart gebruik ik het meest voor {CAT}?', 'Welke rekening had {PERIOD} de meeste uitgaven?'],
  account_inventory: ['Hoeveel kaarten heb ik?', 'Welke rekeningen heb ik?', 'Laat mijn kaarten zien',
    'Lijst van mijn rekeningen', 'Hoeveel bankrekeningen heb ik?', 'Welke creditcards heb ik?'],
  unknown: ['Wat voor weer wordt het morgen?', 'Maak 100 euro over naar Jan', 'Moet ik Tesla-aandelen kopen?', 'Verwijder mijn {MER} transacties',
    'Verander de categorie van {MER} naar {CAT}', 'Vertel me een grap', 'Betaal mijn rekening nu', 'Wat is de koers van bitcoin?'],
};

const TR = {
  spending_total: ['[{PERIOD} ]{CAT} için ne kadar harcadım?', "[{PERIOD} ]{MER}'de ne kadar harcadım?", '{PERIOD}[ {ACCT} ile] ne kadar harcadım?',
    '{PERIOD} {CAT} harcamalarım', '{PERIOD} {MER} için ne kadar ödedim?', '{PERIOD} harcamalarımı göster'],
  income_total: ['[{PERIOD} ]ne kadar kazandım?', '{PERIOD} gelirim ne kadardı?', '{PERIOD} ne kadar para aldım?',
    '{PERIOD} toplam gelir', '{PERIOD} ne kadar maaş yattı?', '{PERIOD} {ACCT} hesabına ne kadar geldi?'],
  compare_periods: ['{PERIOD!} ile {CMP!} karşılaştır', '{PERIOD!} mi yoksa {CMP!} mi daha çok harcadım?', '{PERIOD} {CAT} harcamalarım arttı mı?',
    '{PERIOD} harcamalarım neden değişti?', 'Harcamalar: {PERIOD!} ve {CMP!}', '{MER} harcamam {PERIOD!} mi {CMP!} mi daha fazla?'],
  top_merchants: ['[{PERIOD} ]en çok harcama yaptığım {N} mağaza hangisi?', '[{PERIOD} ]en çok nereye harcadım?', '{PERIOD} ilk {N} mağaza',
    '{PERIOD} en çok hangi mağazada harcadım?', '[{PERIOD} ]{CAT} için en çok nereye harcadım?', '{PERIOD} harcamaya göre mağaza sıralaması'],
  top_categories: ['[{PERIOD} ]en çok neye harcadım?', '{PERIOD} param nereye gitti?', '{PERIOD} en büyük {N} kategori',
    '[{PERIOD} ]kategoriye göre harcamalar', '{PERIOD} en çok hangi kategoriye harcadım?', 'Param en çok nereye gidiyor?'],
  largest_purchases: ['[{PERIOD} ]en büyük alışverişlerim neler?', '{PERIOD} en pahalı {N} alımım', '{PERIOD} en büyük işlemler',
    "[{PERIOD} ]{MER}'deki en pahalı alışverişim neydi?", '{PERIOD} {CAT} için en büyük harcamalar', '{PERIOD} aldığım en pahalı şey neydi?'],
  daily_average: ['[{PERIOD} ]günde ne kadar harcıyorum?', '{PERIOD} günlük ortalama harcama', '{PERIOD} günlük ortalama harcamam ne kadar?',
    '{CAT} için günde ne kadar harcıyorum?', '{PERIOD} {MER} günlük ortalaması', '[{PERIOD} ]günlük ortalamam'],
  net_income_spending: ['[{PERIOD} ]kazandığımdan fazla mı harcadım?', '{PERIOD} gelir eksi gider', '{PERIOD} net bakiyem ne?',
    '{PERIOD} harcadığımdan fazla mı kazandım?', '[{PERIOD} ]gelir ve gider farkı', 'Kazandığımdan fazla mı harcıyorum?'],
  subscriptions: ['Hangi aboneliklerim var?', 'Aktif aboneliklerimi göster', 'Aboneliklerim bana kaça mal oluyor?',
    'Düzenli ödemelerim neler?', 'Hangi hizmetlere aboneyim?', 'Aboneliklerimin listesi'],
  upcoming_payments: ['Yakında hangi ödemeler var?', 'Ödenmemiş faturam var mı?', 'Yaklaşan ödemeler',
    'Yakında ne ödemem gerekiyor?', 'Hangi faturalar geliyor?', 'Vadesi gelen ödemeleri göster'],
  unusual_charges: ['[{PERIOD} ]olağandışı bir harcama var mı?', '{PERIOD} garip işlemleri göster', '{PERIOD} normalin dışında harcama var mı?',
    "[{PERIOD} ]{MER}'de olağandışı bir şey oldu mu?", '{PERIOD} anormal yüksek alışverişler', '{PERIOD} {ACCT} kartında garip çekimler var mı?'],
  possible_duplicates: ['[{PERIOD} ]iki kez ücret alındı mı?', '{PERIOD} mükerrer çekim var mı?', '{PERIOD} {MER} benden iki kez çekti mi?',
    '[{PERIOD} ]mükerrer ödemeleri bul', '{PERIOD} bir şeyi iki kez ödedim mi?', '[{PERIOD} ]{ACCT} üzerinde tekrarlanan çekimler'],
  recurring_changes: ['[{PERIOD} ]hangi düzenli ödemeler değişti?', '{PERIOD} bir abonelik zamlandı mı?', '{MER} fiyatını artırdı mı?',
    '[{PERIOD} ]aboneliklerimdeki değişiklikler', '{PERIOD} bir abonelik ucuzladı mı?', 'Düzenli ödemelerim değişti mi?'],
  month_forecast: ['[{PERIOD} ]bütçemde miyim?', 'Ay sonuna kadar ne kadar harcamış olacağım?', '[{PERIOD} ]harcama tahmini',
    'Ay sonuna kadar {CAT} için ne kadar harcayacağım?', '{PERIOD} öngörülen harcama', 'Bu hızla {PERIOD} ne kadar harcayacağım?'],
  top_accounts: ['[{PERIOD} ]en çok hangi kartı kullandım?', '{PERIOD} en çok hangi hesaptan harcadım?', '{PERIOD} harcamaya göre ilk {N} kart',
    '[{PERIOD} ]hesaplarımı harcamaya göre sırala', '{CAT} için en çok hangi kartı kullanıyorum?', '{PERIOD} en çok harcama hangi hesaptaydı?'],
  account_inventory: ['Kaç kartım var?', 'Hangi hesaplarım var?', 'Kartlarımı göster',
    'Hesaplarımın listesi', 'Kaç banka hesabım var?', 'Hangi kredi kartlarım var?'],
  unknown: ['Yarın hava nasıl olacak?', "Ahmet'e 500 lira gönder", 'Tesla hissesi almalı mıyım?', '{MER} işlemlerimi sil',
    '{MER} kategorisini {CAT} olarak değiştir', 'Bana bir fıkra anlat', 'Faturamı şimdi öde', 'Bitcoin fiyatı ne kadar?'],
};

const ID = {
  spending_total: ['Berapa pengeluaran saya untuk {CAT}[ {PERIOD}]?', 'Berapa yang saya habiskan di {MER}[ {PERIOD}]?', 'Berapa total belanja saya {PERIOD}[ pakai {ACCT}]?',
    'Total pengeluaran {CAT} {PERIOD}', 'Berapa uang yang keluar ke {MER} {PERIOD}?', 'Tampilkan pengeluaran saya {PERIOD}'],
  income_total: ['Berapa penghasilan saya[ {PERIOD}]?', 'Berapa pendapatan saya {PERIOD}?', 'Berapa uang yang saya terima {PERIOD}?',
    'Total pemasukan {PERIOD}', 'Berapa gaji yang masuk {PERIOD}?', 'Berapa yang masuk ke {ACCT} {PERIOD}?'],
  compare_periods: ['Bandingkan {PERIOD!} dengan {CMP!}', 'Apakah saya belanja lebih banyak {PERIOD!} dibanding {CMP!}?', 'Apakah pengeluaran {CAT} naik {PERIOD}?',
    'Kenapa pengeluaran saya berubah {PERIOD}?', 'Pengeluaran {PERIOD!} vs {CMP!}', 'Apakah belanja saya di {MER} {PERIOD!} lebih besar dari {CMP!}?'],
  top_merchants: ['Apa {N} toko teratas saya[ {PERIOD}]?', 'Di mana saya paling banyak belanja[ {PERIOD}]?', '{N} merchant teratas {PERIOD}',
    'Di toko mana saya paling boros {PERIOD}?', 'Di mana saya paling banyak keluar uang untuk {CAT}[ {PERIOD}]?', 'Peringkat toko berdasarkan pengeluaran {PERIOD}'],
  top_categories: ['Untuk apa saya paling banyak keluar uang[ {PERIOD}]?', 'Ke mana uang saya pergi {PERIOD}?', '{N} kategori teratas saya {PERIOD}',
    'Pengeluaran per kategori[ {PERIOD}]', 'Kategori apa yang paling besar {PERIOD}?', 'Uang saya paling banyak habis untuk apa?'],
  largest_purchases: ['Apa pembelian terbesar saya[ {PERIOD}]?', '{N} pembelian termahal saya {PERIOD}', 'Transaksi terbesar {PERIOD}',
    'Apa pembelian termahal di {MER}[ {PERIOD}]?', 'Pembelian {CAT} terbesar {PERIOD}', 'Barang paling mahal yang saya beli {PERIOD}?'],
  daily_average: ['Berapa pengeluaran saya per hari[ {PERIOD}]?', 'Rata-rata pengeluaran harian {PERIOD}', 'Berapa rata-rata belanja saya sehari {PERIOD}?',
    'Berapa pengeluaran harian untuk {CAT}[ {PERIOD}]?', 'Rata-rata harian di {MER} {PERIOD}', 'Rata-rata per hari[ {PERIOD}]'],
  net_income_spending: ['Apakah pengeluaran saya lebih besar dari penghasilan[ {PERIOD}]?', 'Pemasukan dikurangi pengeluaran {PERIOD}', 'Berapa saldo bersih saya {PERIOD}?',
    'Apakah saya dapat lebih banyak dari yang saya habiskan {PERIOD}?', 'Selisih pemasukan dan pengeluaran[ {PERIOD}]', 'Apakah saya boros melebihi gaji?'],
  subscriptions: ['Langganan apa saja yang saya punya?', 'Tampilkan langganan aktif saya', 'Berapa biaya langganan saya?',
    'Pembayaran rutin apa yang saya punya?', 'Saya berlangganan layanan apa saja?', 'Daftar langganan saya'],
  upcoming_payments: ['Pembayaran apa yang segera jatuh tempo?', 'Apakah ada tagihan yang harus dibayar?', 'Pembayaran mendatang',
    'Apa yang harus saya bayar sebentar lagi?', 'Tagihan apa yang akan datang?', 'Tampilkan pembayaran yang jatuh tempo'],
  unusual_charges: ['Apakah ada tagihan tidak biasa[ {PERIOD}]?', 'Tampilkan transaksi aneh {PERIOD}', 'Ada pengeluaran yang tidak wajar {PERIOD}?',
    'Ada yang aneh di {MER}[ {PERIOD}]?', 'Pembelian yang luar biasa besar {PERIOD}', 'Potongan aneh di {ACCT} {PERIOD}?'],
  possible_duplicates: ['Apakah saya ditagih dua kali[ {PERIOD}]?', 'Ada tagihan ganda {PERIOD}?', 'Apakah {MER} menagih saya dua kali {PERIOD}?',
    'Cari pembayaran ganda[ {PERIOD}]', 'Apakah saya membayar sesuatu dua kali {PERIOD}?', 'Potongan berulang di {ACCT}[ {PERIOD}]'],
  recurring_changes: ['Tagihan rutin mana yang berubah[ {PERIOD}]?', 'Apakah ada langganan yang naik harga {PERIOD}?', 'Apakah {MER} menaikkan harga?',
    'Perubahan langganan saya[ {PERIOD}]', 'Apakah ada langganan yang turun {PERIOD}?', 'Apakah pembayaran rutin saya berubah?'],
  month_forecast: ['Apakah pengeluaran saya sesuai rencana[ {PERIOD}]?', 'Berapa yang akan saya habiskan sampai akhir bulan?', 'Perkiraan pengeluaran[ {PERIOD}]',
    'Berapa pengeluaran {CAT} sampai akhir bulan?', 'Proyeksi pengeluaran {PERIOD}', 'Dengan laju ini, berapa pengeluaran saya {PERIOD}?'],
  top_accounts: ['Kartu mana yang paling sering saya pakai[ {PERIOD}]?', 'Dari rekening mana saya paling banyak belanja {PERIOD}?', '{N} kartu teratas berdasarkan pengeluaran {PERIOD}',
    'Urutkan rekening saya berdasarkan pengeluaran[ {PERIOD}]', 'Kartu apa yang paling sering saya pakai untuk {CAT}?', 'Rekening mana yang pengeluarannya paling besar {PERIOD}?'],
  account_inventory: ['Berapa kartu yang saya punya?', 'Rekening apa saja yang saya punya?', 'Tampilkan kartu saya',
    'Daftar rekening saya', 'Berapa rekening bank saya?', 'Kartu kredit apa saja yang saya punya?'],
  unknown: ['Bagaimana cuaca besok?', 'Transfer 100 ribu ke Budi', 'Apakah saya harus beli saham BBCA?', 'Hapus transaksi {MER} saya',
    'Ubah kategori {MER} jadi {CAT}', 'Ceritakan lelucon', 'Bayar tagihan saya sekarang', 'Berapa harga bitcoin?'],
};

const HI = {
  spending_total: ['[{PERIOD} ]{CAT} pe kitna kharch hua?', '[{PERIOD} ]{MER} pe kitna spend kiya?', '{PERIOD} maine kitna kharch kiya[ {ACCT} se]?',
    '{PERIOD} {CAT} ka total kharcha', '{PERIOD} {MER} mein kitne paise gaye?', 'Mere expenses dikhao {PERIOD}'],
  income_total: ['[{PERIOD} ]maine kitna kamaya?', '{PERIOD} meri income kitni thi?', '{PERIOD} kitne paise aaye?',
    '{PERIOD} total income', '{PERIOD} salary kitni aayi?', '{PERIOD} {ACCT} mein kitna aaya?'],
  compare_periods: ['{PERIOD!} ko {CMP!} se compare karo', 'Kya maine {PERIOD!} {CMP!} se zyada kharch kiya?', '[{PERIOD} ]{CAT} ka kharcha badha kya?',
    '{PERIOD} mera kharcha kyun badla?', '{PERIOD!} vs {CMP!} spending', '{MER} pe {PERIOD!} zyada kharch hua ya {CMP!}?'],
  top_merchants: ['[{PERIOD} ]mere top {N} merchants kaun se hain?', '[{PERIOD} ]sabse zyada kharch kis dukaan pe hua?', '{PERIOD} top {N} shops',
    '{PERIOD} sabse zyada kis store pe kharch kiya?', '[{PERIOD} ]{CAT} ke liye sabse zyada kahan kharch kiya?', '{PERIOD} merchants ki ranking spending ke hisaab se'],
  top_categories: ['[{PERIOD} ]sabse zyada kharcha kis cheez pe hua?', '{PERIOD} mera paisa kahan gaya?', '{PERIOD} top {N} categories',
    '[{PERIOD} ]category wise kharcha', '{PERIOD} kaunsi category mein sabse zyada kharch hua?', 'Mera paisa sabse zyada kahan jaata hai?'],
  largest_purchases: ['[{PERIOD} ]meri sabse badi purchases kaun si thi?', '{PERIOD} top {N} sabse mehngi purchases', '{PERIOD} sabse bade transactions',
    '[{PERIOD} ]{MER} pe sabse mehnga kya kharida?', '{PERIOD} {CAT} ki sabse badi purchases', '{PERIOD} sabse mehngi cheez kya li?'],
  daily_average: ['[{PERIOD} ]roz ka kitna kharch hota hai?', '{PERIOD} daily average kharcha', '{PERIOD} per day kitna spend kiya?',
    '{CAT} pe roz kitna kharch hota hai?', '{PERIOD} {MER} pe daily average', '[{PERIOD} ]mera roz ka average'],
  net_income_spending: ['[{PERIOD} ]kya maine kamai se zyada kharch kiya?', '{PERIOD} income minus kharcha', '{PERIOD} net balance kitna hai?',
    '{PERIOD} kya kamai kharche se zyada thi?', '[{PERIOD} ]income aur kharche ka difference', 'Kya main kamai se zyada kharch kar raha hoon?'],
  subscriptions: ['Mere subscriptions kaun kaun se hain?', 'Mere active subscriptions dikhao', 'Subscriptions ka kitna kharcha hai?',
    'Har mahine kaun se payments katte hain?', 'Maine kaun kaun si services subscribe ki hain?', 'Subscriptions ki list'],
  upcoming_payments: ['Kaun se payments jaldi due hain?', 'Koi bill pending hai kya?', 'Upcoming payments',
    'Jaldi kya pay karna hai?', 'Kaun se bills aane wale hain?', 'Due payments dikhao'],
  unusual_charges: ['[{PERIOD} ]koi unusual charge hai kya?', '{PERIOD} ajeeb transactions dikhao', '{PERIOD} normal se hatke koi kharcha?',
    '[{PERIOD} ]{MER} pe kuch ajeeb hua kya?', '{PERIOD} normal se bahut mehngi purchases', '{PERIOD} {ACCT} pe ajeeb charges?'],
  possible_duplicates: ['[{PERIOD} ]kya mujhse do baar paise kate?', '{PERIOD} koi duplicate charge hai?', '{PERIOD} kya {MER} ne do baar charge kiya?',
    '[{PERIOD} ]duplicate payments dhundo', '{PERIOD} kya maine kuch do baar pay kiya?', '[{PERIOD} ]{ACCT} pe repeat charges'],
  recurring_changes: ['[{PERIOD} ]kaun se recurring charges badle?', '{PERIOD} koi subscription mehnga hua kya?', 'Kya {MER} ne price badhaya?',
    '[{PERIOD} ]subscriptions mein changes', '{PERIOD} koi subscription sasta hua?', 'Kya mere recurring payments badle?'],
  month_forecast: ['[{PERIOD} ]kya main track pe hoon?', 'Mahine ke end tak kitna kharch ho jayega?', '[{PERIOD} ]kharche ka forecast',
    'Mahine ke end tak {CAT} pe kitna kharch hoga?', '{PERIOD} projected kharcha', 'Isi speed se {PERIOD} kitna kharch hoga?'],
  top_accounts: ['[{PERIOD} ]sabse zyada kaunsa card use kiya?', '{PERIOD} kis account se sabse zyada kharch hua?', '{PERIOD} spending ke hisaab se top {N} cards',
    '[{PERIOD} ]mere accounts ko spending se rank karo', '{CAT} ke liye sabse zyada kaunsa card use karta hoon?', '{PERIOD} kis account mein sabse zyada kharcha tha?'],
  account_inventory: ['Mere paas kitne cards hain?', 'Mere kaun kaun se accounts hain?', 'Mere cards dikhao',
    'Mere accounts ki list', 'Mere kitne bank accounts hain?', 'Mere credit cards kaun se hain?'],
  unknown: ['Mausam kaisa hai?', 'Rahul ko 500 rupaye bhejo', 'Kya mujhe Reliance stock lena chahiye?', 'Meri {MER} transactions delete karo',
    '{MER} ki category {CAT} kar do', 'Ek joke sunao', 'Mera bill abhi pay karo', 'Bitcoin ka price kya hai?'],
};

module.exports = { TEMPLATES: { en: EN, ar: AR, es: ES, pt: PT, fr: FR, de: DE, it: IT, nl: NL, tr: TR, id: ID, 'hi-Latn': HI } };
