// Generated by scripts/generate-ios-bank-senders.mjs. Do not edit.
import Foundation

public struct WafraBankSenderIdentity: Equatable {
  public let market: String
  public let bankId: String

  public init(market: String, bankId: String) {
    self.market = market
    self.bankId = bankId
  }
}

public enum WafraBankSenderRegistry {
  private static let aliases: [String: WafraBankSenderIdentity] = [:]

  private static func isForbidden(_ scalar: Unicode.Scalar) -> Bool {
    switch scalar.value {
    case 0x0000...0x001F, 0x007F...0x009F, 0x061C, 0x200B...0x200F,
         0x202A...0x202E, 0x2066...0x2069, 0xFEFF:
      return true
    default:
      return false
    }
  }

  private static func isSeparator(_ scalar: Unicode.Scalar) -> Bool {
    switch scalar.value {
    case 0x20, 0x2E, 0x5F, 0x2D:
      return true
    default:
      return false
    }
  }

  public static func normalize(_ value: String) -> String? {
    guard !value.isEmpty, value.utf16.count <= 80 else { return nil }
    guard !value.unicodeScalars.contains(where: isForbidden) else { return nil }
    let source = value.precomposedStringWithCompatibilityMapping
      .lowercased(with: Locale(identifier: "en_US"))
    var normalizedScalars = String.UnicodeScalarView()
    for scalar in source.unicodeScalars where !isSeparator(scalar) {
      normalizedScalars.append(scalar)
    }
    let normalized = String(normalizedScalars)
    guard !normalized.isEmpty, normalized.utf16.count <= 80 else { return nil }
    return normalized
  }

  public static func identity(for value: String) -> WafraBankSenderIdentity? {
    guard let key = normalize(value) else { return nil }
    return aliases[key]
  }
}
