const { withProjectBuildGradle } = require('@expo/config-plugins');

/**
 * `onnxruntime-react-native` does not configure under Gradle 9.
 *
 * Expo SDK 55 ships Gradle 9.0.0. `org.gradle.util.VersionNumber` was
 * deprecated in Gradle 7 and REMOVED in Gradle 9, and
 * `onnxruntime-react-native@1.24.3` still calls it, at
 * `node_modules/onnxruntime-react-native/android/build.gradle` line 250:
 *
 *     if (VersionNumber.parse(REACT_NATIVE_VERSION) < VersionNumber.parse("0.71")) {
 *       extractLibs "com.facebook.fbjni:fbjni:+:headers"
 *       extractLibs "com.facebook.fbjni:fbjni:+"
 *     }
 *
 * so the whole build dies during configuration:
 *
 *     A problem occurred evaluating project ':onnxruntime-react-native'.
 *     > Could not get unknown property 'VersionNumber'
 *
 * The check exists to add fbjni headers for React Native older than 0.71.
 * This app is on 0.83.10, so the branch is dead either way — but Groovy
 * evaluates the condition before it can be skipped, so it still has to
 * resolve the name.
 *
 * Rather than patch a file inside `node_modules` (which `npm ci` restores on
 * every CI run), this binds the name that was removed to the implementation
 * Gradle still ships internally, for every project. The class is the same one
 * the public alias pointed at; only its package moved. If a future Gradle
 * drops that too, the `hasProperty` guard below leaves the build no worse off
 * than it is now, and the right fix then is a newer onnxruntime-react-native.
 *
 * `android/` is gitignored and regenerated by `expo prebuild`, so this has to
 * be a config plugin: a hand-edit of the generated Gradle files would not
 * survive the next prebuild, and a step in `build-apk.yml` would fix CI while
 * leaving every local `npx expo run:android` broken.
 */

const ANCHOR = '// onnxruntime-react-native: Gradle 9 VersionNumber compatibility';

const SNIPPET = `
${ANCHOR}
// See plugins/onnxruntime-gradle9-compat. Removing this breaks the Android
// build at configuration time, before any task runs.
allprojects {
  if (!it.hasProperty('VersionNumber')) {
    try {
      it.ext.VersionNumber = Class.forName('org.gradle.util.internal.VersionNumber')
    } catch (ignored) {
      // Leave the property unset: the build fails exactly as it does without
      // this plugin, rather than failing somewhere less obvious.
    }
  }
}
`;

const withOnnxruntimeGradle9Compat = (config) =>
  withProjectBuildGradle(config, (gradleConfig) => {
    if (gradleConfig.modResults.language !== 'groovy') {
      throw new Error(
        'onnxruntime-gradle9-compat: the root build.gradle is not Groovy; ' +
        'port the VersionNumber binding before building for Android.',
      );
    }
    if (!gradleConfig.modResults.contents.includes(ANCHOR)) {
      gradleConfig.modResults.contents += SNIPPET;
    }
    return gradleConfig;
  });

module.exports = withOnnxruntimeGradle9Compat;
