const {
  withAppBuildGradle,
  withDangerousMod,
  withMainApplication,
  withProjectBuildGradle,
} = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Two things `onnxruntime-react-native@1.24.3` needs under Expo SDK 55 that
 * neither its own `app.plugin.js` nor autolinking provides.
 *
 * 1. Gradle 9 removed `org.gradle.util.VersionNumber`; the package's
 *    build.gradle still resolves it at configuration time (line 250), so the
 *    Android build died before any task ran. The root-project snippet below
 *    binds the name to the internal class Gradle still ships, guarded so a
 *    future removal fails exactly as today.
 *
 * 2. The package ships a legacy `unimodule.json`. Expo's autolinking therefore
 *    treats it as an Expo module: it is compiled and its .so files land in the
 *    APK, but its `OnnxruntimePackage` (a plain `ReactPackage`) is never
 *    registered and the package is excluded from React Native autolinking. At
 *    runtime `NativeModules.Onnxruntime` is null and the JS binding's
 *    `Module.install()` throws on import. Verified on a physical device with
 *    build 331: "TypeError: Cannot read property 'install' of null" at launch.
 *    `withMainApplication` adds the package to the manual list the template
 *    reserves for exactly this case; `withAppBuildGradle` and the Podfile line
 *    mirror what the upstream plugin does for the dependency itself.
 *
 * Done as a config plugin because `android/` and `ios/` are gitignored and
 * regenerated by `expo prebuild`.
 */

const ANCHOR = '// onnxruntime-react-native: Gradle 9 VersionNumber compatibility';

const SNIPPET = `
${ANCHOR}
// See plugins/onnxruntime-gradle9-compat. Removing this breaks the Android
// build at configuration time, before any task runs.
allprojects {
  if (!it.hasProperty('VersionNumber')) {
    try {
      it.ext.VersionNumber = Class.forName('org.gradle.util.internal.VersionNumber')
    } catch (ignored) {
      // Leave the property unset: the build fails exactly as it does without
      // this plugin, rather than failing somewhere less obvious.
    }
  }
}
`;

const withGradle9Compat = (config) =>
  withProjectBuildGradle(config, (gradleConfig) => {
    if (gradleConfig.modResults.language !== 'groovy') {
      throw new Error(
        'onnxruntime-gradle9-compat: the root build.gradle is not Groovy; ' +
        'port the VersionNumber binding before building for Android.',
      );
    }
    if (!gradleConfig.modResults.contents.includes(ANCHOR)) {
      gradleConfig.modResults.contents += SNIPPET;
    }
    return gradleConfig;
  });

const APP_DEPENDENCY = "    implementation project(':onnxruntime-react-native') // onnxruntime-react-native";

const withAppDependency = (config) =>
  withAppBuildGradle(config, (gradleConfig) => {
    if (gradleConfig.modResults.language !== 'groovy') {
      throw new Error('onnxruntime-gradle9-compat: app build.gradle is not Groovy.');
    }
    const contents = gradleConfig.modResults.contents;
    if (!contents.includes("project(':onnxruntime-react-native')")) {
      gradleConfig.modResults.contents = contents.replace(
        /^dependencies[ \t]*\{$/m,
        (match) => `${match}\n${APP_DEPENDENCY}`,
      );
    }
    return gradleConfig;
  });

const PACKAGE_LINE = 'add(ai.onnxruntime.reactnative.OnnxruntimePackage())';
const MANUAL_ANCHOR = /^(\s*)\/\/ add\(MyReactNativePackage\(\)\)\s*$/m;

const withPackageRegistration = (config) =>
  withMainApplication(config, (appConfig) => {
    const contents = appConfig.modResults.contents;
    if (contents.includes(PACKAGE_LINE)) return appConfig;
    if (!MANUAL_ANCHOR.test(contents)) {
      throw new Error(
        'onnxruntime-gradle9-compat: MainApplication has no manual package anchor ' +
        '("// add(MyReactNativePackage())"); register OnnxruntimePackage by hand.',
      );
    }
    appConfig.modResults.contents = contents.replace(
      MANUAL_ANCHOR,
      (match, indent) => `${match}\n${indent}// onnxruntime-react-native ships unimodule.json, so Expo autolinking\n${indent}// compiles it but never registers its ReactPackage. See plugins/onnxruntime-gradle9-compat.\n${indent}${PACKAGE_LINE}`,
    );
    return appConfig;
  });

const POD_LINE = "  pod 'onnxruntime-react-native', :path => '../node_modules/onnxruntime-react-native' # onnxruntime-react-native";

const withPod = (config) =>
  withDangerousMod(config, [
    'ios',
    (iosConfig) => {
      const podfile = path.join(iosConfig.modRequest.platformProjectRoot, 'Podfile');
      const contents = fs.readFileSync(podfile, 'utf8');
      if (!contents.includes("pod 'onnxruntime-react-native'")) {
        fs.writeFileSync(podfile, contents.replace(/^target.+do$/m, (match) => `${match}\n${POD_LINE}`));
      }
      return iosConfig;
    },
  ]);

module.exports = (config) => withPod(withPackageRegistration(withAppDependency(withGradle9Compat(config))));
