'use strict';
/**
 * Independently authored alert templates per language. They imitate common
 * bank-alert STYLES (card-charge sentences, key:value field lists, mobile-money
 * receipts, UPI/Pix/Bizum rails) without reproducing any bank's exact copy.
 *
 * Slots: {AMT} transaction money, {BAL}/{BAL2} other figures, {MER} merchant,
 * {BILLER}, {NAME}, {EMPLOYER}, {DATE}, {TIME}, {CARD}, {ACCT}, {BANK}, {OTP},
 * {REF}, {VPA}, {PHONE}, {ATM}, {RAIL}.
 * Cue markup: <d>debit cue</d>, <c>credit cue</c>, <n>non-posting cue</n>.
 * Entry: [event, template, options?] with options.only = [country codes].
 *
 * Events: purchase refund transfer_out transfer_in salary fee withdrawal
 * card_payment bill_payment | otp pending declined promo balance statement
 * request future
 */

const T = {};

T.en = [
  ['purchase', '{BANK}: Your card ending {CARD} was <d>charged</d> {AMT} at {MER} on {DATE}.'],
  ['purchase', 'You made a {AMT} <d>purchase</d> at {MER} on {DATE} with your card ending in {CARD}.'],
  ['purchase', 'Purchase of {AMT} with Debit Card ending {CARD} at {MER}. Avl Balance {BAL}', { only: ['AE', 'SA', 'EG', 'KW'] }],
  ['purchase', 'Txn Alert: {AMT} <d>spent</d> on card XX{CARD} at {MER} on {DATE} {TIME}. Avl Lmt: {BAL}', { only: ['IN', 'PK', 'AE', 'MY'] }],
  ['purchase', 'Acct:XXX{ACCT}\nAmt:{AMT} <d>DR</d>\nDesc:POS/{MER}\nDate:{DATE}\nBal:{BAL}', { only: ['NG'] }],
  ['purchase', '{BANK}: {ACCT}, <d>Pur</d>, {DATE} {MER}, {AMT}, Available {BAL}.', { only: ['ZA'] }],
  ['purchase', '{REF} Confirmed. {AMT} <d>paid to</d> {MER}. on {DATE} at {TIME}. New M-PESA balance is {BAL}.', { only: ['KE'] }],
  ['purchase', 'Card Transaction | Amount: {AMT} | Merchant: {MER} | Date: {DATE} | Status: <d>Approved</d>'],
  ['purchase', '{BANK} Alert: {AMT} was <d>debited</d> from your account {ACCT} for a purchase at {MER} on {DATE}.'],
  ['purchase', 'Thank you for <d>using</d> your {BANK} card ending {CARD} for {AMT} at {MER} on {DATE}.', { only: ['US', 'CA', 'PH', 'SG', 'AE'] }],
  ['purchase', '{BANK}: {AMT} <d>spent</d> at {MER} with card *{CARD}. {DATE}.'],
  ['purchase', 'Dear Customer, your {BANK} Credit Card XX{CARD} has been <d>used</d> for {AMT} at {MER} on {DATE}. Available limit {BAL}.'],
  ['refund', '{BANK}: A refund of {AMT} from {MER} has been <c>credited</c> to your card ending {CARD} on {DATE}.'],
  ['refund', '<c>Refund</c> {AMT} received from {MER}. Card XX{CARD}. {DATE}'],
  ['refund', 'Your {BANK} card *{CARD} has a <c>credit</c> of {AMT} from {MER} (refund) on {DATE}.'],
  ['refund', '<c>Reversal</c>: {AMT} credited back to your account {ACCT} for {MER} transaction on {DATE}.'],
  ['transfer_out', '{BANK}: {AMT} <d>transferred</d> from your account {ACCT} to {NAME} on {DATE}. Ref {REF}.'],
  ['transfer_out', '{AMT} <d>debited</d> from A/c XX{ACCT} on {DATE} to VPA {VPA} (UPI Ref No {REF}). Not you? Call 18002586161', { only: ['IN'] }],
  ['transfer_out', '{REF} Confirmed. {AMT} <d>sent to</d> {NAME} {PHONE} on {DATE} at {TIME}. New M-PESA balance is {BAL}.', { only: ['KE'] }],
  ['transfer_out', 'You <d>sent</d> {AMT} to {NAME} via {RAIL} on {DATE}.'],
  ['transfer_out', 'Acct:XXX{ACCT}\nAmt:{AMT} <d>DR</d>\nDesc:TRF TO {NAME}\nDate:{DATE}\nBal:{BAL}', { only: ['NG'] }],
  ['transfer_in', '{BANK}: {AMT} has been <c>credited</c> to your account {ACCT} from {NAME} on {DATE}.'],
  ['transfer_in', 'Acct:XXX{ACCT}\nAmt:{AMT} <c>CR</c>\nDesc:TRF FROM {NAME}\nDate:{DATE}\nBal:{BAL}', { only: ['NG'] }],
  ['transfer_in', 'You have <c>received</c> {AMT} from {NAME} via {RAIL}. {DATE}.'],
  ['transfer_in', '{REF} Confirmed. You have <c>received</c> {AMT} from {NAME} {PHONE} on {DATE} at {TIME}. New M-PESA balance is {BAL}.', { only: ['KE'] }],
  ['transfer_in', 'Money in: {NAME} <c>paid you</c> {AMT}. {BANK}'],
  ['salary', '{BANK}: Salary of {AMT} <c>credited</c> to your account {ACCT} on {DATE}. Avl Bal {BAL}.'],
  ['salary', 'Payroll <c>deposit</c>: {AMT} from {EMPLOYER} to account ending {ACCT} on {DATE}.'],
  ['salary', 'Dear Customer, your a/c {ACCT} is <c>credited</c> with {AMT} on {DATE} towards SALARY {EMPLOYER}.'],
  ['fee', '{BANK}: A monthly maintenance fee of {AMT} was <d>charged</d> to your account {ACCT} on {DATE}.'],
  ['fee', 'Annual card fee {AMT} <d>debited</d> to card XX{CARD}. {DATE}'],
  ['fee', 'SMS alert charges of {AMT} <d>deducted</d> from A/c {ACCT} on {DATE}.'],
  ['withdrawal', '{BANK}: ATM <d>cash withdrawal</d> of {AMT} from account {ACCT} on {DATE} at {ATM}. Avl Bal {BAL}.'],
  ['withdrawal', '{AMT} <d>withdrawn</d> at ATM {ATM} using card XX{CARD} on {DATE}.'],
  ['withdrawal', '{REF} Confirmed. on {DATE} at {TIME} <d>Withdraw</d> {AMT} from {ATM} New M-PESA balance is {BAL}.', { only: ['KE'] }],
  ['card_payment', '{BANK}: Payment of {AMT} <c>received</c> towards your credit card ending {CARD} on {DATE}. Thank you.'],
  ['card_payment', 'We have <c>received</c> your credit card payment of {AMT} on {DATE}. Card XX{CARD}.'],
  ['bill_payment', '{BANK}: Bill payment of {AMT} to {BILLER} was <d>successful</d> on {DATE}. Ref {REF}.'],
  ['bill_payment', 'Your payment of {AMT} to {BILLER} for account {ACCT} has been <d>processed</d> on {DATE}.'],
  ['bill_payment', '{AMT} <d>paid</d> to {BILLER} from A/c XX{ACCT} on {DATE}.'],
  ['otp', '{OTP} is your OTP for a transaction of {AMT} at {MER} on card XX{CARD}. Do not share it with anyone. - {BANK}'],
  ['otp', '{BANK}: Use code {OTP} to <n>approve</n> your payment of {AMT} to {MER}. Never share this code.'],
  ['otp', 'Your one-time password is {OTP}. It is valid for 5 minutes for the purchase of {AMT} at {MER}.'],
  ['pending', '{BANK}: A <n>pending</n> transaction of {AMT} at {MER} is awaiting settlement on card ending {CARD}.'],
  ['pending', '<n>Authorization hold</n> of {AMT} placed by {MER} on card *{CARD}. The final amount may differ.'],
  ['pending', 'Your transfer of {AMT} to {NAME} is <n>being processed</n> and will be completed shortly.'],
  ['declined', '{BANK}: Your card ending {CARD} was <n>declined</n> for {AMT} at {MER} on {DATE} due to insufficient funds.'],
  ['declined', 'Transaction of {AMT} at {MER} <n>failed</n>. No amount has been debited from your account.'],
  ['declined', 'Payment of {AMT} to {BILLER} was <n>unsuccessful</n>. Please try again.'],
  ['promo', '{BANK}: Spend {AMT} or more at {MER} this weekend and get 10% cashback! T&C apply.'],
  ['promo', 'Get a personal loan up to {AMT} at 0% processing fee. Apply now in the {BANK} app.'],
  ['promo', 'Congratulations! You are pre-approved for a credit card with a limit of {AMT}. Reply YES to apply.'],
  ['balance', '{BANK}: The available balance in your account {ACCT} is {BAL} as of {DATE}.'],
  ['balance', 'Your account {ACCT} balance on {DATE}: {BAL}. No new transactions.'],
  ['statement', '{BANK}: Your credit card statement for card XX{CARD} is ready. Total due {BAL}, minimum due {BAL2}, due by {DATE}.'],
  ['statement', 'Minimum payment of {BAL} on your {BANK} credit card is due on {DATE}. Pay now to avoid late fees.'],
  ['request', '{NAME} has <n>requested</n> {AMT} from you via {RAIL}. Tap to pay or decline.'],
  ['request', 'Collect request of {AMT} from {VPA} is <n>pending your approval</n>. UPI Ref {REF}.', { only: ['IN'] }],
  ['future', '{BANK}: Your scheduled payment of {AMT} to {BILLER} <n>will be debited</n> on {DATE}.'],
  ['future', 'Reminder: auto-debit of {AMT} for {BILLER} is <n>scheduled</n> for {DATE}. Keep sufficient balance.'],
];

T.ar = [
  ['purchase', 'تمت عملية <d>شراء</d> بقيمة {AMT} لدى {MER} بواسطة البطاقة المنتهية بـ {CARD} في {DATE}. الرصيد المتاح {BAL}'],
  ['purchase', '<d>شراء</d> عبر نقاط البيع\nبطاقة: **{CARD}\nلدى: {MER}\nمبلغ: {AMT}\nفي: {DATE}'],
  ['purchase', 'تم <d>خصم</d> {AMT} من حسابك {ACCT} لعملية شراء من {MER} بتاريخ {DATE}'],
  ['refund', 'تم <c>إيداع</c> مبلغ مسترد {AMT} من {MER} إلى بطاقتك المنتهية بـ {CARD} بتاريخ {DATE}'],
  ['refund', '<c>استرداد</c> مبلغ {AMT} من {MER} إلى حسابك {ACCT}'],
  ['transfer_out', 'تم <d>تحويل</d> {AMT} من حسابك {ACCT} إلى {NAME} بتاريخ {DATE}'],
  ['transfer_out', 'حوالة صادرة: تم <d>خصم</d> {AMT} من حسابك لصالح {NAME}. الرقم المرجعي {REF}'],
  ['transfer_in', 'تم <c>إيداع</c> حوالة واردة بمبلغ {AMT} في حسابك {ACCT} من {NAME} بتاريخ {DATE}'],
  ['transfer_in', 'حوالة واردة: <c>أضيف</c> {AMT} إلى حسابك. المرسل: {NAME}'],
  ['salary', 'تم <c>إيداع</c> الراتب {AMT} في حسابك {ACCT} بتاريخ {DATE}. الرصيد {BAL}'],
  ['salary', 'إيداع راتب: {AMT} من {EMPLOYER} <c>أضيف</c> إلى حسابك'],
  ['fee', 'تم <d>خصم</d> رسوم خدمة بقيمة {AMT} من حسابك {ACCT} بتاريخ {DATE}'],
  ['fee', 'رسوم سنوية للبطاقة {AMT} <d>خصمت</d> من البطاقة المنتهية بـ {CARD}'],
  ['withdrawal', 'تم <d>سحب</d> مبلغ {AMT} نقداً من الصراف الآلي {ATM} بالبطاقة {CARD} بتاريخ {DATE}'],
  ['withdrawal', '<d>سحب نقدي</d>: {AMT} من حسابك {ACCT}. الرصيد المتاح {BAL}'],
  ['card_payment', 'تم <c>استلام</c> دفعة بقيمة {AMT} لبطاقتك الائتمانية المنتهية بـ {CARD} بتاريخ {DATE}. شكراً لك'],
  ['bill_payment', 'تم <d>سداد</d> فاتورة {BILLER} بمبلغ {AMT} من حسابك {ACCT} بتاريخ {DATE}'],
  ['bill_payment', 'دفع فاتورة: {BILLER}، المبلغ {AMT}، <d>تمت العملية بنجاح</d>'],
  ['otp', 'رمز التحقق {OTP} لعملية شراء بقيمة {AMT} لدى {MER}. لا تشارك الرمز مع أحد'],
  ['otp', 'كلمة المرور لمرة واحدة: {OTP} لتأكيد تحويل {AMT} إلى {NAME}'],
  ['pending', 'عملية بمبلغ {AMT} لدى {MER} <n>قيد المعالجة</n> على بطاقتك {CARD}'],
  ['pending', 'تم <n>حجز</n> مبلغ {AMT} مؤقتاً لدى {MER} وسيتم الخصم لاحقاً'],
  ['declined', 'تم <n>رفض</n> عملية شراء بقيمة {AMT} لدى {MER} بسبب عدم كفاية الرصيد'],
  ['declined', '<n>فشلت</n> عملية التحويل بمبلغ {AMT} إلى {NAME}. لم يتم خصم أي مبلغ'],
  ['promo', 'عرض خاص من {BANK}: احصل على استرداد نقدي 10% عند الإنفاق {AMT} لدى {MER}. تطبق الشروط'],
  ['balance', 'رصيد حسابك {ACCT} المتاح هو {BAL} بتاريخ {DATE}'],
  ['statement', 'كشف حساب بطاقتك الائتمانية {CARD} جاهز. المبلغ المستحق {BAL} والحد الأدنى {BAL2} بتاريخ استحقاق {DATE}'],
  ['request', 'طلب {NAME} مبلغ {AMT} منك. <n>بانتظار موافقتك</n>'],
  ['future', '<n>سيتم خصم</n> قسط بقيمة {AMT} لصالح {BILLER} بتاريخ {DATE}'],
];

T.es = [
  ['purchase', '{BANK}: <d>Compra</d> aprobada por {AMT} en {MER} con tu tarjeta terminada en {CARD} el {DATE}.'],
  ['purchase', 'Se realizó un <d>cargo</d> de {AMT} en {MER} a tu tarjeta *{CARD}. Fecha: {DATE}.'],
  ['purchase', '{BANK} informa: <d>compra</d> {AMT} {MER} tarj. ****{CARD} {DATE} {TIME}'],
  ['refund', '<c>Devolución</c> de {AMT} de {MER} abonada en tu tarjeta terminada en {CARD} el {DATE}.'],
  ['refund', 'Te hemos <c>abonado</c> {AMT} por un reembolso de {MER}.'],
  ['transfer_out', 'Has <d>enviado</d> una transferencia de {AMT} a {NAME} el {DATE}.'],
  ['transfer_out', 'Transferencia <d>realizada</d>: {AMT} a {NAME}. Cuenta {ACCT}. Ref {REF}.'],
  ['transfer_in', 'Has <c>recibido</c> una transferencia de {AMT} de {NAME} el {DATE}.'],
  ['transfer_in', '{BANK}: <c>abono</c> por transferencia de {NAME} por {AMT} en tu cuenta {ACCT}.'],
  ['salary', 'Tu nómina de {AMT} ha sido <c>abonada</c> en tu cuenta {ACCT} el {DATE}.'],
  ['salary', '<c>Depósito</c> de nómina {EMPLOYER} por {AMT} el {DATE}.'],
  ['fee', 'Se ha <d>cobrado</d> una comisión de mantenimiento de {AMT} en tu cuenta {ACCT} el {DATE}.'],
  ['fee', 'Cuota anual de tarjeta {AMT} <d>cargada</d> a la tarjeta *{CARD}.'],
  ['withdrawal', '<d>Retiro</d> en cajero de {AMT} con tu tarjeta *{CARD} el {DATE} en {ATM}.'],
  ['withdrawal', 'Has <d>retirado</d> {AMT} en efectivo del cajero {ATM}. Saldo disponible {BAL}.'],
  ['card_payment', 'Hemos <c>recibido</c> tu pago de {AMT} a tu tarjeta de crédito terminada en {CARD} el {DATE}.'],
  ['bill_payment', 'Pago de {BILLER} por {AMT} <d>realizado</d> con éxito el {DATE}. Folio {REF}.'],
  ['bill_payment', 'Se <d>pagó</d> tu recibo de {BILLER} por {AMT} desde tu cuenta {ACCT}.'],
  ['otp', '{BANK}: Tu código de verificación es {OTP} para la compra de {AMT} en {MER}. No lo compartas.'],
  ['otp', 'Clave de seguridad {OTP} para autorizar la transferencia de {AMT} a {NAME}.'],
  ['pending', 'Tu compra de {AMT} en {MER} está <n>pendiente</n> de confirmación.'],
  ['pending', 'Transferencia de {AMT} a {NAME} <n>en proceso</n>. Te avisaremos cuando se complete.'],
  ['declined', 'Tu compra de {AMT} en {MER} fue <n>rechazada</n> por fondos insuficientes.'],
  ['declined', 'Operación <n>no autorizada</n>: {AMT} en {MER} con tu tarjeta *{CARD}.'],
  ['promo', '¡Aprovecha! Gana 15% de reembolso en {MER} por compras mayores a {AMT}. Aplican restricciones.'],
  ['balance', 'El saldo disponible de tu cuenta {ACCT} es {BAL} al {DATE}.'],
  ['statement', 'Tu estado de cuenta de la tarjeta *{CARD} está listo. Pago mínimo {BAL}, fecha límite {DATE}.'],
  ['request', '{NAME} te ha <n>solicitado</n> {AMT}. Acepta o rechaza la solicitud en la app.'],
  ['future', 'Recordatorio: el cargo automático de {AMT} de {BILLER} se <n>realizará</n> el {DATE}.'],
];

T.pt = [
  ['purchase', '{BANK}: <d>Compra</d> aprovada no cartão final {CARD}: {AMT} em {MER} em {DATE}.'],
  ['purchase', 'Você <d>gastou</d> {AMT} em {MER} com o cartão {CARD} no dia {DATE}.'],
  ['purchase', '<d>Compra no débito</d>: {MER}, valor {AMT}, {DATE} {TIME}. Cartão final {CARD}.'],
  ['refund', '<c>Estorno</c> de {AMT} referente a {MER} creditado no cartão final {CARD}.'],
  ['refund', 'Você recebeu um <c>reembolso</c> de {AMT} de {MER} em {DATE}.'],
  ['transfer_out', 'Pix <d>enviado</d>: {AMT} para {NAME} em {DATE}.'],
  ['transfer_out', 'Transferência de {AMT} <d>realizada</d> para {NAME}. Conta {ACCT}.'],
  ['transfer_in', 'Pix <c>recebido</c>: {AMT} de {NAME} em {DATE}.'],
  ['transfer_in', 'Você <c>recebeu</c> uma transferência de {AMT} de {NAME} na conta {ACCT}.'],
  ['salary', 'Salário de {AMT} <c>creditado</c> na sua conta {ACCT} em {DATE}.'],
  ['salary', '<c>Crédito</c> de salário {EMPLOYER}: {AMT}.'],
  ['fee', 'Tarifa de manutenção de {AMT} <d>debitada</d> da sua conta em {DATE}.'],
  ['fee', 'Anuidade do cartão {AMT} <d>cobrada</d> no cartão final {CARD}.'],
  ['withdrawal', '<d>Saque</d> de {AMT} realizado no caixa {ATM} em {DATE}.'],
  ['withdrawal', 'Você <d>sacou</d> {AMT} com o cartão final {CARD}. Saldo {BAL}.'],
  ['card_payment', '<c>Recebemos</c> o pagamento de {AMT} da fatura do cartão final {CARD} em {DATE}.'],
  ['bill_payment', 'Pagamento de boleto {BILLER} no valor de {AMT} <d>efetuado</d> em {DATE}.'],
  ['bill_payment', 'Conta de {BILLER} <d>paga</d>: {AMT} debitados da sua conta.'],
  ['otp', 'Seu código de segurança é {OTP} para a compra de {AMT} em {MER}. Não compartilhe.'],
  ['otp', '{BANK}: código {OTP} para confirmar Pix de {AMT} para {NAME}.'],
  ['pending', 'Compra de {AMT} em {MER} <n>em processamento</n>.'],
  ['pending', 'Pix de {AMT} para {NAME} <n>em análise</n>.'],
  ['declined', 'Compra de {AMT} em {MER} <n>recusada</n> no cartão final {CARD}.'],
  ['declined', 'Transação <n>não aprovada</n>: {AMT} em {MER}. Saldo insuficiente.'],
  ['promo', 'Oferta {BANK}: ganhe 10% de cashback em compras acima de {AMT} na {MER}.'],
  ['balance', 'Saldo disponível na conta {ACCT}: {BAL} em {DATE}.'],
  ['statement', 'Sua fatura do cartão final {CARD} fechou: total {BAL}, vencimento {DATE}.'],
  ['request', '{NAME} te enviou uma <n>cobrança</n> Pix de {AMT}. Pague pelo app.'],
  ['future', 'Pix <n>agendado</n>: {AMT} para {NAME} em {DATE}.'],
];

T.fr = [
  ['purchase', '{BANK} : <d>Paiement</d> par carte de {AMT} chez {MER} le {DATE}. Carte **{CARD}.'],
  ['purchase', 'Achat de {AMT} chez {MER} <d>débité</d> sur votre carte se terminant par {CARD}.'],
  ['purchase', '<d>Opération carte</d> : {MER} {AMT} le {DATE}. Solde disponible : {BAL}.'],
  ['refund', '<c>Remboursement</c> de {AMT} de {MER} crédité sur votre carte {CARD} le {DATE}.'],
  ['refund', 'Un avoir de {AMT} de {MER} a été <c>crédité</c> sur votre compte.'],
  ['transfer_out', 'Virement de {AMT} <d>émis</d> vers {NAME} le {DATE}.'],
  ['transfer_out', 'Votre virement de {AMT} à {NAME} a été <d>effectué</d>.'],
  ['transfer_in', 'Virement <c>reçu</c> de {NAME} : {AMT} crédité sur votre compte {ACCT} le {DATE}.'],
  ['transfer_in', 'Vous avez <c>reçu</c> {AMT} de {NAME}.'],
  ['salary', 'Votre salaire de {AMT} a été <c>crédité</c> sur votre compte le {DATE}.'],
  ['salary', 'Virement <c>reçu</c> de {EMPLOYER} (salaire) : {AMT}.'],
  ['fee', 'Frais de tenue de compte de {AMT} <d>prélevés</d> le {DATE}.'],
  ['fee', 'Cotisation carte {AMT} <d>débitée</d> sur votre compte {ACCT}.'],
  ['withdrawal', '<d>Retrait</d> DAB de {AMT} le {DATE} avec votre carte {CARD}.'],
  ['withdrawal', 'Retrait d’espèces de {AMT} <d>débité</d> au distributeur {ATM}.'],
  ['card_payment', 'Nous avons <c>reçu</c> votre remboursement de {AMT} sur votre carte de crédit {CARD}.'],
  ['bill_payment', 'Prélèvement {BILLER} de {AMT} <d>débité</d> le {DATE}.'],
  ['bill_payment', 'Votre facture {BILLER} de {AMT} a été <d>payée</d>.'],
  ['otp', 'Votre code de sécurité est {OTP} pour valider un paiement de {AMT} chez {MER}.'],
  ['otp', '{BANK} : code {OTP} pour confirmer le virement de {AMT}. Ne le communiquez jamais.'],
  ['pending', 'Paiement de {AMT} chez {MER} <n>en attente</n> de validation.'],
  ['pending', 'Virement de {AMT} vers {NAME} <n>en cours de traitement</n>.'],
  ['declined', 'Paiement de {AMT} chez {MER} <n>refusé</n>. Carte {CARD}.'],
  ['declined', 'Votre virement de {AMT} à {NAME} a <n>échoué</n>. Aucun débit effectué.'],
  ['promo', 'Offre {BANK} : 5% remboursés chez {MER} dès {AMT} d’achat.'],
  ['balance', 'Solde de votre compte {ACCT} au {DATE} : {BAL}.'],
  ['statement', 'Votre relevé de carte {CARD} est disponible. Montant dû {BAL} avant le {DATE}.'],
  ['request', '{NAME} vous a envoyé une <n>demande</n> de paiement de {AMT}.'],
  ['future', 'Prélèvement {BILLER} de {AMT} <n>prévu</n> le {DATE}.'],
];

T.de = [
  ['purchase', '{BANK}: <d>Kartenzahlung</d> über {AMT} bei {MER} am {DATE}. Karte endet auf {CARD}.'],
  ['purchase', 'Umsatz: {MER} {AMT} <d>belastet</d> am {DATE}.'],
  ['purchase', 'Sie haben mit Ihrer Karte *{CARD} {AMT} bei {MER} <d>bezahlt</d>.'],
  ['refund', '<c>Gutschrift</c> von {AMT} von {MER} auf Ihre Karte {CARD} am {DATE}.'],
  ['refund', '<c>Erstattung</c> {AMT} von {MER} wurde Ihrem Konto gutgeschrieben.'],
  ['transfer_out', 'Überweisung über {AMT} an {NAME} <d>ausgeführt</d> am {DATE}.'],
  ['transfer_out', 'Sie haben {AMT} an {NAME} <d>gesendet</d>.'],
  ['transfer_in', '<c>Eingang</c>: {AMT} von {NAME} auf Konto {ACCT} am {DATE}.'],
  ['transfer_in', 'Sie haben {AMT} von {NAME} <c>erhalten</c>.'],
  ['salary', 'Gehalt {AMT} von {EMPLOYER} <c>gutgeschrieben</c> am {DATE}.'],
  ['salary', '<c>Lohneingang</c> {AMT} auf Ihr Konto {ACCT}.'],
  ['fee', 'Kontoführungsgebühr {AMT} <d>abgebucht</d> am {DATE}.'],
  ['fee', 'Jahresgebühr Kreditkarte {AMT} <d>belastet</d>.'],
  ['withdrawal', '<d>Bargeldabhebung</d> {AMT} am Geldautomat {ATM} am {DATE}.'],
  ['withdrawal', 'Sie haben {AMT} am Automaten <d>abgehoben</d>. Kontostand {BAL}.'],
  ['card_payment', 'Ihre Zahlung von {AMT} auf die Kreditkarte {CARD} ist <c>eingegangen</c>.'],
  ['bill_payment', 'Lastschrift {BILLER} {AMT} <d>abgebucht</d> am {DATE}.'],
  ['bill_payment', 'Rechnung {BILLER} über {AMT} <d>bezahlt</d>.'],
  ['otp', 'Ihr Sicherheitscode lautet {OTP} für die Zahlung von {AMT} bei {MER}.'],
  ['otp', '{BANK}: TAN {OTP} für Überweisung {AMT} an {NAME}.'],
  ['pending', 'Zahlung {AMT} bei {MER} ist <n>vorgemerkt</n>.'],
  ['pending', 'Überweisung {AMT} an {NAME} wird <n>bearbeitet</n>.'],
  ['declined', 'Kartenzahlung {AMT} bei {MER} <n>abgelehnt</n>.'],
  ['declined', 'Ihre Überweisung über {AMT} ist <n>fehlgeschlagen</n>. Es wurde nichts abgebucht.'],
  ['promo', 'Nur diese Woche: 10% Cashback bei {MER} ab {AMT} Einkaufswert.'],
  ['balance', 'Ihr Kontostand am {DATE}: {BAL}.'],
  ['statement', 'Ihre Kreditkartenabrechnung ist da: Gesamtbetrag {BAL}, fällig am {DATE}.'],
  ['request', '{NAME} hat {AMT} von Ihnen <n>angefordert</n>.'],
  ['future', 'Dauerauftrag {AMT} an {NAME} wird am {DATE} <n>ausgeführt werden</n>.'],
];

T.it = [
  ['purchase', '{BANK}: <d>pagamento</d> con carta {CARD} di {AMT} presso {MER} il {DATE}.'],
  ['purchase', 'Hai <d>speso</d> {AMT} da {MER} con la carta *{CARD}.'],
  ['purchase', '<d>Addebito</d> carta: {MER} {AMT} {DATE}.'],
  ['refund', '<c>Rimborso</c> di {AMT} da {MER} accreditato sulla carta {CARD}.'],
  ['refund', 'Storno di {AMT} da {MER} <c>accreditato</c> il {DATE}.'],
  ['transfer_out', 'Bonifico di {AMT} a {NAME} <d>eseguito</d> il {DATE}.'],
  ['transfer_out', 'Hai <d>inviato</d> {AMT} a {NAME}.'],
  ['transfer_in', 'Bonifico <c>ricevuto</c> da {NAME}: {AMT} il {DATE}.'],
  ['transfer_in', '<c>Accredito</c> di {AMT} da {NAME} sul conto {ACCT}.'],
  ['salary', 'Stipendio di {AMT} <c>accreditato</c> sul conto il {DATE}.'],
  ['salary', '<c>Accredito stipendio</c> {EMPLOYER} {AMT}.'],
  ['fee', 'Canone mensile di {AMT} <d>addebitato</d> il {DATE}.'],
  ['fee', 'Commissione di {AMT} <d>addebitata</d> sul conto {ACCT}.'],
  ['withdrawal', '<d>Prelievo</d> di {AMT} allo sportello {ATM} il {DATE}.'],
  ['withdrawal', 'Hai <d>prelevato</d> {AMT} con la carta {CARD}. Saldo {BAL}.'],
  ['card_payment', 'Abbiamo <c>ricevuto</c> il pagamento di {AMT} sulla tua carta di credito {CARD}.'],
  ['bill_payment', 'Bolletta {BILLER} di {AMT} <d>pagata</d> il {DATE}.'],
  ['bill_payment', 'Addebito diretto {BILLER} {AMT} <d>eseguito</d>.'],
  ['otp', 'Il codice di sicurezza {OTP} serve per autorizzare il pagamento di {AMT} presso {MER}.'],
  ['otp', 'Codice {OTP} per confermare il bonifico di {AMT}. Non condividerlo.'],
  ['pending', 'Pagamento di {AMT} presso {MER} <n>in attesa</n> di contabilizzazione.'],
  ['pending', 'Bonifico di {AMT} a {NAME} <n>in lavorazione</n>.'],
  ['declined', 'Pagamento di {AMT} presso {MER} <n>rifiutato</n>.'],
  ['declined', 'Operazione <n>non riuscita</n>: {AMT} presso {MER}. Nessun addebito.'],
  ['promo', 'Solo per te: 10% di cashback da {MER} con una spesa minima di {AMT}.'],
  ['balance', 'Il saldo disponibile del conto {ACCT} al {DATE} è {BAL}.'],
  ['statement', 'Estratto conto carta {CARD} disponibile: totale {BAL}, scadenza {DATE}.'],
  ['request', '{NAME} ti ha inviato una <n>richiesta</n> di {AMT}.'],
  ['future', 'Addebito {BILLER} di {AMT} <n>previsto</n> per il {DATE}.'],
];

T.nl = [
  ['purchase', '{BANK}: <d>Betaling</d> van {AMT} bij {MER} op {DATE} met pas {CARD}.'],
  ['purchase', 'U heeft {AMT} <d>betaald</d> bij {MER}.'],
  ['purchase', 'Pinbetaling {MER} {AMT} <d>afgeschreven</d> op {DATE}.'],
  ['refund', '<c>Terugbetaling</c> van {AMT} van {MER} bijgeschreven op {DATE}.'],
  ['refund', '{AMT} van {MER} <c>teruggestort</c> op uw rekening {ACCT}.'],
  ['transfer_out', 'Overboeking van {AMT} naar {NAME} <d>uitgevoerd</d> op {DATE}.'],
  ['transfer_out', 'U heeft {AMT} <d>overgemaakt</d> naar {NAME}.'],
  ['transfer_in', 'U heeft {AMT} <c>ontvangen</c> van {NAME} op {DATE}.'],
  ['transfer_in', '<c>Bijschrijving</c> {AMT} van {NAME} op rekening {ACCT}.'],
  ['salary', 'Salaris {AMT} van {EMPLOYER} <c>bijgeschreven</c> op {DATE}.'],
  ['fee', 'Kosten betaalpakket {AMT} <d>afgeschreven</d> op {DATE}.'],
  ['withdrawal', '<d>Geldopname</d> {AMT} bij geldautomaat {ATM} op {DATE}.'],
  ['withdrawal', 'U heeft {AMT} <d>opgenomen</d>. Saldo {BAL}.'],
  ['card_payment', 'Uw betaling van {AMT} op creditcard {CARD} is <c>ontvangen</c>.'],
  ['bill_payment', 'Incasso {BILLER} {AMT} <d>afgeschreven</d> op {DATE}.'],
  ['otp', 'Uw verificatiecode is {OTP} voor de betaling van {AMT} bij {MER}.'],
  ['pending', 'Betaling van {AMT} bij {MER} is <n>in behandeling</n>.'],
  ['declined', 'Betaling van {AMT} bij {MER} is <n>geweigerd</n>.'],
  ['declined', 'Overboeking van {AMT} naar {NAME} is <n>mislukt</n>.'],
  ['promo', 'Actie: 10% korting bij {MER} vanaf {AMT}.'],
  ['balance', 'Uw saldo op {DATE}: {BAL}.'],
  ['statement', 'Uw creditcardoverzicht staat klaar: totaal {BAL}, te betalen voor {DATE}.'],
  ['request', '{NAME} heeft een <n>betaalverzoek</n> van {AMT} gestuurd.'],
  ['future', '<n>Geplande</n> overboeking van {AMT} naar {NAME} op {DATE}.'],
];

T.tr = [
  ['purchase', '{BANK}: {CARD} ile biten kartınızla {DATE} tarihinde {MER} işyerinde {AMT} tutarında <d>harcama</d> yapılmıştır.'],
  ['purchase', '{MER} {AMT} <d>alışveriş</d> {DATE}. Kart no: ****{CARD}'],
  ['purchase', 'Kartınızdan {AMT} <d>tahsil edilmiştir</d>. İşyeri: {MER}.'],
  ['refund', '{MER} işyerinden {AMT} tutarında <c>iade</c> kartınıza yansımıştır.'],
  ['refund', 'Kartınıza {AMT} <c>iade edildi</c>. İşyeri: {MER}, {DATE}.'],
  ['transfer_out', 'Hesabınızdan {NAME} adlı kişiye {AMT} <d>gönderilmiştir</d>. {DATE}'],
  ['transfer_out', 'FAST ile {NAME} hesabına {AMT} <d>gönderildi</d>.'],
  ['transfer_in', 'Hesabınıza {NAME} tarafından {AMT} <c>gelen havale</c> yapılmıştır. {DATE}'],
  ['transfer_in', 'FAST ile {AMT} tutarında para <c>geldi</c>. Gönderen: {NAME}.'],
  ['salary', 'Maaşınız {AMT} hesabınıza <c>yatırılmıştır</c>. {DATE}'],
  ['fee', 'Hesap işletim ücreti {AMT} hesabınızdan <d>tahsil edilmiştir</d>.'],
  ['fee', 'Kart aidatı {AMT} kartınıza <d>yansıtılmıştır</d>.'],
  ['withdrawal', '{ATM} ATM’den {AMT} nakit <d>çekim</d> yapılmıştır. {DATE}'],
  ['card_payment', 'Kredi kartınıza {AMT} <c>ödeme</c> yapılmıştır. Kart: {CARD}'],
  ['bill_payment', '{BILLER} faturanız {AMT} <d>ödenmiştir</d>. {DATE}'],
  ['otp', '{MER} işyerindeki {AMT} tutarlı işleminiz için doğrulama kodunuz: {OTP}. Kimseyle paylaşmayınız.'],
  ['pending', '{MER} işyerindeki {AMT} tutarlı işleminiz <n>provizyon</n> aşamasındadır.'],
  ['declined', '{MER} işyerindeki {AMT} tutarlı işleminiz <n>reddedilmiştir</n>. Yetersiz bakiye.'],
  ['promo', '{MER} alışverişlerinizde {AMT} ve üzeri harcamaya 50 TL bonus! Kampanya detayları mobil uygulamada.'],
  ['balance', 'Hesabınızın {DATE} tarihli kullanılabilir bakiyesi: {BAL}.'],
  ['statement', 'Kredi kartı ekstreniz kesildi. Dönem borcu {BAL}, son ödeme tarihi {DATE}.'],
  ['request', '{NAME} sizden {AMT} <n>ödeme talep etti</n>.'],
  ['future', '{BILLER} otomatik ödemeniz {AMT} {DATE} tarihinde <n>gerçekleştirilecektir</n>.'],
];

T.id = [
  ['purchase', '{BANK}: <d>Transaksi</d> {AMT} di {MER} dengan kartu {CARD} pada {DATE} berhasil.'],
  ['purchase', 'Anda telah <d>melakukan pembayaran</d> {AMT} ke {MER} pada {DATE}.'],
  ['purchase', 'Pembelian {MER} sebesar {AMT} <d>berhasil</d>. Saldo {BAL}.'],
  ['refund', '<c>Pengembalian dana</c> {AMT} dari {MER} telah masuk ke rekening Anda.'],
  ['refund', 'Refund {AMT} dari {MER} <c>berhasil dikreditkan</c> pada {DATE}.'],
  ['transfer_out', '<d>Transfer</d> {AMT} ke {NAME} berhasil pada {DATE}.'],
  ['transfer_out', 'Dana {AMT} telah <d>dikirim</d> ke rekening {NAME}. Ref {REF}.'],
  ['transfer_in', 'Anda <c>menerima</c> transfer {AMT} dari {NAME} pada {DATE}.'],
  ['transfer_in', '<c>Dana masuk</c> {AMT} dari {NAME} ke rekening {ACCT}.'],
  ['salary', 'Gaji {AMT} dari {EMPLOYER} telah <c>masuk</c> ke rekening Anda pada {DATE}.'],
  ['fee', 'Biaya administrasi bulanan {AMT} telah <d>didebet</d> dari rekening {ACCT}.'],
  ['withdrawal', '<d>Tarik tunai</d> {AMT} di ATM {ATM} pada {DATE}. Saldo {BAL}.'],
  ['card_payment', 'Pembayaran kartu kredit {AMT} untuk kartu {CARD} telah <c>kami terima</c>.'],
  ['bill_payment', 'Pembayaran tagihan {BILLER} sebesar {AMT} <d>berhasil</d> pada {DATE}.'],
  ['bill_payment', '<d>Bayar</d> {BILLER} {AMT} sukses. No Ref {REF}.'],
  ['otp', 'JANGAN BERIKAN KODE INI KE SIAPAPUN. Kode OTP {OTP} untuk transaksi {AMT} di {MER}.'],
  ['pending', 'Transaksi {AMT} di {MER} sedang <n>diproses</n>.'],
  ['declined', 'Transaksi {AMT} di {MER} <n>gagal</n>. Saldo tidak mencukupi.'],
  ['declined', 'Transaksi {AMT} di {MER} <n>ditolak</n>.'],
  ['promo', 'Promo! Cashback 20% di {MER} min. transaksi {AMT}. S&K berlaku.'],
  ['balance', 'Saldo rekening {ACCT} per {DATE}: {BAL}.'],
  ['statement', 'Tagihan kartu kredit {CARD}: total {BAL}, jatuh tempo {DATE}.'],
  ['request', '{NAME} <n>meminta</n> pembayaran {AMT} dari Anda.'],
  ['future', 'Autodebet {BILLER} {AMT} <n>dijadwalkan</n> pada {DATE}.'],
];

T['hi-latn'] = [
  ['purchase', 'Aapke card XX{CARD} se {MER} par {AMT} ka <d>kharch</d> hua hai, {DATE}.'],
  ['purchase', '{AMT} aapke A/c XX{ACCT} se {MER} ko <d>pay kiye gaye</d> on {DATE}.'],
  ['refund', '{MER} se {AMT} ka <c>refund</c> aapke khate mein jama ho gaya hai.'],
  ['transfer_out', 'Aapke khate XX{ACCT} se {AMT} {NAME} ko <d>bheje gaye</d>. UPI Ref {REF}.'],
  ['transfer_out', '{AMT} <d>debit hue</d> aapke A/c XX{ACCT} se, {NAME} ko transfer, {DATE}.'],
  ['transfer_in', 'Aapke khate XX{ACCT} mein {NAME} se {AMT} <c>jama hue</c>, {DATE}.'],
  ['transfer_in', '{AMT} <c>credit hue</c> aapke A/c mein {NAME} se. UPI Ref {REF}.'],
  ['salary', 'Aapki salary {AMT} aapke khate mein <c>credit ho gayi</c> hai, {DATE}.'],
  ['fee', 'SMS charges {AMT} aapke khate se <d>kaate gaye</d>.'],
  ['withdrawal', 'ATM {ATM} se {AMT} <d>nikale gaye</d>, card XX{CARD}, {DATE}.'],
  ['bill_payment', '{BILLER} bill ka {AMT} ka <d>bhugtan safal</d> raha, {DATE}.'],
  ['otp', 'Aapka OTP {OTP} hai {MER} par {AMT} ke transaction ke liye. Kisi ke saath share na karein.'],
  ['pending', '{MER} par {AMT} ka transaction <n>pending</n> hai.'],
  ['declined', '{MER} par {AMT} ka transaction <n>fail ho gaya</n>. Paise nahi kate.'],
  ['promo', 'Offer! {MER} par {AMT} se zyada kharch karein aur 10% cashback paayein.'],
  ['balance', 'Aapke khate XX{ACCT} ka balance {BAL} hai, {DATE}.'],
  ['request', '{NAME} ne aapse {AMT} ki <n>request bheji</n> hai. UPI app mein approve karein.'],
  ['future', '{BILLER} ka auto-debit {AMT} {DATE} ko <n>hoga</n>.'],
];

const EVENT_LABEL = {
  purchase: { status: 'completed', family: 'purchase', direction: 'debit', merchantSlot: 'MER' },
  refund: { status: 'completed', family: 'refund', direction: 'credit', merchantSlot: 'MER' },
  transfer_out: { status: 'completed', family: 'transfer', direction: 'debit' },
  transfer_in: { status: 'completed', family: 'transfer', direction: 'credit' },
  salary: { status: 'completed', family: 'salary', direction: 'credit' },
  fee: { status: 'completed', family: 'fee', direction: 'debit' },
  withdrawal: { status: 'completed', family: 'withdrawal', direction: 'debit' },
  card_payment: { status: 'completed', family: 'card-payment', direction: 'credit' },
  bill_payment: { status: 'completed', family: 'bill-payment', direction: 'debit', merchantSlot: 'BILLER' },
  otp: { status: 'otp' },
  pending: { status: 'pending' },
  declined: { status: 'declined' },
  promo: { status: 'promo', noAmount: true },
  balance: { status: 'informational', noAmount: true },
  statement: { status: 'informational', noAmount: true },
  request: { status: 'request' },
  future: { status: 'future' },
};

module.exports = { TEMPLATES: T, EVENT_LABEL };
